### ISSUE TITLE
autocomplete feature

### ISSUE THREAD

**Issue by jupe** [jsonform/jsonform#104]
I couldn't find this feature, so I created this issue.
Autocomplete would be very useful with jsonform.
E.g. usage of jquery-ui autocomplete (http://api.jqueryui.com/autocomplete/ ).

Usage example:

```
"schema": {
   "name": {type: 'string'}
},
"form": [
    {
      "key": "name",
      "type": "string",
      "autocomplete": { ... /*jquery-ui-autocomplete parameters*/}
    }
  ]
```

**Comment by tchapi** [comment]
Closing as I think this is out of the scope of jsonform for now. And the @ulion branch has it, so if absolutely needed, its repo can be used ;)
