### ISSUE TITLE
Publish your playground as gh-pages

### ISSUE THREAD

**Issue by jonasfj** [jsonform/jsonform#113]
Your playground is a really awesome show case for this project. You should publish it to the `gh-pages` branch, it would be easier for people to discover and play it...

Having looked a few JSON-schema tools, I have to say that tools that rock as much as this, certainly isn't a given.. So you should make sure people can see it.

Trivial approach, `git push origin master:gh-pages` would do the trick, and give you `joshfire.github.io/jsonform/playground/` as a place people can test it out. I must say I had my doubts about this tool until I saw the playground. So I recommend that publish it.

**Comment by tchapi** [comment]
The playground is now available at https://jsonform.github.io/jsonform/playground/index.html
