### ISSUE TITLE
Not render in Chrome with Kentico CMS 7.x

### ISSUE THREAD

**Issue by vasu-rbt** [jsonform/jsonform#116]
Hi,
I am using Build forms from JSON Schema(downloaded from https://github.com/joshfire/jsonform). I have integrated this into Kentico CMS 7.x. it is working fine in IE and Firefox browsers but not working in Chrome and safari (no script errors). 

Please help me.

Thanks
Vasu

**Comment by tchapi** [comment]
We don't really have knowledge on Kentico CMS. If this is still an issue and you are still using this lib, feel free to repoen and give us some more details on the error
