### ISSUE TITLE
Bower package?

### ISSUE THREAD

**Issue by ielashi** [jsonform/jsonform#117]
I searched if this project is available on Bower and couldn't find it. I think it would make installation a lot easier if a bower package became available.

**Comment by tchapi** [comment]
Bower now recommends to use `npm` or `yarn` and  `webpack`: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

The process of adding jsonform to the npm repository is pending. In due time, I will add a mention in the docs on how to use it with webpack and the like.
