### ISSUE TITLE
How do I escape string type in properties?

### ISSUE THREAD

**Issue by wpoosanguansit** [jsonform/jsonform#121]
Hi, 

I have a need to declare:
           "properties": {
                  "type": {
                      "type": "string",
                      "title": "Type",
                      "enum": ["objectType"]
                  },
             }
However, type is not allowed in the properties's key.  Is there a way to escape the string?  Thanks for your help.

**Comment by tchapi** [comment]
I guess this issue is a bit outdated. Feel free to reopen @wpoosanguansit if you still have a problem
