### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by kiro** [jsonform/jsonform#123]
Hi, I think it will be really useful in your documentation if you show what the form the schema examples looks like. 

Also it will be more convenient to host the playground somewhere.

**Comment by nise** [comment]
Agreed, because the example in the README.md is not working out of the box.

**Comment by ulion** [comment]
though you can see the hosted playground on my patched fork: http://ulion.github.io/jsonform/playground/

**Comment by tchapi** [comment]
The playground is hosted now too : https://jsonform.github.io/jsonform/playground/index.html 🎉
