### ISSUE TITLE
onSubmit function won't go anywhere in the examples

### ISSUE THREAD

**Issue by pduer** [jsonform/jsonform#129]
Hey all, this might just be my own ignorance. But, I find that when you use the onSubmit function in the exmaples, that then after global validation that the form submission is not made. That's to say that the server doesn't get called with the post/get operation.

Am I just missunderstanding it?

**Comment by RobKav252** [comment]
if you were doing things like me, I was trying to attach the form to a DIV element, and "onSubmit" would never called, try changing the DIV with a FORM tag and you should get the JSON with all the data from the form.

**Comment by tchapi** [comment]
@ulion is right on this, closing for now. Please open a new issue if you still have questions
