### ISSUE TITLE
Incorrect validation of optional object with required property

### ISSUE THREAD

**Issue by schaman** [jsonform/jsonform#130]
Suppose a schema of a customer with optional address:

```
{
  title: "Customer",
  type: "object",
  properties: {
    name: { type: "string", title: "Name", required: true },
    address: {
      type: "object",
      title: "Address",
      required: false,
      properties: {
        street: { type: "string", title: "Street", required: true },
        city: { type: "string", title: "City", required: true }
      }
    }
  }
}
```

For JSON it means:
- when address **is not present**, the document is valid since
  address is not required
- when address **is present**, it must satisfy the definition
  provided, as specified in the 'address' definition.

Using generated form I don't have a chance to fill in customer without an address – the form is not submitting because browser says that the address.street is required.

**Comment by tchapi** [comment]
I would be happy to review and implement it in this repo if @ulion you can point me to the commit(s) that enable this behaviour in your specific branch ?
Thanks a lot
