### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'ownerDocument' of null

### ISSUE THREAD

**Issue by lbischof** [jsonform/jsonform#131]
When I upgrade underscore to 1.7 I get an error in chrome console:

Uncaught TypeError: Cannot read property 'ownerDocument' of null

It works with 1.6

**Comment by ryanitus** [comment]
Any thoughts on merging this change to master?  Just downloaded master and it doesn't work with 1.7 version of underscore.

**Comment by tchapi** [comment]
Underscore has been bumped up to 1.8.3 (see merged PR https://github.com/jsonform/jsonform/pull/146), and fixes have been made in the repo. Let us know if this is still an issue
