### ISSUE TITLE
Title with value of array property

### ISSUE THREAD

**Issue by thenewguy** [jsonform/jsonform#133]
I've also posted the issue here https://github.com/ulion/jsonform/issues/3 but I am not sure what the active repo is, so I am reposting here.

Support the use of {{ value }} template to reference properties with an object type 

I.e. with the following, the titles would be "Friend Foo" and "Friend Bar" if two friends were added with nicknames of "Foo" and "Bar"

```
{
  "schema": {
    "friends": {
      "type": "array",
      "items": {
        "type": "object",
        "title": "Friend {{ value.nick }}",
        "properties": {
          "nick": {
            "type": "string",
            "title": "Nickname",
            "required": true
          },
          "gender": {
            "type": "string",
            "title": "Gender",
            "enum": [ "male", "female", "alien" ]
          },
          "age": {
            "type": "integer",
            "title": "Age"
          }
        }
      }
    }
  }
}
```

**Comment by tchapi** [comment]
It seems @ulion has already answered here : https://github.com/ulion/jsonform/issues/3 so I'm closing this issue for now
