### ISSUE TITLE
Multiple Select Support

### ISSUE THREAD

**Issue by MattJakeman** [jsonform/jsonform#135]
Is there any support for a select that can have multiple options selected? I have looked through the documentation but can't seem to find any reference to it.

I am looking for something that provides the same functionality as the following if possible: 

![code](https://cloud.githubusercontent.com/assets/294255/5662934/9a9e9da6-9737-11e4-9bd8-75bcf288c4cf.png)

Allowing the user to select more than one option from the list.

**Comment by ulion** [comment]
I guess checkboxes type is what you required

2015-01-08 21:02 GMT+08:00 MattJakeman <notifications@github.com>:

> Is there any support for a select that can have multiple options selected?
> I have looked through the documentation but can't seem to find any
> reference to it.
>
> I am looking for something that provides the same functionality as the
> following if possible:
>
>
> option 1
> option 2
> option 3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshfire/jsonform/issues/135>.
>



-- 
Ulion

**Comment by MattJakeman** [comment]
This has crossed my mind but unfortunately I have been asked not to implement it like that for some reason. I'll look into other options. Thanks for the response.

**Comment by ulion** [comment]
then you may consider integrate bootstrap-multiselect with jsonform,
pull request is welcome.


2015-01-08 21:43 GMT+08:00 MattJakeman <notifications@github.com>:
>
> This has crossed my mind but unfortunately I have been asked not to implement it like that for some reason. I'll look into other options. Thanks for the response.
>
> —
> Reply to this email directly or view it on GitHub.




-- 
Ulion

**Comment by MattJakeman** [comment]
Great, thanks. I hadn't come across that, it looks like exactly what I need. I'll have a look at integrating it and come back with a pull request if I do.
