### ISSUE TITLE
Adding classes to 'select' elements(drop-downs), checkboxes, and radio buttons is not currently supported.

### ISSUE THREAD

**Issue by Shad0wLi0n** [jsonform/jsonform#137]
The "fieldHtmlClass" function does not support select elements or their options as well as checkboxes and radio buttons. It would be nice to add classes to these elements.

**Comment by ulion** [comment]
if you checkout my fork, you will found the select field type do support
fieldHtmlClass.
the checkboxes and radios types do not support it. but you can always give
any form definition an "id", then you can always use the id to css the
fields you want affect.
and htmlClass is also a possibility, or more generally
"[data-jsonform-type=typename]" in my fork to css certain type fields.

2015-02-21 3:51 GMT+08:00 Scott <notifications@github.com>:

> The "fieldHtmlClass" function does not support select elements or their
> options as well as checkboxes and radio buttons. It would be nice to add
> classes to these elements.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshfire/jsonform/issues/137>.
>



-- 
Ulion

**Comment by Shad0wLi0n** [comment]
Thanks but I've actually edited the JS file to include support for adding classes to any element. Including fixing the select element. I'll post it online later.

-Scott

**Comment by tchapi** [comment]
It's now supported on `master`
