### ISSUE TITLE
Question: how to create a sub form type functionality and go back to main form

### ISSUE THREAD

**Issue by ikeamanual** [jsonform/jsonform#139]
Hi,

This is not really a Jsonform question, but a Javascript question about using forms ...

I have a jsonform custom select field with a datalist. If the user enters a unknown value, I want to present a new form so that he can enter more information about the new value.

I have created the new page with a new seperate Jsonform in newStoreForm.html.
When the user enters an unkown value I do:

window.location = "newStoreForm.html";

In the onSubmit() of the newStoreForm I do:

window.history.back(); return false;

I go back but all my previous info is gone and the original page is reloaded...
By the way, I am running all this locally without a server in node-webkit http://nwjs.io/.

Is there a way to achieve this functionality without manually storing the whole state of the main page and rebuilding it manually?

Maybe use the newStoreForm jsonform in jquery Dialog?
Any examples?

thanks,

Peter

**Comment by ikeamanual** [comment]
I used jquery modal dialog

**Comment by tchapi** [comment]
_I'm closing this issue since it is probably outdated (and probably out of the scope of jsonform) — Please reopen if you still need help on this. Thanks_

**Comment by jcmertz** [comment]
> I used jquery modal dialog

Hi @ike

> I used jquery modal dialog

@ikeamanual I am currently trying to use this library in a jquery dialog and am having trouble. I can't get the onSubmit function to get called when the submit button is pressed. I can get all of the examples working fine if I don't run them in a dialog, but the submit button stops working when in a dialog. Did you happen to run into anything like this?
