### ISSUE TITLE
Json code does not work

### ISSUE THREAD

**Issue by ivantowers** [jsonform/jsonform#141]
Hello i have a form builder that show as a result this json code;

{"fields":[{"label":"Name","field_type":"text","required":true,"field_options":{"size":"small"},"cid":"c14"},{"label":"Phone","field_type":"text","required":true,"field_options":{"size":"small"},"cid":"c18"},{"label":"Select an option","field_type":"radio","required":true,"field_options":{"options":[{"label":"Option 1","checked":false},{"label":"Option 2","checked":false}]},"cid":"c22"},{"label":"Date","field_type":"date","required":true,"field_options":{},"cid":"c26"}]} 

If i paste into the example file does not work. What im doing wrong? How i make it work? 

thanks!

**Comment by ulion** [comment]
your json code format is not for the json schema form. that's why it not
works here.

2015-05-16 3:02 GMT+08:00 ivantowers <notifications@github.com>:

> Hello i have a form builder that show as a result this json code;
>
> {"fields":[{"label":"Name","field_type":"text","required":true,"field_options":{"size":"small"},"cid":"c14"},{"label":"Phone","field_type":"text","required":true,"field_options":{"size":"small"},"cid":"c18"},{"label":"Select
> an
> option","field_type":"radio","required":true,"field_options":{"options":[{"label":"Option
> 1","checked":false},{"label":"Option
> 2","checked":false}]},"cid":"c22"},{"label":"Date","field_type":"date","required":true,"field_options":{},"cid":"c26"}]}
>
>
> If i paste into the example file does not work. What im doing wrong? How i
> make it work?
>
> thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshfire/jsonform/issues/141>.
>



-- 
Ulion

**Comment by ajw93** [comment]
@ivantowers I am working with the same form builder as you, I think, and am now working on doing transforming the produced JSON into a proper readable schema for this renderer. (I use C#)

If you would like, let me know and I will be glad to share when I am done.
