### ISSUE TITLE
Update select field data.

### ISSUE THREAD

**Issue by Etheriq** [jsonform/jsonform#144]
Hi!
Help me please. I have two select field. When i select something in first field i get from server some date and this data need set to second select field. How i can do this? Thanks for help. 
Example my schema:

``` javascript
var clientKeys = ["1", "2", "3"],
    clientObj = {
        "1": "cl 1",
        "2": "cl 2",
        "3": "cl 3"
    },
    categoryKeys = ["1", "2", "3"],
    categoryObj = {
        "1": "cat 1",
        "2": "cat 2",
        "3": "cat 3"
    };

var formSchema = {
    "schema": {
        "car_job": {
            "type": "object",
            "properties": {
                "client": {
                    "type": "string",
                    "title": "Client",
                    "enum": [
                        "1", "2", "3"
                    ]
                },
                "car": {
                    "type": "string",
                    "title": "Car",
                    "enum": clientKeys
                },
                "jobDate": {
                    "type": "string",
                    "title": "Job date",
                    "default": moment().format("DD.MM.YYYY")
                },
                "carCategories": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "title": "Job category:",
                        "properties": {
                            "jobCategory": {
                                "type": "string",
                                "title": "JobCat",
                                "enum": categoryKeys
                            },
                            "jobDescriptions": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "title": "Job description:",
                                    "properties": {
                                        "description": {
                                            "type": "string",
                                            "title": "Description"
                                        },
                                        "price": {
                                            "type": "number",
                                            "title": "Price"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "form": [
        {
            "key": "car_job.car",
            "titleMap": {
                "1": "car 1",
                "2": "car 2",
                "3": "car 3"
            },
            "onChange": function (e) {
                var val = $(e.target).val();

                var data = 'get new data from server by val'

                clientKeys = data.keys;
                clientObj = data.obj;
            }
        },
        {
            "type": "button",
            "title": "<i class='fa fa-plus'></i>&nbsp;&nbsp;<i class='fa fa-user'></i>",
            "onClick": function(e, values){
                e.preventDefault();

                alert("add user");
            }
        },
        {
            "key": "car_job.client",
            "titleMap": clientObj
        },
        {
            "type": "button",
            "title": "<i class='fa fa-plus'></i>&nbsp;&nbsp;<i class='fa fa-car'></i>",
            "htmlClass": "clearfix col-md-2 col-lg-2 col-sm-3 col-xs-4 text-right row-not-padding",
            "onClick": function(e){
                e.preventDefault();

                alert("add car");
            }
        },
        {
            "key": "car_job.jobDate",
            "fieldHtmlClass": "jod-date-picker"
        },
        {
            "type": "array",
            "items": {
                "type": "section",
                "items": [
                    {
                        "key": "car_job.carCategories[].jobCategory",
                        "titleMap": categoryObj
                    },
                    {
                        "type": "array",
                        "items": [
                            "car_job.carCategories[].jobDescriptions[]"
                        ]
                    }
                ]
            }
        },
        {
            "type": "submit",
            "title": "Create"
        }
    ],
    //"value": {
    //    "car_job": {
    //        "jobDate": "09.07.2015",
    //        "client": "3",
    //        "car": "2",
    //        "carCategories": [
    //            {
    //                "jobCategory": "1",
    //                "jobDescriptions": [
    //                    {
    //                        "price": 14.6
    //                    },
    //                    {
    //                        "description": "xxxxxx",
    //                        "price": 45.2
    //                    }
    //                ]
    //            },
    //            {
    //                "jobCategory": "3",
    //                "jobDescriptions": [
    //                    {
    //                        "price": 100
    //                    },
    //                    {
    //                        "description": "zzzzzzz",
    //                        "price": 250.5
    //                    }
    //                ]
    //            }
    //        ]
    //    }
    //},
    onSubmit: function(errors, values){
        alert('Values object:\n' + JSON.stringify(values, null, 2));
        console.log(values);
    }
};

jQuery(function ($) {

    var formObj = $("#custom_form form");
    formObj.jsonForm(formSchema);

});
```

**Comment by ulion** [comment]
jsonform simply do not support the 2-level select options chain.

maybe you want try angular-schema-form

or implement that by jquery change the options of the 2nd select when the
first select value changed.

2015-07-09 17:12 GMT+08:00 Yuriy Tarnavskiy <notifications@github.com>:

> Hi!
> Help me please. I have two select field. When i select something in first
> field i get from server some date and this data need set to second select
> field. How i can do this? Thanks for help.
> Example my schema:
>
> var clientKeys = ["1", "2", "3"],
>     clientObj = {
>         "1": "cl 1",
>         "2": "cl 2",
>         "3": "cl 3"
>     },
>     categoryKeys = ["1", "2", "3"],
>     categoryObj = {
>         "1": "cat 1",
>         "2": "cat 2",
>         "3": "cat 3"
>     };
> var formSchema = {
>     "schema": {
>         "car_job": {
>             "type": "object",
>             "properties": {
>                 "client": {
>                     "type": "string",
>                     "title": "Client",
>                     "enum": [
>                         "1", "2", "3"
>                     ]
>                 },
>                 "car": {
>                     "type": "string",
>                     "title": "Car",
>                     "enum": clientKeys
>                 },
>                 "jobDate": {
>                     "type": "string",
>                     "title": "Job date",
>                     "default": moment().format("DD.MM.YYYY")
>                 },
>                 "carCategories": {
>                     "type": "array",
>                     "items": {
>                         "type": "object",
>                         "title": "Job category:",
>                         "properties": {
>                             "jobCategory": {
>                                 "type": "string",
>                                 "title": "JobCat",
>                                 "enum": categoryKeys
>                             },
>                             "jobDescriptions": {
>                                 "type": "array",
>                                 "items": {
>                                     "type": "object",
>                                     "title": "Job description:",
>                                     "properties": {
>                                         "description": {
>                                             "type": "string",
>                                             "title": "Description"
>                                         },
>                                         "price": {
>                                             "type": "number",
>                                             "title": "Price"
>                                         }
>                                     }
>                                 }
>                             }
>                         }
>                     }
>                 }
>             }
>         }
>     },
>     "form": [
>         {
>             "key": "car_job.car",
>             "titleMap": {
>                 "1": "car 1",
>                 "2": "car 2",
>                 "3": "car 3"
>             },
>             "onChange": function (e) {
>                 var val = $(e.target).val();
>
>                 var data = 'get new data from server by val'
>
>                 clientKeys = data.keys;
>                 clientObj = data.obj;
>             }
>         },
>         {
>             "type": "button",
>             "title": "<i class='fa fa-plus'></i>&nbsp;&nbsp;<i class='fa fa-user'></i>",
>             "onClick": function(e, values){
>                 e.preventDefault();
>
>                 alert("add user");
>             }
>         },
>         {
>             "key": "car_job.client",
>             "titleMap": clientObj
>         },
>         {
>             "type": "button",
>             "title": "<i class='fa fa-plus'></i>&nbsp;&nbsp;<i class='fa fa-car'></i>",
>             "htmlClass": "clearfix col-md-2 col-lg-2 col-sm-3 col-xs-4 text-right row-not-padding",
>             "onClick": function(e){
>                 e.preventDefault();
>
>                 alert("add car");
>             }
>         },
>         {
>             "key": "car_job.jobDate",
>             "fieldHtmlClass": "jod-date-picker"
>         },
>         {
>             "type": "array",
>             "items": {
>                 "type": "section",
>                 "items": [
>                     {
>                         "key": "car_job.carCategories[].jobCategory",
>                         "titleMap": categoryObj
>                     },
>                     {
>                         "type": "array",
>                         "items": [
>                             "car_job.carCategories[].jobDescriptions[]"
>                         ]
>                     }
>                 ]
>             }
>         },
>         {
>             "type": "submit",
>             "title": "Create"
>         }
>     ],
>     //"value": {
>     //    "car_job": {
>     //        "jobDate": "09.07.2015",
>     //        "client": "3",
>     //        "car": "2",
>     //        "carCategories": [
>     //            {
>     //                "jobCategory": "1",
>     //                "jobDescriptions": [
>     //                    {
>     //                        "price": 14.6
>     //                    },
>     //                    {
>     //                        "description": "xxxxxx",
>     //                        "price": 45.2
>     //                    }
>     //                ]
>     //            },
>     //            {
>     //                "jobCategory": "3",
>     //                "jobDescriptions": [
>     //                    {
>     //                        "price": 100
>     //                    },
>     //                    {
>     //                        "description": "zzzzzzz",
>     //                        "price": 250.5
>     //                    }
>     //                ]
>     //            }
>     //        ]
>     //    }
>     //},
>     onSubmit: function(errors, values){
>         alert('Values object:\n' + JSON.stringify(values, null, 2));
>         console.log(values);
>     }
> };
>
> jQuery(function ($) {
>
>     var formObj = $("#custom_form form");
>     formObj.jsonForm(formSchema);
>
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshfire/jsonform/issues/144>.
>



-- 
Ulion

**Comment by learner291** [comment]
@Etheriq Did you manage to implement this as I need to do 2 level selection chain as well? If user selects a value from a drop down, I need to display list of check boxes which depends on the value that user selects from the drop down. If user selects option A, I may need to get data from the server via ajax and display 10 check boxes, if user selects option B, I may need to get data from the server again and display may be 15 different check boxes.

@ulion Do you have any example code on how to do this in jquery as I using Angular is not an option for us at this stage?
