### ISSUE TITLE
Are there any drawbacks to tightly coupling the json-schema to the view?

### ISSUE THREAD

**Issue by mkmoisen** [jsonform/jsonform#145]
I wrote a detailed [question on stackoverflow](http://stackoverflow.com/questions/31777279/adding-properties-to-fields-in-a-json-schema-to-tightly-couple-the-schema-with-a) if anyone could answer, but I'll ask the concise version here:

I would love to leverage something like jsonform so that my UI team could generate a UI form based off the json-schema I provide them. This would cut down tremendously on the hours spent in meetings describing business requirements or how the UI needs to flow. However, this appears to me to tightly couples the backend to the UI. Is there any drawback to this approach or concerns I should look out for?

Best regards!

(I am cross posting this in the 3 jsonform's I see on github for some more visibility)

**Comment by tchapi** [comment]
_I'm closing this issue since it is probably outdated — Please reopen if you still need help on this. Thanks_
