### ISSUE TITLE
Condition based UI

### ISSUE THREAD

**Issue by basvandenheuvel** [jsonform/jsonform#148]
Is it possible to have conditions? Like.. when a checkbox is checked show an extra textfield. Something like:

remark: {
   type = 'string',
   show = 'CHECKBOX.VALUE'
}

**Comment by ulion** [comment]
try use toggleNext

sample from my patched fork:
http://ulion.github.io/jsonform/playground/?example=fields-checkbox

2015-09-17 20:12 GMT+08:00 Bas van den Heuvel <notifications@github.com>:

> Is it possible to have conditions? Like.. when a checkbox is checked show
> an extra textfield. Something like:
>
> remark: {
> type = 'string',
> hidden = 'CHECKBOX.VALUE'
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshfire/jsonform/issues/148>.
>



-- 
Ulion

**Comment by tchapi** [comment]
_I'm closing this issue since it is probably outdated — Please reopen if you still need help on this. Thanks_
