### ISSUE TITLE
update values

### ISSUE THREAD

**Issue by mjau-mjau** [jsonform/jsonform#152]
Hi. I am trying to update some values of the jsonform _after_ its created, but it seems this is not really possible. One can of course target each form field in the DOM, but that is a tedious process if you have new settings in a json object. Is the only option to remove the json form element from DOM, and re-create it?

Or am I missing something?

**Comment by ulion** [comment]
Yes, maybe you want try angular-schema-form, which may partly support
dynamic adjust form schema.

2015-10-23 23:25 GMT+08:00 Karl Ward <notifications@github.com>:

> Hi. I am trying to update some values of the jsonform *after* its
> created, but it seems this is not really possible. One can of course target
> each form field, but that is a tedious process if you have new settings in
> a json object. Is the only option to remove the json form element from DOM,
> and re-create it?
>
> Or am I missing something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshfire/jsonform/issues/152>.
>



-- 
Ulion

**Comment by tchapi** [comment]
_I'm closing this issue since it is probably outdated — Please reopen if you still need help on this. Thanks_
