### ISSUE TITLE
adding tags for the repo

### ISSUE THREAD

**Issue by Amomo** [jsonform/jsonform#153]
Hello,

Adding tags for repo could specify points in history and mark release points.
It's helpful for user to know the version and status of repository, and would enable wider distribution of the library, for example it could be hosted by [cdnjs](https://github.com/cdnjs/cdnjs) ([website](https://cdnjs.com/))

Would you please consider on using tags?
Thanks for your great work!

**Comment by howardroark** [comment]
+1 ... Would you also be willing to add a `bower.json` file and register it with bower?  Once you do that it will automatically pick up each release you tag.  Easy peasy!

**Comment by tchapi** [comment]
Hello and thanks for this issue (_and the latency of this message ..._)
I'll try to have a look — in the meantime we're looking forward to revive this project so that it can progress and be useful to the community. See https://github.com/joshfire/jsonform/issues/177 if you are interested ;)

**Comment by tchapi** [comment]
Tags added now, for bower, see the relevant issue
