### ISSUE TITLE
JSON schema from file or html

### ISSUE THREAD

**Issue by leanno91** [jsonform/jsonform#156]
Hi 

I would like to import a json schema from a file of an html tag, is that possible? I did not find any documentation about that.

Thanks!

**Comment by tchapi** [comment]
You can easily do that directly with jQuery — this is out of the scope of the library. Something like this could work (HTML tag, in the data-schema attribute) :

    var schema = JSON.parse($('div.schema').data('schema'))
    $('form').jsonForm(schema)

**Comment by samaasamy** [comment]
> You can easily do that directly with jQuery — this is out of the scope of the library. Something like this could work (HTML tag, in the data-schema attribute) :
> 
> ```
> var schema = JSON.parse($('div.schema').data('schema'))
> $('form').jsonForm(schema)
> ```

I didn't understand your explanation.. What is  (HTML tag, in the data-schema attribute) ? Could you please elaborate, if possible? 
Thank you in advance!

**Comment by samaasamy** [comment]
> You can easily do that directly with jQuery — this is out of the scope of the library. Something like this could work (HTML tag, in the data-schema attribute) :
> 
> ```
> var schema = JSON.parse($('div.schema').data('schema'))
> $('form').jsonForm(schema)
> ```

Could you please elaborate with an example? thanks in advance!

**Comment by tchapi** [comment]
Please create a specific jsfiddle for your case — with all the modifications — so I can see the error happening. It's hard to debug pseudo-code
