### ISSUE TITLE
underscore v>1.6.0

### ISSUE THREAD

**Issue by rogerburton** [jsonform/jsonform#159]
Hello,
with underscore > 1.6.0:
TypeError: Cannot read property 'ownerDocument' of null

Great job ! thanks.
Roger Burton

**Comment by nop1984** [comment]
++, same problem. Looks like jsonform is quit (5 years no updates)

**Comment by tchapi** [comment]
`master` has been updated to work with underscore 1.8.3. Let us know if there are issues.
