### ISSUE TITLE
Angular 2.0 Integration

### ISSUE THREAD

**Issue by anupamarachuri** [jsonform/jsonform#160]
Could you please provide a way to integrate with Angular 2.0. Basically our requirement is to include the dynamic form only for few pages and static for few. Could you please let us know how we can leverage this using the jsonform

**Comment by kchetan92** [comment]
Checkout angular schema https://github.com/json-schema-form/angular-schema-form

**Comment by tchapi** [comment]
https://github.com/json-schema-form/angular-schema-form is effectively the best solution for this
