### ISSUE TITLE
Installing the  project via npm does not work

### ISSUE THREAD

**Issue by nourdine** [jsonform/jsonform#167]
Upon running `npm install json-form --save` the module is installed but it only contains a basic package.json with no dependencies and zero source code. Can this be fixed so that your project can be used as a dependency?

**Comment by tchapi** [comment]
Unfortunately this is not the package you're looking for. So far it is not available on package repositories.

Follow https://github.com/jsonform/jsonform/issues/117 for Bower for instance or https://github.com/jsonform/jsonform/issues/153
