### ISSUE TITLE
How can I implement a responsive multicolumn form?

### ISSUE THREAD

**Issue by proms2018** [jsonform/jsonform#169]
How can I implement a responsive multicolumn form?

With enough horizontal space (width) the controls should appear in 3 columns, when horizontal space is reduced fields are shrinked and at some width goes to 1 column.

Thanks

![image](https://user-images.githubusercontent.com/6732577/37182377-94953e8a-22f6-11e8-9460-1d572fe6a5f7.png)

![image](https://user-images.githubusercontent.com/6732577/37182392-b22b367a-22f6-11e8-81cd-1d965c184e76.png)

**Comment by tchapi** [comment]
This is a purely CSS question and not really related to jsonform, Bootstrap 3 should be able to do this automatically, or you could change the template used for the fields if you find it easier.

Making `.form-group` display as inline blocks or floats could be a start, or use flexbox if you can.

**Comment by proms2018** [comment]
Ok. I finally found out how to do it:

1. Create the fields
2. In "form" create "section" to group them
3. After create the form, add bootstrap classes: "row" to the sections and "col-sm" to the ".form-group".

`$('form').jsonForm({

            schema: {
                "name": {
                    "id"   : "Nombre",
                    "title": "Nombre",
                    "type" : "string"
                },

                "apPat": {
                    "title": "Apellido Paterno",
                    "type": "string"
                },
                "apMat": {
                    "title": "Apellido Materno",
                    "type": "string"
                },
                "gender": {
                    "title": "Género",
                    "type": "string",
                    "enum": [
                        "Masculino",
                        "Femenino",
                        "Alien"
                    ]
                }
            },

            form: [
                {
                    type : "section",
                    id   : "DatosNom",
                    title: "Nombre",
                    items: [
                        "name",
                        "apPat",
                        "apMat"
                    ]
                },

                {
                    type : "section",
                    id   : "DatosNom2",
                    title: "Nombre2",
                    items: [
                        "name",
                        "apPat",
                        "apMat"
                    ]
                },

                "gender",
                {
                    type: "submit",
                    title: "¡Crear tu cuenta!"
                }
            ],

            onSubmit: function (errors, values) {
                if (errors) {
                    $('#res').html('<p>I beg your pardon?</p>');
                }
                else {
                    $('#res').html('<p>Hello ' + values.name + '.' +
                        (values.age ? '<br/>You are ' + values.age + '.' : '') +
                        '</p>');
                }
            }
        });`

And after that the magic words are:
`       $("#DatosNom").addClass("row");`
`        $("#DatosNom2").addClass("row");`
`        $(".form-group").addClass("col-sm");`

And the result:

![image](https://user-images.githubusercontent.com/6732577/42917236-5314618a-8ace-11e8-9558-5f5485db9c3b.png)

When window changes its width:

![image](https://user-images.githubusercontent.com/6732577/42917265-70b9cca2-8ace-11e8-85fb-5fb9c083d1a5.png)

I think that there should be a special group like "rowsection" or something like that to avoid the "addClass" but, for now, it will do it.

**Comment by proms2018** [comment]
For fast use:

Edit jsonform.js
Go to line 1319, it must be:

![image](https://user-images.githubusercontent.com/6732577/42917942-4b7c696a-8ad1-11e8-83d1-81717ccde0ed.png)

Add a class to the template, let's say: jsonform-section:

![image](https://user-images.githubusercontent.com/6732577/42918025-a6832f88-8ad1-11e8-8733-9ae1c0062d40.png)

In our code now we can do:

`$(".jsonform-section").addClass("row");`
`$(".form-group").addClass("col-sm");`

**Comment by tchapi** [comment]
Glad that you made it work, and thanks for sharing a solution

**Comment by joelguittet** [comment]
Hello,

Interesting subject I was really looking about. I assume since this issue has been closed it is now also possible to use the "htmlClass" value. It is the same feature than the solution proposed by @proms2018 .

Current code in the lib: (v2.2.2)
```
'section': {
    'template': '<div' +
      '<% if (elt.htmlClass) { %> class="<%= elt.htmlClass %>"<% } %>' +
      '<% if (node.id) { %> id="<%= node.id %>"<% } %>' +
      '><%= children %></div>'
  },
```

Hope this will help other looking to this subject.

Joel
