### ISSUE TITLE
Extending JsonForm with new fields

### ISSUE THREAD

**Issue by raizam** [jsonform/jsonform#17]
Hi,

first of all, you've done a great job on this useful project.

I've played with the playground project, and looked at the source.
I noticed the field type 'file' is rendered in the generated form.

however reading the source, It seems file upload handling was commented out on submit.
since the 'file' type is not available in the documentation, I guess the feature was dropped.

I need to add this feature, and eventually contribute to the project.
Any instruction on adding new field types?

Thank you

**Comment by norama** [comment]
Hi, what is the status of this? I would also need file upload feature, just realized that the "type": "file" does not even return the file path in the values map.  I have no experience with Transloadit and it seems to be non-free. So I would prefer the jQuery File Upload implementation.

**Comment by NerdsvilleCEO** [comment]
+1 I really need this, is there an easy way to override a field?

**Comment by ctaity** [comment]
Some news?

**Comment by tchapi** [comment]
Hi guys. I see this issue is quite old but it seems that there is still a need for it. I'll try to have a look in the coming weeks, any suggestions on how to do it are welcome !

**Comment by collimarco** [comment]
Has anyone found a solution?

Maybe the file input could be read as a base64 and stored in the JSON

**Comment by tchapi** [comment]
Is that what you are looking for, for instance: https://github.com/jsonform/jsonform/pull/379/files#diff-8b2e26b4e9c233be876073b1eb7ced4836edc952ec18c08b0b82e47d1afe7d95 ?
