### ISSUE TITLE
Maintainers and going forward

### ISSUE THREAD

**Issue by tchapi** [jsonform/jsonform#177]
Hello all

This project has been stale for a while (_due to us not putting much work in it since we didn't use it for the last couple of years_) — we deeply apologize for that. But it still has a lot of traction and would really benefit from the work of all the people that helped build it and all the fantastic forks that exist today.

We are actively considering creating an independent organisation to hold this repo (_and possibly all the plugins / related code_), so that everyone can get involved, correct, enhance, triage issues, test, etc ... From there, we can pick a few members to publish packages for instance, to smooth the process and speed things up.

**Let us know what you think** in the comments of this issue below, or via mail at `cyril@joshfire.com`, we're happy to discuss so the project can really be useful and progress as it should.

Thanks
Best !
Cyril @ Joshfire

**Comment by tchapi** [comment]
Here we are now : https://github.com/jsonform/jsonform

**Comment by tchapi** [comment]
:tumbleweed:

**Comment by goldingdamien** [comment]
Is there an npm module? I want to use this with all the dependencies loaded. If necessary, I will contribute to make it.

**Comment by tchapi** [comment]
Hi @goldingdamien 
It is published on npm : https://www.npmjs.com/package/jsonform
But the dependencies are a bit of a mess at the moment... they are directly in the `deps/` folder. If you want to improve that, it would be great !

Best

**Comment by goldingdamien** [comment]
@tchapi Hi, I can make a function to load dependencies such as below. I am not familiar with the source of the project, Please let me know how it should be added. Also please let me know what environments it should support as I usually use es2015 code and I do not see any build process in this project.

```
//Each dependency listed here: https://github.com/jsonform/jsonform/blob/master/README.md#dependencies
const settings = {
  ace: /opt/ace/ace/js,
  ...
}

function load(keys=[]){
  const toLoad = []
  keys.forEach((key)=>{toLoad.push(settings[key])})
  return loadUrls(toLoad)
}
```

**Comment by tchapi** [comment]
There is no build process _yet_, so everything has to be created.

The only *required* dependencies are jQuery and Underscore. The other libraries depend on the features wanted, so they should not be explicitly required.

I myself do not know exactly how to tackle this, so any suggestions are welcome TBH.

**Comment by goldingdamien** [comment]
I am not familiar with how jquery extensions are applied to npm packages, but general npm packages would result in something like "const jsonForm = require('json-form')" and then I guess a selector function to get the form element and then an execute function. I will try and create a demonstration soon as I am quite in need of such functionality for a couple of projects I am working on.

**Comment by goldingdamien** [comment]
I created a demo Github repository.
Something like this would need to wrap the JSON Form library to prevent dependencies not loaded errors.
The demo doesn't take into consideration more detailed circumstances such as JQuery already being loaded in the page.

Please take a look:
https://github.com/goldingdamien/jsonform-loader

**Comment by tchapi** [comment]
Thanks @goldingdamien and sorry for the late response as I am quite busy atm on various projects. I will try to take some time in the near future to review what you propose. Do you think it would be worth it to create this loader repo directly in the jsonform organization, of which you can become a contributor, so that it's more consistent ?

**Comment by goldingdamien** [comment]
@tchapi Yes that is fine. Please let me know of your opinion when you have the time.
