### ISSUE TITLE
Event Handlers are not triggering on previousvalues 

### ISSUE THREAD

**Issue by kmondedd** [jsonform/jsonform#178]
Hay 
In `customFormItems` i have `onChange` event, based on radio value I am adding/removing classes to other elements. 

Its not working on previous values, I mean its not triggering onChange event after value set from value like this https://github.com/jsonform/jsonform/blob/master/docs/examples/previousvalues.json

**Comment by tchapi** [comment]
Can you show the content of your schema / form ?

**Comment by sdetweil** [comment]
is this a big?  the onChange is set after the values are loaded.
