### ISSUE TITLE
Better version handling

### ISSUE THREAD

**Issue by ymeiner** [jsonform/jsonform#179]
there was just a major update to this tool that caused some things to break on my side, Please handle versions better so we can control updates.

Thanks!

**Comment by tchapi** [comment]
Hi @ymeiner

We started using semantic versioning a few days ago only. There was no releases before that, so I guess we could say that we now handle versions better; the package will likely be available on npm in the coming month, too (_somebody actually squats the name right now_).

This being said, the legacy version (_that has been sitting in this repo for a while_) is now tagged 1.0  (https://github.com/jsonform/jsonform/releases/tag/v1.0).  I guess this is what you were using but you were on the `HEAD` of master and not locked to one specific commit, which might have broken things on your side.

The current 2.0 release has seen some BC-breaks (_notably, the drop of Bootstrap 2, that is long overdue_) if you want to give it a try.

**Comment by ymeiner** [comment]
Thanks, i'll check it out.

**Comment by ymeiner** [comment]
We ended up locking to 1 until we upgrade to 2 thanks!

**Comment by tchapi** [comment]
No problem
