### ISSUE TITLE
Update of the "legend" of tabarray before/after deletion of an item

### ISSUE THREAD

**Issue by pbuleon** [jsonform/jsonform#180]
Hi,

Here is the schema/form used :
```
{
  "schema": {
		"servers": {
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "object",
				"title": "server",
				"properties": {
					"address": {
						"type": "string",
						"title": "Address",
						"required": true
					}
				}
			}
		}
	},
	"form": [
		{
			"type": "fieldset",
			"title": "Servers Configuration",
			"items": [
				{
					"type": "tabarray",
					"key": "servers",
					"items": {
						"type": "fieldset",
						"legend": "Server  {{value}}",
						"items": [
							{
								"key": "servers[].address",
								"valueInLegend": true
							}
						]
					}
				}
			]
		}
	]
}
```

If I create 3 servers, (ex "1.1.1.1" "2.2.2.2" "3.3.3.3") i have the nav-tab (on left), with the good labels :
 "Server 1.1.1.1"
 "Server 2.2.2.2"
 "Server 3.3.3.3"
 
In the <legend> of the fieldsets, the value is still "Server" (and not "Server x.x.x.x")

If I remove the Server "2.2.2.2", the nav-tab is still ok :
 "Server 1.1.1.1"
 "Server 3.3.3.3"
 
 But the <legend>  of the fieldset of the "Server 3.3.3.3" becomes "SERVER 3.3.3.3", and for the Server 1.1.1.1, the legend is still "Sever"
 
 It is because after the delete of a server, only the fieldsets with a rank > (deleted rank) is refreshed
 
 A possible solution is to update the legend of the fieldset, when the nav-tab is updated. 
 
 BR
 
 p.

**Comment by tchapi** [comment]
You were right, I just fixed it; If you could test it and tell me if it's ok

**Comment by pbuleon** [comment]
Thanks

i'll test it soon!

**Comment by pbuleon** [comment]
It seems ok fro me!

Thanks
