### ISSUE TITLE
Using dictionary in enum

### ISSUE THREAD

**Issue by Macodom** [jsonform/jsonform#184]
Hi, I love this library, I'm having a problem since I didn't found an example on documentation.
I want to use a dictionary in the enum list. So I want to store the index value. I'm using update value schema and added the dictionary to be easier to replicate. The key value is gender that has the dict.

I have problems with this because when I use the jsonform all the answers that I get are converted to string, so instead of getting value 0, I get the string of "Male"
Is there a way to get this the way I want it?
Thanks in advance.

```
{
   "schema":{
      "friends":{
         "type":"array",
         "items":{
            "type":"object",
            "title":"Friend",
            "properties":{
               "nick":{
                  "type":"string",
                  "title":"Nickname",
                  "required":true
               },
               "gender":{
                  "type":"string",
                  "enum":{
                     "0":"Male",
                     "1":"Female",
                     "2":"Alien"
                  }
               },
               "age":{
                  "type":"integer",
                  "title":"Age"
               }
            }
         }
      }
   },
   "value":{
      "friends":[
         {
            "nick":"tidoust",
            "gender":1,
            "age":34
         },
         {
            "nick":"titine",
            "gender":"2",
            "age":6
         },
         {
            "nick":"E.T.",
            "gender":"alien"
         }
      ]
   }
}
```

**Comment by tchapi** [comment]
Hi,

I'm afraid this is not possible at the moment. If you want to submit a PR, feel free :)

**Comment by MISurg** [comment]
<script type="text/javascript"> $(
   'form'   ).jsonForm(   {
      schema:{
         "gender":{
            "type":"string",
            "title":"Gender",
            "enum":[
               1,
               0
            ]
         }
      },
      "form":[
         {
            "key":"gender",
            "titleMap":{
               1:"Yes",
               0:"No",

            }
         }
      ]
   }
);
