### ISSUE TITLE
How do I create a form using prefill checkbox values?

### ISSUE THREAD

**Issue by simkeyur** [jsonform/jsonform#187]
I am trying to prefill some checkboxes while creating a form. here is how my schema looks right now:

{
  "schema": {
    "menu": {
      "type": "array",
      "title": "Options",
      "items": {
        "type": "string",
        "title": "Option",
        "enum": [
          "starter",
          "maincourse",
          "cheese",
          "dessert"
        ]
      }
    }
  },
  "form": [
    {
      "key": "menu",
      "type": "checkboxes"
    }
  ],
  "value": {
    "menu": "starter"
  }
}

Code:
`{
  "schema": {
    "menu": {
      "type": "array",
      "title": "Options",
      "items": {
        "type": "string",
        "title": "Option",
        "enum": [
          "starter",
          "maincourse",
          "cheese",
          "dessert"
        ]
      }
    }
  },
  "form": [
    {
      "key": "menu",
      "type": "checkboxes"
    }
  ],
  "value": {
    "menu": "starter"
  }
}`

Thanks

**Comment by simkeyur** [comment]
Infact just found a solution. 

{
  "schema": {
    "menu": {
      "type": "array",
      "title": "Options",
      "items": {
        "type": "string",
        "title": "Option",
        "enum": [
          "starter",
          "maincourse",
          "cheese",
          "dessert"
        ]
      }
    }
  },
  "form": [
    {
      "key": "menu",
      "type": "checkboxes"
    },
    {
      "type": "submit",
      "title": "Submit"
    }
  ],
  "value": {
    "menu": ["starter", "maincourse"]
  }
}

Code:
`{
  "schema": {
    "menu": {
      "type": "array",
      "title": "Options",
      "items": {
        "type": "string",
        "title": "Option",
        "enum": [
          "starter",
          "maincourse",
          "cheese",
          "dessert"
        ]
      }
    }
  },
  "form": [
    {
      "key": "menu",
      "type": "checkboxes"
    },
    {
      "type": "submit",
      "title": "Submit"
    }
  ],
  "value": {
    "menu": ["starter", "maincourse"]
  }
}`

**Comment by tchapi** [comment]
Perfect, thanks for sharing !
