### ISSUE TITLE
Use htmlClass on Section

### ISSUE THREAD

**Issue by beedjees** [jsonform/jsonform#190]
### Expected behavior
Generate "div" section with specific class name, like this :
```html
<div class="col-sm-6">...</div>
```

### Actual behavior
```html
<div>...</div>
```

### Steps to reproduce the behavior

```javascript
"form": [{
    "type": "section",
    "htmlClass": "col-sm-6",
    "items": [ ... ]
}]
```

**Comment by tchapi** [comment]
Hi,

It is currently not possible with a `section` type. You can use a `fieldset`, that would work.

If you think this should be possible for sections too, I'm happy to accept a PR as I'm short on time atm (_I guess the modifications should be around https://github.com/jsonform/jsonform/blob/master/lib/jsonform.js#L1318_)

Best

**Comment by tchapi** [comment]
Better late than never 🎉
