### ISSUE TITLE
Unable to load Form "onChange" in form

### ISSUE THREAD

**Issue by wiless** [jsonform/jsonform#193]
Trying to modify the example.html with schema given in [`events.json`](https://github.com/jsonform/jsonform/blob/master/playground/examples/events.json) from examples. The example does not load when "onChange" or "onClick" event is included in the **JSON Form object**

```
{
  "schema": {
    "text": {
      "type": "string",
      "title": "Text"
    }
  },
  "form": [
    {
      "key": "text",
      "onChange": function (evt) {
        var value = $(evt.target).val();
        if (value) alert(value);
      }
    },
    {
      "type": "button",
      "title": "Click me",
      "onClick": function (evt) {
        evt.preventDefault();
        alert('Thank you!');        
      }
    }
  ]
}
```

**Comment by tchapi** [comment]
Hi
This example works as expected (https://jsonform.github.io/jsonform/playground/index.html?example=events) - can you provide us with a non-working example ?

**Comment by wiless** [comment]
Here is the way I am using it..
I load the "events.json" through  $.getJSON() - I see that the getJSON fails to parse the "events.json" when it has "onchange" assigned to javascript function. If I create the JSON object inline (in the index.html) it works perfectly fine !!
https://gist.github.com/wiless/88a37d9f6d156ccb911582a8c82cb564

**Comment by wiless** [comment]
> Here is the way I am using it..
> I load the "events.json" through $.getJSON() - I see that the getJSON fails to parse the "events.json" when it has "onchange" assigned to javascript function. If I create the JSON object inline (in the index.html) it works perfectly fine !!
> https://gist.github.com/wiless/88a37d9f6d156ccb911582a8c82cb564

Found workaround to `overload` JSON.parse by this approach 
```
$.get({ url: "events.json", dataType: "text" })
	.done(function (data) {
		alert("Data Loaded: " + data);
		jschema = JSON.parse(data, function (key, value) {
			if (typeof value === "string" && value.startsWith("function") && value.endsWith("}")) {
				value = eval("(" + value + ")");
				return value;
			}
			return value;
		}); 
		myproperties = jschema.schema;
		formlayout = jschema.form;
		loadform();
	});
```
for this `event.json` schema

```
{
  "schema": {
    "Name": {
      "type": "string",
      "title": "Enter some text"
    }
  },
  "form": [
    {
      "key": "Name",
      "onChange": "function(evt) { var xx = $(evt.target).val();         if (xx) alert(xx); }"
    },
    {
      "type": "button",
      "title": "Click me"
    }
  ]
}
```

**Comment by tchapi** [comment]
Thanks for sharing this !
