### ISSUE TITLE
How do I create a form using prefill date values?

### ISSUE THREAD

**Issue by TimRowe** [jsonform/jsonform#195]
```js
$('form').jsonForm({
			schema: {
				birthday: {
				    type: 'date',
					title: 'Birthday',
					required: true
				},
				age: {
					type: 'number',
					title: 'Age'
				}
			},
			value: {
			    birthday: "2018-9-20",
			    age: 20
			}
		});
```

Date value does't init ? 

Another problem ： How to init properties value?

**Comment by tchapi** [comment]
Hello

You need to open your console and read the warning in it : 

`jquery.min.js:4339 The specified value "2018-9-20" does not conform to the required format, "yyyy-MM-dd".`

So just put a correct value for the date and it will work.

**Comment by TimRowe** [comment]
@tchapi Another problem ： How to init properties value?

**Comment by tchapi** [comment]
I don't understand your question. Please provide an example of what you are trying to achieve
