### ISSUE TITLE
Incorrect validation of number fields

### ISSUE THREAD

**Issue by duffar12** [jsonform/jsonform#197]
Number fields are not allowing me to enter floating point numbers. They only allow integer values.
When I try to enter a floating point number and press submit I get a pop up saying 
"please enter a valid value. The two nearest valid values are x.0 and y.0"

The funny thing is that if I set the default value to a floating point number. Say 0.7, then the only values allowed are floating point numbers with a 0.7 offset are allowed. For example the only valid values in this case would be 0.7, 1.7, 2.7, 3.7 etc. Everything else including integers is forbidden

I can get around this problem by using the range type, which is rendered as a slider bar. However, I do not want a slider bar and would prefer not to use a string type

**Comment by tchapi** [comment]
This limitation boils down to the fact that the `step` attribute is not taken into account when using a `number` field, and that it defaults to **1** for number type fields, thus only allowing integers or deviations of 1 related to the initial value.

This would need to take the step (and possibly min and max) attributes into account in the code [here](https://github.com/jsonform/jsonform/blob/master/lib/jsonform.js#L269). I could give it a try but not sure it'll be very quick though; Happy to review a PR about it

**Comment by coreyfournier** [comment]
The fix is simple. Open up jsonform.js and on line "var inputFieldTemplate = function (type)" (239) add

'<%= (node.schemaElement.step > 0 ? " step=\'" + node.schemaElement.step + "\'" : "")%>' +

Once this is done, you can add a step property to the schema like below:

"field2": {
			"type": "number",
			"title": "A Number Field",
			"step": 0.01
		}

This will allow any number to end in two decimal places and will be in increments of .01

**Comment by tchapi** [comment]
Hi @coreyfournier - would you make a PR out of your solution with a proper example file so that I can include it in the code ? I think that would be great

**Comment by coreyfournier** [comment]
@tchapi, I edited the file and created a pull request. This is my first PR, so keep that in mind.

**Comment by tchapi** [comment]
Closed in https://github.com/jsonform/jsonform/pull/215
