### ISSUE TITLE
Support for tooltips

### ISSUE THREAD

**Issue by duffar12** [jsonform/jsonform#198]
Could we add support for tooltips? I would like to be able to display a tooltip when my form boxes are hovered over? 
Perhaps a form field similar to htmlClass could be added for a title.  For example htmlTitle

**Comment by tchapi** [comment]
Thanks for your idea — I'm not sure we should add a field specifically for tooltip, but having a "metadata" field could be of use I guess. Happy to accept a PR if you have the time to give it a try !

**Comment by duffar12** [comment]
Ok, I've submitted a pull request.  I'm only learning javascript, so please bear with me if I have done something unconventional. I've tested my changes and they seem to work nicely though. So fingers crossed it's good to go

**Comment by tchapi** [comment]
I've seen it, thanks a lot for that. Will merge sometime soon

**Comment by tchapi** [comment]
This is fixed in https://github.com/jsonform/jsonform/pull/199
