### ISSUE TITLE
Small helper tool that takes a JSON object and generates a skeleton of the corresponding JSON Form object

### ISSUE THREAD

**Issue by tidoust** [jsonform/jsonform#20]
To speed up the authoring of a JSON Form object, it would be good to be able to start from an example of a JSON structure that the form is to generate and automatically create a basic JSON Form object that would generate that structure.

For instance, given:

``` json
{
  "name": {
    "firstname": "Francois",
    "lastname": "Daoust"
  },
  "adult": true
}
```

... that small tool could generate:

``` json
{
  "schema": {
    "name": {
      "type": "object",
      "properties": {
        "firstname": {
          "type": "string",
          "title": "name.firstname"
        },
        {
          "lastname": {
            "type": "string",
            "title": "name.lastname"
        }
      }
    },
    "adult": {
      "type": "boolean",
      "title": "adult"
    } 
  },
  "form": [
    {
      "type": "fieldset",
      "items": [
        "name.firstname",
        "name.lastname" 
      ]
    },
    "adult"
  ]
}
```

Such a tool is just a beginning, obviously. It cannot detect additional constraints on data and cannot produce meaningful fields titles and form structure, but it would give a very easy way to produce a JSON Form object.

See suggestion by moriation on dev-joshfire mailing-list:
https://groups.google.com/d/topic/joshfire-dev/-CfYn73ZtmM/discussion

**Comment by tchapi** [comment]
http://www.jsonschema.net/ does the job, closing for now.
