### ISSUE TITLE
higher JSON Schema drafts  than 03 throws exceptions

### ISSUE THREAD

**Issue by fontanka16** [jsonform/jsonform#200]
It seems to me that this library does not support JSON Schema versions higher than draft-03. Would it be a big chanllenge to raise the version so that the lib is on par with current schema drafts?

**Comment by tchapi** [comment]
Hi
If you can point me to a doc listing the differences / novelties in the latest draft, I can surely have a look. An example of failing schema could be useful too so I can see what is the culprit.

Thanks

**Comment by fontanka16** [comment]
I usually go to https://www.jsonschema.net/ and put in some json in order to get a schema. The default version that comes out is draft-07. So far i have managed by just changing the version in the header, but I do not use too many new features.

Release notes from draft 06 and 07:
https://json-schema.org/draft-07/json-schema-release-notes.html
https://json-schema.org/draft-06/json-schema-release-notes.html

**Comment by stevemart** [comment]
+1 to this request. One of the more popular python implementations for jsonschema validation is https://github.com/Julian/jsonschema and it supports v3, v4, v6, and v7.

**Comment by Sathish-at-AutoGrid** [comment]
Any update on this?

**Comment by tchapi** [comment]
Hi
I haven't had any time in the past year to work on this issue. It's not as straightforward as it may seem and I have focused my efforts on bug fixing and merging small useful PRs from the (few) contributors that provided them.

Also, see https://github.com/jsonform/jsonform/issues/177#issue-329531863 — it would be a good thing to have other contributors 🤗 

I'll reopen this for now, if ever I find some time in the near future
Thanks
