### ISSUE TITLE
Attributes in form

### ISSUE THREAD

**Issue by mlabarre** [jsonform/jsonform#203]
Hello
I discovered jsonform today. It's great but I have a little problem.
I have the very simple example declaration
```
{
   schema: {
          "obj": {
                 type: "object",
                 properties: {
                        "firstname": {
                               type: "string"
                        },
                        "lastname": {
                               type: "string"
                        },
                 }
          }
   },
   form: {
          ???
   }
}
```
How can I specify a placeholder attribute on field 'firstname' of this object in the form (view) part?
All my tests are bad.
In fact, my question is more complexe. 
The problem is that only the fields in 'form' will be submitted. To indicate an attribute, you must indicate the field in 'form'. So only this one will be submitted! Then, I must indicate all fields in 'form' even if i set only one field attribute. Exact?
Many thanks

**Comment by tchapi** [comment]
For the placeholder, have a look at this example : https://jsonform.github.io/jsonform/playground/index.html?example=fields-common
