### ISSUE TITLE
Upload File Option Value retrieval?

### ISSUE THREAD

**Issue by simkeyur** [jsonform/jsonform#205]
How do I retrieve value of uploaded file via jsonform?

Here is my code:
`{
 "schema": {
    "file": {
      "title": "Upload File",
      "description": "Nickname allowed",
      "type": "file"
    }
  }
}`

**Comment by tchapi** [comment]
On the server side you mean ?

**Comment by simkeyur** [comment]
Just in jquery file? Or if there is server side, I am good too. Just want to handle FileUpload with this library

**Comment by tchapi** [comment]
use FileReader if you use jQuery only, for instance.

**Comment by VaibhavFortress** [comment]
@simkeyur  have you got the solution?
@tchapi  i didn't get you. where i can use FileReader?

**Comment by tchapi** [comment]
Hi @VaibhavFortress 
The uploading process _per se_ is out of the scope of **jsonform**, so you can use https://developer.mozilla.org/en-US/docs/Web/API/FileReader for instance if you want to process the file client-side, or any stack you like if you want to do it server-side
