### ISSUE TITLE
Get values at any time(not on submit)?

### ISSUE THREAD

**Issue by goldingdamien** [jsonform/jsonform#207]
How can I get the values usually retrieved on submit before submitting using a function?

**Comment by tchapi** [comment]
Something like `form.submit()` (https://api.jquery.com/submit/) ?

**Comment by goldingdamien** [comment]
It seems like that will cause a submit action.
I just want to get the currently inputted values in a similar format to [accessing-submitted-values](https://github.com/jsonform/jsonform/wiki#accessing-submitted-values) without submitting.

**Comment by tchapi** [comment]
Not if you `return false` : the form will not be submitted then.
How about a simpler : 
```
$.each($('#your_form').serializeArray(), function(i, field) {
    console.log(field.name + " = " + field.value);
});
```

**Comment by goldingdamien** [comment]
Working well, thanks.
