### ISSUE TITLE
Compatible with Bootstrap 4?

### ISSUE THREAD

**Issue by shaunc869** [jsonform/jsonform#209]
Sorry I couldn't find this answer in the docs, it says Bootstrap 3.3. or higher, does that include Bootstrap 4? Thanks!

**Comment by mudovytskyi** [comment]
The docs are automatically generated (Read.Me) by create-react-app library on the initial stage. I didn't tie this project with Bootsrap. I use styled-components as alternative. But it doesn't make a big issue to link this project with Bootstrap4 via (e.g.) [reactstrap](https://reactstrap.github.io/).

**Comment by onyxg** [comment]
+1

**Comment by michaelmairegger** [comment]
@shaunc869 I have the same issue. For this I forked the repository and edited some few parts of the code so that bootstrap 4 looks better. You can see my progress within my fork: https://github.com/michaelmairegger/jsonform/tree/bootstrap4

Note that I have changed the parts that I needed for my project. As my project evolves I will see some other parts that I have to change in order to look good.

**Comment by learner291** [comment]
> 
> 
> @shaunc869 I have the same issue. For this I forked the repository and edited some few parts of the code so that bootstrap 4 looks better. You can see my progress within my fork: https://github.com/michaelmairegger/jsonform/tree/bootstrap4
> 
> Note that I have changed the parts that I needed for my project. As my project evolves I will see some other parts that I have to change in order to look good.

Hi, Have you finished making this bootstrap4 compatible or are you still working?

**Comment by michaelmairegger** [comment]
@learner291 The project that I was working for that used this library was put on hold.
The project should resume in the next months, so it might be that I continue migrating

**Comment by jducobu** [comment]
> Supporting Bootstrap 3 and 4 at the same time would be complicated since a lot has changed between these two versions.
It's not possible to include template for HTMLElement ?
By it's bootstrap 3, and the user can extend to other framework !

**Comment by n0mer** [comment]
Bumping

**Comment by HeraldtenDam** [comment]
Glyphicons doesn't work anymore out of the box with BS 4, it was dropped. So for example the + and - sign don't work anymore with arrays.
