### ISSUE TITLE
Nested array initial value not populated correctly

### ISSUE THREAD

**Issue by punppis** [jsonform/jsonform#210]
Inner nested arrays are shown in the form correctly but all values are empty. **innerArray** works correctly and **innerNestedArray** does not populate any values.

schema:
`{
    "nestedArray": {
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
                "innerArray": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "a": { "type": "number" },
                            "b": { "type": "string" },
                        }
                    }
                },
                "innerNestedArray": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "a": { "type": "number" },
                                "b": { "type": "string" },
                            }
                        }
                    }
                }
            }
        }
    }
}`

value:
`{
    "nestedArray": [
        {
            "innerArray": [
                {
                    "a": 1,
                    "b": "stuff",
                }
            ],
            "innerNestedArray": [
                [
                    {
                        "a": 2,
                        "b": "other stuff",
                    }
                ]
            ]
        }
    ]
}`

**Comment by tchapi** [comment]
Your schema works in the playground : 

```
{
  "schema": {
		"nestedArray": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"innerArray": {
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"a": {
									"type": "number"
								},
								"b": {
									"type": "string"
								}
							}
						}
					},
					"innerNestedArray": {
						"type": "array",
						"items": {
							"type": "array",
							"items": {
								"type": "object",
								"properties": {
									"a": {
										"type": "number"
									},
									"b": {
										"type": "string"
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
```

I'm getting values correctly for both arrays. What exactly is the problem you're having ?

**Comment by punppis** [comment]
![image](https://user-images.githubusercontent.com/6446823/52770624-4678be80-303c-11e9-907f-97187089d356.png)

**Comment by tchapi** [comment]
Well default values work perfectly : 

```
{
  "schema": {
    "nestedArray": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "innerArray": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "a": {
                  "type": "number",
                  "default": 1
                },
                "b": {
                  "type": "string",
                  "default": "hello"
                }
              }
            }
          },
          "innerNestedArray": {
            "type": "array",
            "items": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "a": {
                    "type": "number",
                    "default": 2
                  },
                  "b": {
                    "type": "string",
                    "default": "hello again"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by punppis** [comment]
This does not help if I have a list of 100 items and would like to init the editor with initial values.

**Comment by tchapi** [comment]
Ok, I understand your point better now. I'm working on a fix and will update you asap

**Comment by tchapi** [comment]
Can you checkout this PR #212 and tell me if that fixes the behaviour for you ?

**Comment by punppis** [comment]
Seems to be working. Nice!
