### ISSUE TITLE
Any way to use form contents on enum list?

### ISSUE THREAD

**Issue by punppis** [jsonform/jsonform#211]
So I have a json structure where I would like to use value from a object inside a array as enum for string field.

    {
        "items": [
            {
                "id": "123-444",
                "stuff": "some stuff"
            },
            {
                "id": "22-124",
                "stuff": "other stuff
            }
        ],
        "otherItems": [
            {
                "selectedItem": "123-444" # i want to use enum here from items[].id
            }
        ]
    }

I could not find anything in documentation to support this. Is there easy way to achieve this by listening on events or something and manipulating the form object on the fly?

**Comment by tchapi** [comment]
When do you want to do this ? If it's on submit, you can use the `onSubmit` event and then manipulating the form like you proposed.

https://github.com/jsonform/jsonform/wiki#accessing-submitted-values

**Comment by punppis** [comment]
I want to do this in real time. So if I add a new entry in "items", it should bee available in the otherItems enums instantly.

I can already do this by manipulating schema in load time, but how can I manipulate the schema while using the form?

**Comment by VladBrok** [comment]
How do I implement this?

**Comment by oriyalperin** [comment]
Is there any implementation for this?

**Comment by sdetweil** [comment]
No.. there is no form definition way to accomplish this.   I use some javascript and jQuery with the OnChange event handler to populate a tabbed list,  live, further down in my form.  but not an enum.  I had to review the generated form html to determine what to do.

**Comment by sdetweil** [comment]
see my issue #456 , which uses the value of a select list to show secondary entry fields.. thru the onChange  event
