### ISSUE TITLE
Possibility to add custom input

### ISSUE THREAD

**Issue by michaelmairegger** [jsonform/jsonform#214]
Hi,

i want to have a form with custom additional input fields that are not present in the json.

For this i made the following form:

    <form>
          <input type="date"  />
    </form>

The field is shown but it is shown at the bottom of the form. Is it possible to add the date field at the beginning of the form? And if so, how?

Thanks for the great library

**Comment by tchapi** [comment]
hmm.. I'm not sure that this easily feasible. I guess you could add your custom input via a JS function, that would be the easiest way I guess
