### ISSUE TITLE
form layout: put input field beside label

### ISSUE THREAD

**Issue by yiufai** [jsonform/jsonform#216]
hi,

currently the input field is automatically put below the label,
example:
Name:
______________ <-- input field
 is there anyway to put the input field just right beside the label?
example:
Name: ___________________

i realize using fieldset can change the layout but i cant find a way to do this.
this is my json for "form" part
"form": [
    {
      "type": "fieldset",
      "htmlClass": "row",
      "items": [
        { "key": "name", "htmlClass": "col-sm-3" },
        { "key": "gender", "htmlClass": "col-sm-6" }
      ]
    },
    {
      "type": "fieldset",
      "htmlClass": "row",
      "items": [
        { "key": "age", "htmlClass": "col-sm-6" },
        { "key": "birthdate", "htmlClass": "col-sm-6" }
      ]
    },
    {
      "type": "fieldset",
      "htmlClass": "row",
      "items": [
        {
          "key": "pwd",
          "type": "password",
          "placeholder": "Minimum character is 8",
          "htmlClass": "col-sm-6"
        },
        {
          "key": "email",
          "type": "email",
          "placeholder": "Eg:kiwi@gmail.com",
          "htmlClass": "col-sm-6"
        }
      ]
    },
    {
      "type": "submit",
      "title": "submit"
    }
  ]
thanks in advance for your reply!!

regards, 
yiufai

**Comment by tchapi** [comment]
This is related to Bootstrap — check horizontal forms in Bootstrap : https://getbootstrap.com/docs/3.4/css/#forms-horizontal

**Comment by yiufai** [comment]
hi, actually i have tried with both form-horizontal and form-inline but it just dont work... could u please help?

**Comment by tomitesh** [comment]
> hi, actually i have tried with both form-horizontal and form-inline but it just dont work... could u please help?

did you find solution? i am facing the same issue.
