### ISSUE TITLE
how do I define a datalist for an input field?

### ISSUE THREAD

**Issue by alhuber1502** [jsonform/jsonform#217]
Is there a standard way of creating something like this in JSONForm?
```
<input list="browsers">

<datalist id="browsers">
  <option value="Internet Explorer">
  <option value="Firefox">
  <option value="Chrome">
  <option value="Opera">
  <option value="Safari">
</datalist>
```

**Comment by tchapi** [comment]
Hi
Datalists are not implemented yet. Their support is still quite partial and buggy (https://caniuse.com/#feat=datalist) so I don't think it's important to implement as of now.

If you find some time and want to contribute, feel free ! ;)

Thanks
