### ISSUE TITLE
using jsonform to generate a table

### ISSUE THREAD

**Issue by yiufai** [jsonform/jsonform#218]
hi,

is it possible to generate a table layout as below?
example:
![1](https://user-images.githubusercontent.com/43767886/53788258-3c235380-3f5c-11e9-8b10-04e7e19fee7c.PNG)

i was trying to make it using array jsonform method but it just not quite like a table:
![image](https://user-images.githubusercontent.com/43767886/53792257-32065280-3f66-11e9-91bf-4388f75778f8.png)

is there anyway to remove the repeating label, let name, age, location just appear once?

kindly help?
thanks in advance for the reply!

regards,
Yiu Fai

**Comment by tchapi** [comment]
Hi
The library is not really made for such display. You could customize the CSS though, to hide all the labels and _make it look_ like a table.

Just add your custom CSS on top of the existing one and you should be good to go.
