### ISSUE TITLE
datepicker in Safari browser

### ISSUE THREAD

**Issue by PeterGruber** [jsonform/jsonform#219]
Hi! I implemented a 'date' field and it works fine with Firefox (v65)  and also with (IE) but not with the browser Safari (v12). Any idea to fix this problem 

{
  "schema": {
    "field": {
      "type": "string",
      "title": "A field"
    }
  },
  "form": [
    {
      "key": "field",
      "type": "date"
    },
    {
      "type": "submit",
      "title": "Submit"
    }
  ]
}

[example-A.html.zip](https://github.com/jsonform/jsonform/files/2967085/example-A.html.zip)

**Comment by tchapi** [comment]
Hi - could you provide a working JSFiddle so I can help ?

**Comment by PeterGruber** [comment]
Hi! Here it is.
https://jsfiddle.net/PeterGruber/8kwzf5p6/22/

When you use Firefox the datepicker pops up in the in the ‘Date’ field. Don’t with Safari browser.
Thanks for any help!

**Comment by tchapi** [comment]
Safari does not support this input type unfortunately : https://caniuse.com/#search=input-date
