### ISSUE TITLE
Radiobuttons not aligned

### ISSUE THREAD

**Issue by RiklinLundSwe** [jsonform/jsonform#220]
Hi, I'm using the Json Form Playground to learn about the Json Schema and Form. 
The Radiobuttons are not the aligned, with the first one slightly offset downwards. Is this a "feature" of the Playground or is it a bug?

![image](https://user-images.githubusercontent.com/48774406/54722000-c88c6380-4b63-11e9-8448-c1f5ebe592f4.png)

**Comment by tchapi** [comment]
Hi !
This seems related to the Bootstrap implementation. It should be fixable - I will have a look when I have time

Thanks

**Comment by tchapi** [comment]
Can you checkout this PR : https://github.com/jsonform/jsonform/pull/221 and tell me if this solves your problem ?

thanks

**Comment by RiklinLundSwe** [comment]
Hi,

Now it works perfectly!
Thanks.

Rikard

________________________________
Från: tchap <notifications@github.com>
Skickat: den 21 mars 2019 11:55
Till: jsonform/jsonform
Kopia: RiklinLundSwe; Author
Ämne: Re: [jsonform/jsonform] Radiobuttons not aligned (#220)


Can you checkout this PR : #221<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjsonform%2Fjsonform%2Fpull%2F221&data=02%7C01%7C%7Ca609903460314e8eeddb08d6adebc2fb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636887625425629218&sdata=%2FPLBa9kK%2Fng5RAchDwXpVpiawNI2izBP0K62cC94V8M%3D&reserved=0> and tell me if this solves your problem ?

thanks
