### ISSUE TITLE
Value ignored for a boolean as a selectfieldset

### ISSUE THREAD

**Issue by dmlayton** [jsonform/jsonform#222]
Here is the simplest, clear example:
`{
  "schema": {
    "field": {
      "type": "boolean",
      "title": "A field"
    }
  },
  "form": [
    {
      "key": "field",
      "type": "selectfieldset",
      "items": [
        {"type":"help", "helpvalue": "0"},
        {"type": "help", "helpvalue": "1"}
      ]
    },
    {
      "type": "submit",
      "title": "Submit"
    }
  ],
  "value": {
    "field": false
  }
}`
When I put this into the playground, all behavior is that of "field" being true.

**Comment by tchapi** [comment]
Hello

I tested that right now in the playground and when I change the option, I get "true" or "false" depending on the selection, so it seems to be working ? Or maybe I didn't get what your problem is.

I'm using your schema (prettified) : 
```
{
  "form": [
    {
      "items": [
        {
          "helpvalue": "0",
          "type": "help"
        },
        {
          "helpvalue": "1",
          "type": "help"
        }
      ],
      "key": "field",
      "type": "selectfieldset"
    },
    {
      "title": "Submit",
      "type": "submit"
    }
  ],
  "schema": {
    "field": {
      "title": "A field",
      "type": "boolean"
    }
  },
  "value": {
    "field": false
  }
}
```

**Comment by tchapi** [comment]
Closing as there is no update from the OP. Please reopen if this is still an issue on your side
