### ISSUE TITLE
Title of input field

### ISSUE THREAD

**Issue by viniciusyoshiura** [jsonform/jsonform#223]
Hello,

Is It possible to generate an input with title ? In the documentation, there is the description property, but It only shows the description next to the input. What I am trying to generate is something like this:

`<input type="text" class="form-control" name="inputName" value="" id="inputId" title="Title of this input">`

Thanks in advance

**Comment by tchapi** [comment]
Yes it's possible : use htmlMetadata as seen here https://github.com/jsonform/jsonform/commit/cff42c204fe5832801243595a4e2bfe7c399e129
