### ISSUE TITLE
How can i bind source using API?

### ISSUE THREAD

**Issue by VaibhavFortress** [jsonform/jsonform#224]
In Jquery-ui autocomplete sample, 

"customFormItems": {
    "name": {
      "type": "text",
      "autocomplete": {
        "source":  ['abc', 'bed', 'bee', 'dog', 'cat']
      }
    }
}

i want to bind the source from api. Is there any sample or any way to bind the source from API ?

**Comment by tchapi** [comment]
Hi

What sample are you refering to exactly ?

**Comment by VaibhavFortress** [comment]
@tchapi i want to bind source dynamically. One of my Rest API get all users of my system. I wan to bind it in source. how can i do that?

**Comment by tchapi** [comment]
What I'm saying is that there is no sample to use jquery-autocomplete in this repo, so I'm not sure how to help here; If you want to retrieve results before bulding the form, just get a JSON from your API, and then create a JSON form from this JSON dynamically afterwards. This is out of scope of JSON form in itself I guess

**Comment by VaibhavFortress** [comment]
In online playground sample is available i.e.

http://ulion.github.io/jsonform/playground/bootstrap3/?example=fields-text-autocomplete

**Comment by tchapi** [comment]
That's @ulion 's repository, not this repo, you can create an issue on his repository.

**Comment by VaibhavFortress** [comment]
Ok...
Thanks @ch
