### ISSUE TITLE
AdvancedFieldSet Title / Legend can't be changed

### ISSUE THREAD

**Issue by midi-foot-controller** [jsonform/jsonform#226]
I tried to change the title / legend of an advancedFieldSet. When looking at the JS files it seems to be hard-coded to "Advanced Options". I modified the JS code fragment and changed it to:

  'advancedfieldset': {
    'template': '<fieldset' +
      '<% if (id) { %> id="<%= id %>"<% } %>' +
      ' class="expandable <%= elt.htmlClass?elt.htmlClass:"" %>">' +
      **'<legend><%= elt.legend ? elt.legend : "Advanced options" %></legend>' +**

which allows to change it by JSON like this:

 "form": [
{
      "type": "advancedfieldset",
      **"legend": "Leg",**
...
} 

Is there an other solution?

Thanks in advance

Jens

**Comment by tchapi** [comment]
This is very true and this should be changed in the library.
I'll do that and keep you posted
