### ISSUE TITLE
expanded not reflected on sub elements

### ISSUE THREAD

**Issue by midi-foot-controller** [jsonform/jsonform#228]
I tried the following sample

<pre>
{
  "schema": {
    "name": {
      "type": "string",
      "title": "Name"
    },
    "age": {
      "type": "number",
      "title": "Age"
    }
  },
  "form": [
    "name",
    {
      "type": "advancedfieldset",
      ____"htmlClass": "expanded",____
      "items": [
        "age"
      ]
    }
  ]
}
</pre>
 
adding "htmlClass": "expanded" on the fieldset shows the chevron as opened but all sub-elements still have style **"display:none"** instead of **"display:block"**. How can a fieldset shown as opened by default without the need of a mouse click?

Thanks in advance 

Jens

**Comment by tchapi** [comment]
Hi Jens,

The "expanded" class basically only dictates what the legend icon will be, but the behavior is done in javascript afterwards.

As noted in the wiki (https://github.com/jsonform/jsonform/wiki#set-of-fields-the-fieldset-type) you can add styles for the expandable section though, and one that would force the `.expanded .form-group` to `display: block` for instance, something like that : 

    .expandable.expanded .form-group {
        display: block !important;
    }

Hope that helps

**Comment by midi-foot-controller** [comment]
Sorry, to bother you, but this is not working, because you can't close sections anymore after applying this style. I like to open/close sections especially in complex search forms so the use can hide unimportant sections while the form is initially opened or even better "parts of it" are opened while others are closed.
