### ISSUE TITLE
How to set a data-attribute of select <option>?

### ISSUE THREAD

**Issue by viniciusyoshiura** [jsonform/jsonform#229]
Hello,

Is it possible to create data-attributes for each `<option>` of a `<select>` element? Something like this:
`<select><option data-attr="data1">Option 1</option><option data-attr="data2">Option 2</option><option data-attr="data3">Option3</option></select>`

Thanks in advance

**Comment by tchapi** [comment]
Hi @viniciusyoshiura 

At the moment no, it's not possible.

But you can have values for each of these options, and if you really want to have a `data-attr`, you can iterate with javascript over all the options and add a `data-attr` on each.
