### ISSUE TITLE
Generated HTML attributes 'class' and 'id' of fieldsets contain whitespace

### ISSUE THREAD

**Issue by tapulator** [jsonform/jsonform#231]
My schema has some keys that contain whitespace, like

    {
      "schema": {
        "this is a key": {
          "title": "Some form group",
          "type": "object",
          "properties": { ... }
        }
      }
    }

As I see it, JSON Form generates HTML classes and IDs from the schema keys for fieldsets. The HTML for my example looks like this:

`<fieldset class="form-group jsonform-error-this is a key" id="jsonform-1-elt-this is a key"> ... </fieldset>`

This behavior leads to unwanted results. In my example, the style of a CSS class `.a` could be applied to the fieldset.

*Any chance to support multi-word schema keys with properly generated `class` and `id` attributes?*

Maybe replacing the whitespace with `_` while generating the attributes does suffice. So the HTML in my example would look like this:

`<fieldset class="form-group jsonform-error-this_is_a_key" id="jsonform-1-elt-this_is_a_key"> ... </fieldset>`

But I'm new to JSON Form, so I don't see the implications of that solution. :grimacing:

My current workaround is to hook into the `onBeforeRender` handler of the `JSONForm.fieldTypes.fieldset` to fix the values of `data.keydash` and `data.id`. Seems to work, at first glance.

**Comment by tchapi** [comment]
Hi @tapulator 

For the **id** : You can change it quite easily in the form, like this : 

```
{
  "schema": {
    "this is a field": {
      "type": "string",
      "title": "A field"
    }
  },
  "form": [
    {
      "key": "this is a field",
      "id": "myId"
    }
  ]
}
```

As for the rest, you cannot change the behaviour easily (_except with your proposed handler solution_). I think this is not ideal and am working on a fix at the moment. Replacing ` ` with `_` looks quite straightforward and the right thing to do.

Will keep you posted on this thread

**Comment by tchapi** [comment]
This last commit should fix it. Tell me if you encounter any other problems related to that

**Comment by tapulator** [comment]
Looks good! :smiley: Thank you for the quick fix, @tchapi! :+1:
