### ISSUE TITLE
Expandable fieldset with tabarray: when adding tab and expanded class is preserved but all fields are hidden

### ISSUE THREAD

**Issue by elibus** [jsonform/jsonform#233]
The behaviour is shown when using expandable fieldset with tabarray.
Adding a new tab hides all fieldsets/divs with this:
`$(".expandable > div, .expandable > fieldset", node.el).hide();`

As a result, all fields are hidden in the new added tab and in the existing tabs, however expanded fieldsets keep the "expanded" class even though all fields are hidden.
It becomes visible when using visual formatting like explained here https://github.com/jsonform/jsonform/wiki#fields-fieldset

To reproduce the issue:
1. Use tabarray with expandable fieldset
2. Expand a fieldset
3. Create a new tab
4. Check the previously expanded fieldset has the "expanded" class

**Comment by tchapi** [comment]
Your PR is merged, thanks @elibus !
