### ISSUE TITLE
Compatible with Lodash?

### ISSUE THREAD

**Issue by aswinkumar863** [jsonform/jsonform#237]
Already using Lodash in my project.
```
Uncaught TypeError: Cannot read property 'appendChild' of undefined
    at jsonform.js:3074
```
 Any possible way to overcome this?

Thanks in advance!

**Comment by tchapi** [comment]
Hello
How is this related to Lodash ?
Can you post here a schema that gives you this error ?

**Comment by tchapi** [comment]
Closing this issue as there is no update from the OP. Please reopen with details about your exact issue if you still experience a problem
