### ISSUE TITLE
Is it possible to create nested form inputs

### ISSUE THREAD

**Issue by mittal16985** [jsonform/jsonform#238]
Hi I am have radios options and trying to create nested input if one of the radio option is selected. Below is what I am trying to accomplish:

![image](https://user-images.githubusercontent.com/8986857/59125737-da8ece80-8928-11e9-8f53-8bbc4091e2e5.png)

Below is the code I am working with:

```
{
    "schema": {
        "options": {
             "type": "string",
             "title": "<b>Options:</b>",
             "enum": [ "Option1", "Option2"]
        },
        "option1": {
            "type": "string",
            "title": "Option1",        
            "enum": ["Textbox1", "Textbox2"]
        },
        "textbox1" : {
            "type": "string",
        },
        "textbox2" : {
            "type": "string",
        }
    },
    "form": [
    {
        "type": "fieldset",
        "title": "<b style='cursor: pointer'>Options <i class='fas fa-sort'></i></b>",
        "expandable": true,
        "items": [
        {
            "key": "Options",
            "type": "radios"
        },
        {
            "key": "option1",
            "items": [
              {
                "key": "textbox1"
              },
              {
                "key": "textbox2"
              }
            ]
         }
         ]
      },
    ]
  
}
```
Is there a way we can easily do this with this jsonform library?

**Comment by tchapi** [comment]
Technically, not exactly what you're looking for, but it should be equivalent : https://jsonform.github.io/jsonform/playground/index.html?example=fields-selectfieldset

Instead of having radio buttons, it's a select box, so it's kind of the same. And you can have different text boxes under each option.

Would that work for you ?

**Comment by AndreaEBM** [comment]
Can I piggyback on this question to ask if 3 levels of nesting is possible?
ie Select list A -> select list B -> select list C?
Eg Continents -> Countries -> Cities
I am new to this and whilst I can happily get 2 select boxes working off each other, the third level is stumping me at the moment...

**Comment by tchapi** [comment]
You can go two levels, but 3 I don't see how you could natively. Using some custom Javascript on the top-level (continents) could do the trick (you swap the jsonForm, one jsonform per continent)

Here for 2 levels : 
```
{
  "schema": {
    "oceania": {
      "type": "string",
      "title": "Oceania",
      "enum": [
        "Australia",
        "Tasmania"
      ]
    },
    "europe": {
      "type": "string",
      "title": "Europe",
      "enum": [
        "France",
        "UK"
      ]
    }
  },
  "form": [
    {
      "type": "selectfieldset",
      "title": "Choose a continent",
      "items": [
        {
          "key": "oceania",
          "legend": "Oceania"
        },
        {
          "key": "europe",
          "legend": "Europe"
        }
      ]
    },
    {
      "type": "submit",
      "title": "Submit"
    }
  ]
}
```

**Comment by AndreaEBM** [comment]
Thanks, that is indeed what I have for my working 2 levels. I will see if I can get multiple forms working. In my actual requirement I only have two top level choices so that may not be too bad.
