### ISSUE TITLE
Delete i'th item in array

### ISSUE THREAD

**Issue by qstevens** [jsonform/jsonform#240]
It appears that you can only delete the last item in an array. This seems like a bug as one of the earlier playgrounds allow for deletion of any item in an array. Is it possible to restore this functionality as it seems like it would be quite useful to have (other json form projects also have this functionality).

**Comment by tchapi** [comment]
Hello
Can you give me an example schema so I can test that ?

**Comment by qstevens** [comment]
https://jsonform.github.io/jsonform/playground/index.html?example=schema-array

Add a couple items to the array. You will be able to move items around but cannot delete any but the last item. This functionality was present in an earlier version.

**Comment by tchapi** [comment]
I don't recall a time when we could delete the _n_th item in an array in this lib. Do you have an idea as to which commit would have introduced this regression ?

There has not been any changes on this particular feature over the past year I think.
