### ISSUE TITLE
Error in jsonform.js

### ISSUE THREAD

**Issue by groundswel** [jsonform/jsonform#244]
I am getting the following error TypeError: key
    .replace is not a function. (In 'key
    .replace(/\./g, '.properties.')', 'key
    .replace' is undefined) at jsonform.js:1593

I have this at the beginning of the html file. 
<script type="text/javascript" src="jsonform/deps/jquery.min.js"></script>
<script type="text/javascript" src="jsonform/deps/underscore.js"></script>
<script type="text/javascript" src="jsonform/deps/opt/jsv.js"></script>
<script type="text/javascript" src="jsonform/lib/jsonform.js"></script>

**Comment by tchapi** [comment]
Hello
Can you indicate a schema that gives this error in the playground ?
