### ISSUE TITLE
checkboxbuttons not in the documentation/wiki but it's on the playground

### ISSUE THREAD

**Issue by kokizzu** [jsonform/jsonform#247]
When I try to use it, it throws an error:
`Uncaught Error: The JSONForm contains an element whose type is unknown: "checkboxbuttons"`

edit: I copied the javascript from the playground and it works

**Comment by kokizzu** [comment]
weird, now it's gone '__')

**Comment by tchapi** [comment]
Hi @kokizzu

You may have stumbled on the playground of a fork (for instance, @ulion's) that includes this element ?

Closing for now
