### ISSUE TITLE
Splitting a form into tabs (not tabarray)

### ISSUE THREAD

**Issue by iluuu1994** [jsonform/jsonform#250]
I'd like to split different translations of a form into different tabs, similar to this:

![image](https://user-images.githubusercontent.com/1752683/68781169-ad60ed80-0637-11ea-8403-3ca0dfb6b7de.png)

My schema would look something like this:

```json
{
    "type": "object",
    "properties": {
        "menu_entry": {
            "type": "object",
            "title": "Menueintrag",
            "properties": {
                "de": {
                    "type": "string",
                    "title": "DE"
                },
                "fr": {
                    "type": "string",
                    "title": "FR"
                }
            }
        }
    }
}
```

All fields would hold an object with the language keys instead of holding the values directly. But the fields should be split into tabs instead of displaying them all in separate rows.

I don't think this is possible right now, correct? I could find anything in the documentation.

Thanks for your response!

**Comment by tchapi** [comment]
Hello

No it's not possible at the moment. How about having 3 different forms, on for each language, that you display in tabs ?

**Comment by iluuu1994** [comment]
Hi @tchapi. Thanks for your response! That would work for most forms. This is just closer to how we store things in the database. For arrays, we'd want all languages to contain the same number of elements which would require additional validation. Furthermore some fields don't need to be translated (e.g. checkboxes) which would split the form into a translated and non-translated section which is not necessarily the best way to split the form.

We decided to go with [jsonforms](https://github.com/eclipsesource/jsonforms). Feel free to close this issue if you don't think this adds any value to your library.

Thanks again!

**Comment by tchapi** [comment]
No problem, understood.

Happy coding,
BR
