### ISSUE TITLE
Is there a way to change datatype in onBeforeRender()?

### ISSUE THREAD

**Issue by Jasata** [jsonform/jsonform#253]
I was trying to do this in `onBeforeRender: function (data, node) { ..` by setting the `.type` s I could find:
```javascript
data.schema.type = "string";
data.elt.type = "string";
data.value = formatBytes(data.schema.default, 2); // Becomes "1.62 GB", for example
```
(yes, I am carrying database values in `.default` ... best place I could come up with).

This stumbling in the dark didn't work as I hoped, and I get JQuery complaints:
`jquery.min.js:2 The specified value "1.62 GB" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?`

In this wonky case, the database handles sizes in bytes, but in reality, these are indicative and user input most of the time. For that reason, it would make sense to let the user deal with them in more manageable presentation.

Is there a way to accomplish this? Render a value from interger to string, and when form is about to be submitted, can I write a code somewhere to return the field back into an integer type?

**Comment by tchapi** [comment]
Hi
What about having a separate field (that is not submitted) in whatever format you like, and catch the `submit` event and copy the value, "de-format" it, and paste it in the real field, that is submitted ?

Have you explored this way of handling things ?

**Comment by Jasata** [comment]
First version of this reply, while typing it, helped me to come up with answers to some questions about how to do that in my case... Reply version 2:

That sound like a reasonable thing to do. I just need to create display fields after retrieving data (value for JSONForm) and schema from API and then interpret values back to the actual fields before PUT'ing the entity back to API. I will try that!

BTW, I am extra happy that `schema` does not require those presentation related values. That makes so much more sense that "the next leading brand" -way of doing this, and the schema provided by the API (automatically parsed from the database table and its constraints) matches beautifully. ...leaving `form` with purely presentation related items. Nice and clear, making things easier!

Cheers!
