### ISSUE TITLE
Enum link to lookup tables

### ISSUE THREAD

**Issue by learner291** [jsonform/jsonform#254]
Hi,

I have a question regarding enum. Is it possible to display text but on selection send an id of the selection from drop down? For example, I store list of Nationalities in a lookup table and I would like to store id from Nationalities lookup table into my Person table.

I have an asp.net background so Text property for drop down in Asp.net displays the actual nationalities and Value property of the drop down stores id which allows me to use SelectedValue property of the drop down to retrieve and store in database. 

I couldn't find any code example in the documentation which I can use for this purpose.

**Comment by tchapi** [comment]
Hi
You should put the values in the `enum` and add a `titleMap` to display specific text for each value : See https://github.com/jsonform/jsonform/wiki#selection-fields for instance
