### ISSUE TITLE
Pre-populating Date

### ISSUE THREAD

**Issue by learner291** [jsonform/jsonform#255]
I am using following code to generate a form. I would like to pre-populate the date but it is not populating.

`{
  "schema": {
    "client": {
      "type": "object",
      "title": "Client",
      "properties": {
        "forename": {
          "type": "string",
          "title": "Forename"
        },
        "surname": {
          "type": "string",
          "title": "Surname"
        },
        "dateOfBirth": {
          "type": "string",
          "title": "Date of Birth"
        }
      }
    }
  },
  "form": [
    {
      "key": "client.forename",
      "title": "Forename",
      "value": "ABX"
    },
    {
      "key": "client.surname",
      "title": "Surname"
    },
    {
      "key": "client.dateOfBirth",
      "title": "Date of Birth",
      "type": "date",
      "value": "2020-01-19T00:00:00+00:00"
    }
  ]
}`

I have also tried following but of no use.

`"value: "01/01/2020"`

**Comment by tchapi** [comment]
See https://github.com/jsonform/jsonform/issues/195

**Comment by learner291** [comment]
Thanks

**Comment by learner291** [comment]
Just one more question regarding populating values. I am using following code to pre-populate values, it works fine if a field is not a part of object e.g, prePopulate field below, however, it is not working for client.forename and client.surname. There is no error in console. Am I following correct format for client.forename?
`{
  "schema": {
    "client": {
      "type": "object",
      "title": "Client",
      "properties": {
        "forename": {
          "type": "string",
          "title": "Forename"
        },
        "surname": {
          "type": "string",
          "title": "Surname"
        },        
      }
    },
    "prePopulate":{
      "type": "string",
      "title": "Is Populating"
    }
  },
  "form": [
    {
      "key": "client.forename",
      "title": "Forename",      
    },
    {
      "key": "client.surname",
      "title": "Surname"
    },    
    "prePopulate"
  ],
    "value": {
    "client.forename": "Not working",
    "client.surname": "Not working",
    "prePopulate": "Working Fine"    
  }
}`

**Comment by tchapi** [comment]
It's an object, so you should describe it as such :

```
{
  "schema": {
    "client": {
      "type": "object",
      "title": "Client",
      "properties": {
        "forename": {
          "type": "string",
          "title": "Forename"
        },
        "surname": {
          "type": "string",
          "title": "Surname"
        }
      }
    },
    "prePopulate": {
      "type": "string",
      "title": "Is Populating"
    }
  },
  "form": [
    {
      "key": "client.forename",
      "title": "Forename"
    },
    {
      "key": "client.surname",
      "title": "Surname"
    },
    "prePopulate"
  ],
  "value": {
    "client": {
      "forename": "Not working",
      "surname": "Not working"
    },
    "prePopulate": "Working Fine"
  }
}
```

**Comment by learner291** [comment]
Thank you, this is working now.
