### ISSUE TITLE
Can you apply conditional logic?

### ISSUE THREAD

**Issue by katie6** [jsonform/jsonform#256]
Hi there, 

Is it possible (and if so, how) to show a form field based on the value selected for a previous field?

For example, if I want the form to include a question: "Do you have a specific date in mind?" If they select 'yes' then it will show a date picker and if they pick 'no' it will move on to the next question.

Many thanks,

Katie

**Comment by tchapi** [comment]
Are you looking for something like https://github.com/jsonform/jsonform/issues/238 ?

**Comment by katie6** [comment]
Yes, that looks like it could work! Thank you tchapi - I will look at this in detail and figure out what to do. Much appreciated :)

**Comment by katie6** [comment]
Hello again, I've just had a look at this in more detail and I'm not sure if it will work? Selectfieldsest appears to allow you to create a second list based on the selection of a first list (i.e. one select form field after another). However I want to create a date field based on the selection of the first select list. Is this possible? I was pondering using jquery, such as below...but all I've managed to do is create an alert on click. Do you know how I would create a new field on click instead?!

Thanks again,

Kate

```
schema:{
dateInMind:{
					type: 'string',
					title: 'Do you have a specific date in mind?',
					enum:[
						'yes',
						'no'
					]
},
'form':[
				{
				  "key": "dateInMind",
				  "onChange": function (evt) {
					var value = $(evt.target).val();
					if (value == 'yes') {
						alert(value);
					}
				  }
				}
]
});
```

**Comment by tchapi** [comment]
You could just load a different form JSON object when the value is `yes`; that would mean having different objects for different states of the form but if it's only one choice, it should be relatively straightforward.

**Comment by katie6** [comment]
Well, eventually I will want to build this out so a choice further up the form affects all the fields beneath it. The conditional logic may be fairly complex so there will be multiple form fields which affect others.  I'm wondering whether I am taking the most sensible approach? I think jsonform is really neat, but is it the most sensible approach in this case?

**Comment by tchapi** [comment]
I'm not sure — you might want to have something that has more flexibility in terms of dynamic fields...

**Comment by tchapi** [comment]
Closing as this is likely a matter of choosing a library that has more flexbility for your use case
