### ISSUE TITLE
Form Submission URL

### ISSUE THREAD

**Issue by learner291** [jsonform/jsonform#257]
I have been trying to find something in documentation regarding the URL which is called when a submit button is clicked but unable to find it. Currently when I click submit button, alert box displays all the values but where I should define the URL it should send those values to?

I thought I could call my asp.net mvc controller URL in "onSubmit" function but alert code added into "onSubmit" handler is not executed at all. Is this the correct approach? Thanks.

`{
  "schema": {
    "client": {
      "type": "object",
      "title": "Client",
      "properties": {
        "forename": {
          "type": "string",
          "title": "Forename"
        },
        "surname": {
          "type": "string",
          "title": "Surname"
        }
      }
    },
    "prePopulate": {
      "type": "string",
      "title": "Is Populating"
    }
  },
  "form": [
    {
      "key": "client.forename",
      "title": "Forename"
    },
    {
      "key": "client.surname",
      "title": "Surname"
    },
    "prePopulate",    
    {
      "type": "submit",
      "title": "OK Go - This Too Shall Pass"
    }
  ],
  "value": {
    "client": {
      "forename": "working1",
      "surname": "workinga"
    },
    "prePopulate": "Working Fine"
  },
  "onSubmit": function (errors, values) {
    alert("Here I should send the values, but this code is not executed")
  }
}`

**Comment by tchapi** [comment]
See the "Getting started" section of the Wiki (https://github.com/jsonform/jsonform/wiki#getting-started) — there is an example of a working `onSubmit` function. Just call your url there.
