### ISSUE TITLE
Form Layout

### ISSUE THREAD

**Issue by learner291** [jsonform/jsonform#259]
I have a couple of questions regarding the form layout:

1) I am trying to display a label to the left side, I have used the following code but the title 'Forename' is still coming up in the middle, see the image below.. On the playground, titles are displayed on the left without any explicit htmlClass so this is causing me confusion.

`{"key":"client.forename","title":"Forename","htmlClass":"float-left"}`

![Forename](https://user-images.githubusercontent.com/40409548/72914034-f323eb80-3d35-11ea-8f2e-f04226660ddf.png)

2) Second question is to do with number of columns on the form. Currently, all form elements are displayed in a single column. Is it possible to have two column form, do you have any example to accomplish two column form?

Thanks

**Comment by learner291** [comment]
I have managed to display the label to the left side now. 

Can you help with the second question?
Second question is to do with number of columns on the form. Currently, all form elements are displayed in a single column. Is it possible to have two column form, do you have any example to accomplish two column form?

**Comment by tchapi** [comment]
jsonform uses **Bootstrap 3** classes, but I'm not sure it's easy to separate the form in different columns, to be honest.

You could still use the `"htmlClass"` property on form elements, and then use CSS to achieve the result you seek (_for example by setting column width and floating everything to the left_).
