### ISSUE TITLE
Date Picker is not being bootstrapped

### ISSUE THREAD

**Issue by learner291** [jsonform/jsonform#260]
Hi,

I am using following json but date picker is not being bootstrapped.

`
{
  "schema": {
    "client": {
      "type": "object",
      "title": "Client",
      "properties": {
        "forename": {
          "type": "string",
          "title": "Forename",
          "minLength": 3,
          "maxLength": 10
        },
        "gender": {
          "type": "string",
          "title": "Gender",
          "enum": ["male", "female"]
        },
        "dateOfBirth": {
          "type": "string",
          "title": "Date of Birth"
        }
      }
    }
  },
  "form": [
    {
      "key": "client.forename",
      "title": "Forename"
    },
    {
      "key": "client.gender",
      "title": "Gender",
      "titleMap": {
        "male": "Dude",
        "female": "Dudette",
        "alien": "I am from out of space"
      }
    },
    {
      "key": "client.dateOfBirth",
      "title": "Date of Birth",
      "type": "date",
      "fieldHtmlClass": "date"
    }
  ],
  "value": {
    "client": {
      "forename": ""
    }
  }
}
`

I am calling following jquery method in java script as well but of no use.

`
$('.date').datetimepicker();
`

It is currently rendering as per below image.
![Incorrect Date Picker](https://user-images.githubusercontent.com/40409548/73104094-85222480-3eed-11ea-8684-a9a5b9452b08.png)

Where as I would like it to render as per below image, including a calendar image

![Correct Date](https://user-images.githubusercontent.com/40409548/73104115-91a67d00-3eed-11ea-918c-27537baa2b81.png)

Can you please provide guidance on how to achieve? I have tried setting "fieldHtmlClass" but of no use?

**Comment by learner291** [comment]
Just to preempt a possible question, I am importing following files.

`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css"> 
`
`<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/js/bootstrap-datetimepicker.min.js"></script>`

Also, is it possible to use a different library for styling such as [https://keenthemes.com/metronic/](url), if yes, is there any guidance available?

We are just trying to resolve a couple of issues in our evaluation phase so that we can start using jsonform in production system, so any help would be highly appreciated.

**Comment by learner291** [comment]
Can someone help regarding this please as I am keen to use jsonform in production but need to fully implement different scenarios on a demo system before going ahead?

**Comment by tchapi** [comment]
This likely is a problem with the Bootstrap plugin you use, or how it's inited. Are you sure that your `$('.date')` selector is correct and targets the correct field ?

I myself have no previous experience with this plugin, hence I cannot help you much further, sorry.

**Comment by tchapi** [comment]
I'm closing this since it's relevant to the external plugin you use. Feel free to reopen if there is a bug in JSONform
