### ISSUE TITLE
Possibility to set a placeholder for a Dropdown-Menu

### ISSUE THREAD

**Issue by ValentinFFM** [jsonform/jsonform#265]
Is it possible to add a placeholder for a dropdown Menu? 

In general when I work with HTML, I add a additional option into the dropdown Menu and set it to "hidden". So it's visible in the DropDown Menu, but not selectable. Is this option also in this library possible?

![image](https://user-images.githubusercontent.com/58034499/75781551-b21fed80-5d5d-11ea-9cd8-d78d9df852de.png)

**Comment by tchapi** [comment]
Hello @ValentinFFM 
There is no option for that yet — you're welcome to propose a PR if ever you have the time to add it.

Best regards

**Comment by ValentinFFM** [comment]
Hey @tchapi 
thanks for your fast answer. :) That's sad, but mabye we will work on this in our team, because we need this function. If that's so, then I will afterwards make a PR.
Greetings from Germany,
Valentin
