### ISSUE TITLE
Missing screenshot in Wiki

### ISSUE THREAD

**Issue by rafaellehmkuhl** [jsonform/jsonform#266]
On the "Dealing with arrays" section of the wiki, there's a paragraph starting with "And here is a screenshot of the form generated by JSON Form.", but there is no screenshot.

**Comment by tchapi** [comment]
Hi @rafaellehmkuhl 
You are perfectly right but since the playground is an easy way to test a schema, I modified the sentence to remove the reference to the screenshot, and adjusted the schema so you can just copy and paste it in the playground. Thanks !
