### ISSUE TITLE
Improve input type "search"

### ISSUE THREAD

**Issue by gandy92** [jsonform/jsonform#267]
In some text input fields, I need my form to make suggestions for possible values, while still allowing to enter new values. A selection list doesn't allow this, so I tried to use a "search" type input field. I soon learned that currently, _jsonform_ does not add the required `<optionlist>` with `<option>` elements. Fortunately, I managed to extend my copy of _jsonform_, accordingly:
```
{
  "schema": {
    tag: {
      type: 'string',
      title: 'Tag',
      enum: ['Suggestion 1', 'Suggestion 2', 'Suggestion 3']
    }   
  },
  "form": [
    {
      "key": "location",
      "type": "search"
    },
  ]
}
```

In my use case, I want the suggestions to be retrieved from a database, so I use an API call:
```
{
  "schema": {
    tag: {
      type: 'string',
      title: 'Tag'
    }   
  },
  "form": [
    {
      "key": "location",
      "type": "search",
      "enumSrc": "/api/v1/inventory/suggest/location/{partial}"
    },
  ]
}
```
Here, when the user begins typing, a list of suggestions is retrieved from the server with strings containing the already typed text. From this, _jsonform_ updates the `<optionlist>`.

I'm achieving this with the following code:
```
  'search':{
    'template':'<input type="search" name="<%= node.name %>" id="<%= id %>" value="<%= escape(value) %>"' +
      'class=\'form-control<%= (fieldHtmlClass ? " " + fieldHtmlClass : "") %>\'' +
      '<%= (node.disabled? " disabled" : "")%>' +
      '<%= (node.readOnly ? " readonly=\'readonly\'" : "") %>' +
      '<%= (node.schemaElement && node.schemaElement.disabled? " disabled" : "")%>' +
      '<%= (node.schemaElement && node.schemaElement.required ? " required=\'required\'" : "") %>' +
      '<%= (node.placeholder? " placeholder=" + \'"\' + escape(node.placeholder) + \'"\' : "")%>' +
      'list="<%= id %>_list" ' +
      'autocomplete="off"/>'+
      '<datalist id="<%= id %>_list">' +
      '<% _.each(node.options, function(key, val) { if(key instanceof Object) { %> ' +
         '<option value="<%= key %>"><%= val %></option> '+
      '<% } else { %> '+
         '<option value="<%= key %>"/>'+
      '<% }}); %> ' +
      '</datalist>',
    'fieldtemplate': true,
    'inputfield': true,
    'onInsert': function (evt, node) {
        var elt = node.formElement || {};
        if (elt.enumSrc) {
            console.log('search element with "enumSrc":',elt.enumSrc,'- adding event handler');
            var oldSearchValue="";
            minLength = elt.minReqLen || 1;
            console.log('minLength is', minLength);
            $(node.el).on('input', function() {
                value = $(node.el).find('input').attr('value', '').val();
                console.log("keyup() - minLength is", minLength, "value length is", value.length);
                console.log("keyup() - oldSearchValie is", oldSearchValue, "value is", value);
                if(value.length >= minLength && value != oldSearchValue) {
                    oldSearchValue = value;
                    var loc = elt.enumSrc.replace('{partial}', value);
                    // Todo: how can we do this more elegantly? if (loc[0] === '/') loc = baseUrl + loc;
                    $.get(loc, {}, function(data) {
                        console.log("requesting search data from ", loc, " returned: ", data);
                        var datalist = $(node.el).find('datalist');
                        datalist.empty();
                        if (Array.isArray(data)) {
                            for (i=0; i<data.length; i++) {
                                datalist.append($('<option></option>').attr("value", data[i]));
                            }
                        }
                    }, "json");
                }
            });
        }
    }
  },
```
This works quite well, with one minor flaw: The base URL for the query may vary between http://localhost:6543/ and https://myfancyserver.xyz/myfancydb/. With the template system of the server app I can provide a global JavaScript variable "baseUrl" and use it to build the request URL, like in the commented out code above. But I'm sure there must be way better ways to do this. Unfortunately, lack the experience with Javascript, jQuery and even HTML5, so I'm hoping for good suggestions.

Thanks,
Andy.

**Comment by tchapi** [comment]
Hi Andy
If it works, it can't be that bad.
If I were you though, I'd _always_ append the `baseUrl` to `loc`, and change it on the server, either to your local address (`http://localhost:6543`) or any remote server. This way, you always have an absolute url, and it's predictable

**Comment by gandy92** [comment]
Hi, thank you ffor your feedback. Meanwhile, I found a way to do just that, without the need for jsonform to know anything about the baseUrl. If you like, I'll prepare a PR for you to review, maybe including a simple example (without querying the server) for the playground. Anything else that the PR should include?
