### ISSUE TITLE
Controlling the layout of the form

### ISSUE THREAD

**Issue by dave-sapienza** [jsonform/jsonform#269]
Hi all,

I have some problem in controlling the layout of this schema:

<pre>
{
  "schema": {
    "paramSettings":{
      "type":"object",
      "title":"Paramater settings",
      "properties":{
        "inputList":{
          "type":"array",
          "title":"List",
          "items":{
            "type":"object",
            "title":"Parameter",
            "properties":{
              "paramName":{"type":"string","title":"Nome"},
              "paramLabel":{"type":"string","title":"Label"},
              "paramRequired":{"type":"boolean","title":"Required"},
              "paramDefaultValue":{"type":"string","title":"Default value"},
              "paramType":{
                "type":"string",
                "title":"Type",
                "enum":["0","1","2","3"]
              },
              "arrayValue":{
                "type":"string",
                "title":"Array values",
                "description":"In case of type = \"map\""
              }
            }
          }
        }
      }
    }
  },
  "form": [
    {"key":"paramSettings"}
  ]
}
</pre>

I've tried adding a titleMap `{"0":"String", "1":"Number", "2" : "Date", "3":"Map"}` for element `paramType` in `inputList` in `paramSettings`, but I can't. 

Please, could you help me?

Thanks,
Davide

**Comment by tchapi** [comment]
Hello
I'm not sure I understand what your exact problem is with the layout ? Can you elaborate ?

Thanks
