### ISSUE TITLE
Add documentation on how to update or destroy a jsonform

### ISSUE THREAD

**Issue by Tectea** [jsonform/jsonform#271]
In case this functionality is included/intended then it would be great to have this in the Wiki. 

I am creating a jsonform through an ajax call depending on what information the user inputs. E.g. if the user checkes that he is interested in music, then an ajax call for the music questions are triggered and a subform (jsonform) is created. If the user unchecks the music check box, then the subform is removed. 

When removing and creating several subforms it is clear that I am not removing everything with my $('#subform').empty(). For example using the authfieldset toggle function (collapse, expand) gets buggy and fires multiple times.

I was looking through the code to be able to suggest some documentation or changes but I was unable to figure out how to handle this.

**Comment by tchapi** [comment]
Hello @Tectea 
This is not intended _per se_. Do you have a reproducible example of a buggy behaviour, maybe a jsfiddle, so I can have a look ?

BR

**Comment by Tectea** [comment]
See fiddle at https://jsfiddle.net/osmvc2y7/

1. Click the auth field to toggle content
2. Click form1 button
3. Click form2 button
4. Click the auth field to toggle content (Buggy behaviour expected)

**Comment by tchapi** [comment]
Hello

Well you could just clone the original form to remove all event handlers associated, since `empty()` will not do so:
https://jsfiddle.net/t3dsmzj8/

Tell me if that works for you

**Comment by Tectea** [comment]
Awesome! Big thanks for the help and for all work on this!
