### ISSUE TITLE
Event handler after array addition

### ISSUE THREAD

**Issue by kpoman** [jsonform/jsonform#275]
Hello,
I am trying to figure out how to trigger a function after an item has been added to an "array" (in particular because I am using materializecss that needs to call its own initializers after a form element appears). I tried adding a MutationObserver and it enters an infinite loop because the array addition mutates then the materializecss trigger mutates again and so on ...

```
        function mutationCallback(mutationsList, observer) {
            $('select').formSelect();
        }
        var observer = new MutationObserver(mutationCallback);
        var config = { attributes: true, childList: true, subtree: true };
        observer.observe(document.getElementById('health_info'), config);
```

I saw on the source code and the form object that there was something thought in that sense, but not used on jsonform:

```
jsonform.html:268 
l {eventhandlers: Array(0), root: w, formDesc: {…}, domRoot: form#health_info.untouched.well}
domRoot: form#health_info.untouched.well
eventhandlers: Array(0)
```

Is there any mechanism to add a hook for a function to be called after an item is added to an array ?

**Comment by tchapi** [comment]
Hi

Did you try to add an event handler for the click on `$('._jsonform-array-addmore')` ? It should work

**Comment by kpoman** [comment]
Cool, it worked:

`$('._jsonform-array-addmore').on('click', function(){alert('clicked');});`

**Comment by tchapi** [comment]
Perfect !
