### ISSUE TITLE
Loading Form Values from JSON REST API

### ISSUE THREAD

**Issue by darrenlock** [jsonform/jsonform#277]
Sorry for the newbie question but I currently fetch a JSON string from a REST API in my window.onload  function. How do I then assign this JSON to the "value" property to pre-fill the form?

**Comment by tchapi** [comment]
Hi

You mean something like that _(not tested, but you get the idea)_ ?

```
const apiResultAsString = fetch('https://whatever.com/form')
const apiResultAsJSONObject = JSON.parse(apiResultAsString)
$('form').jsonForm(apiResultAsJSONObject);
```

**Comment by darrenlock** [comment]
@tchapi  Doh! I completely missed the fact that the entire form (data schema, form layout & values) is defined using JSON! 

My REST API currently just returns the data model JSON but it could be modified to provide the full JSON. Or I could do some string stitching before calling $('form').jsonForm. 

In the interim I was able to deal with this by doing some server-side template processing and put a replaceable string after "value": which then expands out to the data I want to prepopulate. This has the added benefit of avoiding another call back to the server to get the data. 

I am implementing the server on an IOT device (ESP32) so trying to keep things as compact as possible.

Thank you for the help.

**Comment by kpoman** [comment]
Is there a way to load the values on the form after it has been rendered instead of when intantiating it ? Sometimes the data comes dynamically after the page rendering. Is there a method to set the form values ?
Thank you !

**Comment by tchapi** [comment]
Well in this case I'd recommend initiating the form _after_ you have received these values. You can reinstantiate the form several times I guess, to account for new values coming in
