### ISSUE TITLE
Dropdown for selectfieldset has inconsistent style with other dropdowns in the form.

### ISSUE THREAD

**Issue by cornelius1** [jsonform/jsonform#278]
Looks like the dropdown for selectfieldset is missing the style (CSS class "form-control") used for other dropdowns in the form. Is that intentional?
https://jsonform.github.io/jsonform/playground/index.html?example=fields-selectfieldset
<img width="686" alt="Screen Shot 2020-05-28 at 10 53 20 AM" src="https://user-images.githubusercontent.com/755035/83176230-f0fddf00-a0d1-11ea-9c7c-2cd6c0032874.png">

**Comment by tchapi** [comment]
You're right, and to be honest I think it was a design choice at the start, to separate the actual "choice" from an _actual submitted_ form value.

I think this is quite reasonable, and you can still style the dropdown afterwards if you want.

What do you think ?

**Comment by cornelius1** [comment]
I suppose that is fine.
