### ISSUE TITLE
Contract work similar to this project

### ISSUE THREAD

**Issue by omarali-me** [jsonform/jsonform#281]
I have an urgent requirement to create the reverse of this:

Create a UI that would spit out JSON-format (not input fields) but other structure.

But to 'create' that structure, I would need a UI to .. add step, add criteria etc..and then click on "generate" .. to generate a JSON

if you're interested, hit me up: hello@omarali.me

**Comment by tchapi** [comment]
Hello
This is not the place for this kind of requests unfortunately.

BR
