### ISSUE TITLE
Render Object contains Objects

### ISSUE THREAD

**Issue by massimomannoni** [jsonform/jsonform#282]
I'm trying to render a json schema where I have a dictionary.
This is a schema example 

```
 "alfa": {
      "$ref": "#/definitions/alfa"
    },

// definition
    "alfa": {
      "type": "object",
      "title": "Coupons",
      "properties": {
        "myObject": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/beta"
          }
        },
        "interval": {
          "enum": [
           someintvalues
 ],
          "type": "integer",
          "title": "Interval"
        }
      }
    }

// beta definition
```
the interval elements is rendered but for beta I got only the label

**Comment by tchapi** [comment]
Hello
Can you provide us with a full reproducible example (the full json schema definition) ?
Thanks

**Comment by massimomannoni** [comment]
Hi this is a simple schema definition I created to reproduce the issue.

/// SCHEMA
{
  "type": "object",
  "title": "test",
  "properties": {
    "coupons": {
      "$ref": "#/definitions/Coupons"
    }
  },
  "definitions": {
    "Coupon": {
      "type": "object",
      "title": "Coupon",
      "required": [
        "uid"
      ],
      "properties": {
        "uid": {
          "type": "string",
          "title": "Uid"
        },
        "coupon_rate": {
          "type": "string",
          "title": "Coupon Rate"
        }
      }
    },
    "Coupons": {
      "$id": "#Coupons",
      "type": "object",
      "required": [
        "interval"
      ],
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Coupon"
          },
          "title": "Coupon"
        },
        "interval": {
          "enum": [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11
          ],
          "type": "integer",
          "title": "Interval"
        }
      }
    }
  }
}

**Comment by massimomannoni** [comment]
was an issue related to our logic. tnx
