### ISSUE TITLE
file upload issue

### ISSUE THREAD

**Issue by sammyau** [jsonform/jsonform#284]
trying to add upload files , but not getting the uploaded file info in the output.
and also should be able to upload multiple files and different file types.
schema sample below.
{
  "schema": {
     "photo": {
        "type": "string",
        "title":"upload images"
      }
  },
  "form": [
      {"key": "photo", "type": "file" },
      {
        "type": "actions",
        "items": [
          {
            "type": "submit",
            "title": "Submit",
            "htmlClass":"btn"
         
          }
        ]
      }
  ],

  
  onSubmit: function (errors, values) {
consol.log(values);                    
    
      if (errors) {
          var myJSONText = JSON.stringify(errors); 
      } else {
          var myJSONText = JSON.stringify(values); 
      }
alert(myJSONText);                    
  }
}

**Comment by tchapi** [comment]
Hello

Well, you need to process the file if you want to have the data. You could use the FileReader API for instance (see https://developer.mozilla.org/en-US/docs/Web/API/FileReader)

**Comment by collimarco** [comment]
Have you found a solution for the file upload? Do you have an example?
