### ISSUE TITLE
Type null or string for date value 

### ISSUE THREAD

**Issue by massimomannoni** [jsonform/jsonform#285]
Defining a type as [string, null] for date value, hide calendar icon.

**Comment by tchapi** [comment]
Can you elaborate ? Maybe give a minimum reproducible example ? https://stackoverflow.com/help/minimal-reproducible-example

**Comment by massimomannoni** [comment]
Hi , starting from "seed" https://jsonforms.io/docs/getting-started , change the json schema 
`    "due_date": {
      "type": "string",
      "type": ["string", "null"],
      "format": "date"
    },
` 
adding "null" to the type array. 
The result is the icon used to display calendar popup, disappear.
Thanks in advance
MM

**Comment by tchapi** [comment]
The documentation you link refer to another project. You're looking for https://github.com/eclipsesource/jsonforms I guess.
