### ISSUE TITLE
Is there an option to display value with range?

### ISSUE THREAD

**Issue by HeraldtenDam** [jsonform/jsonform#291]
Hi,

new to jsonforms I see never an example of having the values (minimum,maximum) displayed at the range form field. Is this possible (maybe not documented) or is there a trick?

Thanks
Herald

**Comment by tchapi** [comment]
Hi there

There is no such feature, but you can simply add a little bit of javascript to update the label with the new value for instance.

Something along those lines :

```
$("#myrange").on("input change", function() {
    // update the value of a label for instance
});
```
