### ISSUE TITLE
Expanded fieldset get closed when "Add new" button is clicked.

### ISSUE THREAD

**Issue by TheJosean** [jsonform/jsonform#292]
Hi, 

First of all, thanks for that code. It saves me a lot of time.

My issue (which happens also in playground) is when i click on + button to add a new array element, the expanded fieldset is closed (with - button does not happen). That only happens when the array item has an other array item inside. 

This is an example of the full JSON, for playground, I'm trying to use.

```
{"schema":{"type":"object","properties":{"config":{"type":"object","title":"config","properties":{"steps":{"title":"steps","type":"array","items":{"type":"object","title":"steps","properties":{"category":{"title":"category","type":"array","items":{"type":"object","title":"categories","properties":{"name":{"type":"string","title":"name"},"subcategory":{"type":"object","title":"subcategory","properties":{"name":{"type":"string","title":"name"}}}}}}}}}}}}},"form":[{"expandable":true,"title":"config","type":"fieldset","items":[{"expandable":true,"title":"steps","type":"fieldset","items":[{"expandable":true,"type":"array","title":"steps","items":[{"expandable":true,"type":"fieldset","title":"{{idx}}","items":[{"expandable":true,"title":"category","type":"fieldset","items":[{"expandable":true,"type":"array","title":"category","items":[{"expandable":true,"type":"fieldset","title":"{{idx}}","items":[{"title":"name","type":"section","items":[{"key":"config.steps[].category[].name"}]},{"expandable":true,"title":"subcategory","type":"fieldset","items":[{"title":"name","type":"section","items":[{"key":"config.steps[].category[].subcategory.name"}]}]}]}]}]}]}]}]}]}]}
```

Please tell me if I'm doing something wrong.

Thanks in advance.

JA.

**Comment by tchapi** [comment]
Hi

This behaviour has been kind of introduced by https://github.com/jsonform/jsonform/issues/233. I think that https://github.com/jsonform/jsonform/commit/08eb83f40ac016c1b6161d49d83a724bf4487908 fixes that, making sure that we always look at children of the current node before collapsing an expandable item.

Let me know if that works for you
Thanks !

**Comment by TheJosean** [comment]
Hi,

Now works perfect, thank you very much @tchapi for your time and work on this.

JA.
