### ISSUE TITLE
Field Dependencies

### ISSUE THREAD

**Issue by LokeshBabuTG** [jsonform/jsonform#296]
Is it possible to add field dependencies like populating, adding, or removing field (or even changing values) depending on the selection of another field?

**Comment by tchapi** [comment]
Hi @LokeshBabuTG 

Do you mean something like https://jsonform.github.io/jsonform/playground/index.html?example=fields-selectfieldset ?

**Comment by LokeshBabuTG** [comment]
Yes it is.
