### ISSUE TITLE
JSON Form schema for creating JSON Form schemas

### ISSUE THREAD

**Issue by J-Setzer** [jsonform/jsonform#298]
Can anyone provide a JSON Form schema which can be used for creating another JSON Form schema? 

In my imagination I can **use JSON Form itself as a designer-tool for form-fields** with options like name, label, datatype, default values etc.. The export should be usable as schema for other forms. So users could use a form for building custom forms. The exported schemas could be stored in DB for example and the forms based on one of the exports could be opened up for (real) data-entry then. This could become quite generic.

You know what I mean? Sorry if my English is not sufficient to describe the idea well.

**Comment by tchapi** [comment]
Hi @J-Setzer and sorry for this late response

I think this could be possible, but then it's quite a different (and complementary) tool. I have no time to create such a thing but if you have the motivation to do so, I can then add you to the jsonform organization so we can put your repo under it
