### ISSUE TITLE
Cannot read property 'el' of undefined when imported via require

### ISSUE THREAD

**Issue by IonicaBizau** [jsonform/jsonform#300]
I am getting the following error when initializing the form:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/2864371/97667253-2d21db00-1a88-11eb-9b76-b36ba1faf642.png">

It seems `this` is undefined inside of the callback, due to not providing a `context` to the `_.each` function

**Comment by IonicaBizau** [comment]
Actually, I think #295 is about this, but not merged yet.

**Comment by tchapi** [comment]
#295 is now merged. Can you confirm that this resolves your issue ?

**Comment by IonicaBizau** [comment]
Yes, this is fixed now. Thank you very much!
