### ISSUE TITLE
Formatting based on array contents

### ISSUE THREAD

**Issue by mw777eds** [jsonform/jsonform#302]
Is there a way to use the data from an array to format the fields.  For example, a specific array has a boolean property of "disabled" can this be used to disable specific entries?  How would that be set up?

**Comment by tchapi** [comment]
Hi @mw777eds and sorry for the late response

You can "construct" the JSON schema object with these values before feeding them to jsonForm for instance, but maybe I misunderstood your request ?

**Comment by mw777eds** [comment]
Actually this relates to an array.  So all of the form elements in the array should not be disabled but only ones that have specific values for example.  So it depends on the data passed not the form.  But the form determines the class with the "htmlClass".  Again, this is within an array of items.

**Comment by tchapi** [comment]
Hmm, I see. To date, this is not possible in a straightforward way. You could bind change events on your inputs and trigger a rebuild of the form, maybe?
