### ISSUE TITLE
How to do server side validation of values?

### ISSUE THREAD

**Issue by bluepuma77** [jsonform/jsonform#304]
Hi,

thanks for providing this library and keeping it updated even after 8 years! 

One question I have is about data security and avoiding tampering. If a bad actor really wants to mess with my site, they can modify the schema on client side and submit invalid data. 

How would I validate the data again the schema on the server side in NodeJS? Can this be done with `deps/opt/jsv.js` or would I use another library like [ajv](https://github.com/ajv-validator/ajv) or dormant [jsv](https://github.com/garycourt/JSV)?

Thanks,
bluepuma

**Comment by tchapi** [comment]
Hi @bluepuma77 

You can use any library you like but ajv seems more up to date so I would rather go along with that

**Comment by bluepuma77** [comment]
[ajv](https://github.com/ajv-validator/ajv) seems not to be 100% compatible with the JSON format :-/

"`schema is invalid: data/properties/name/required should be array`"

Is there a way to run `jsonform` on the server side with the JSON schema and data?

**Comment by tchapi** [comment]
Arf. I haven't tested server-side, but I guess there are going to be several problems because it's expecting to be in a browser and have access to `window`.

**Comment by bluepuma77** [comment]
In 2014 Fabian looked at [validation in JSON Form](http://fabian-kostadinov.github.io/2014/09/22/validation-in-jsonform/). I looked into the code again, the whole validation part is done by `JSONFormValidator` from file [jsv.js](https://github.com/jsonform/jsonform/blob/master/deps/opt/jsv.js). I tested it and the validation part can be used easily on the server-side in NodeJS:

```
const jsv = require('../../static/js/jsv'); # adapt your local path
let validator = jsv.JSONFormValidator.createEnvironment("json-schema-draft-03");

let values = JSON.parse(req.body.json);
let schema = { properties: full_jsonform_definition.schema };
let v = validator.validate(values, schema);
console.log(v.errors)
```
Example result:
```
[
  {
    uri: 'urn:uuid:ed8924e5-df71-4b9e-9240-e972d528c023#/zip',
    schemaUri: 'urn:uuid:782a6bc6-29b4-49b5-a2fa-7ed6261f61c3#/properties/zip',
    attribute: 'type',
    message: 'Instance is not a required type',
    details: [ 'integer' ]
  },
  {
    uri: 'urn:uuid:ed8924e5-df71-4b9e-9240-e972d528c023#/zip',
    schemaUri: 'urn:uuid:782a6bc6-29b4-49b5-a2fa-7ed6261f61c3#/properties/zip',
    attribute: 'maxLength',
    message: 'String is greater then the required maximum length',
    details: 5
  }
]
```

An interesting next step would be to transform the submitted values from String into the right type (e.g. integer, date).
