### ISSUE TITLE
jQuery.ui.sortable not working

### ISSUE THREAD

**Issue by SteveG3R** [jsonform/jsonform#309]
Hello,

I cant get the sortable function to work for my example. See following plnkr for a working example: https://plnkr.co/edit/cYVEf4K4vE3whB6g?preview

Trying to drag the items will result in a console error `Uncaught TypeError: Cannot read property 'msie' of undefined`

Am I doing something wrong? Other than that I love this library, as I was building a expandable form with nested arrays before myself 👍

**Comment by tchapi** [comment]
Hi @SteveG3R 

You can try this example: https://jsonform.github.io/jsonform/playground/index.html?example=templating-idx and look at the playground page code to see how it is done. you might be missing a dependency somewhere

BR

**Comment by SteveG3R** [comment]
Hello @tchapi ,

any idea what that could be as I followed the Documentation and implemented all Files.

Apart from the default that got listed here: https://github.com/jsonform/jsonform/wiki#getting-started

- deps/jquery.min.js
- deps/underscore.js
- deps/opt/jsv.js
- lib/jsonform.js

I added the ones that got listed here: https://github.com/jsonform/jsonform/wiki#dealing-with-arrays

- deps/opt/jquery.ui.core.js
- deps/opt/jquery.ui.widget.js
- deps/opt/jquery.ui.mouse.js
- deps/opt/jquery.ui.sortable.js

I updated the plnkr (https://plnkr.co/edit/cYVEf4K4vE3whB6g) with your mentioned playground page. It is the same form now but is still not working with the same error.

![image](https://user-images.githubusercontent.com/27893204/103566169-cecb0b80-4ec1-11eb-9151-b6e5e3f9390e.png)

Sorry to bother again, but any Idea? The Documentation does not state to implement any other library.

**Comment by tchapi** [comment]
I think jQuery UI sortable needs more than these dependencies. You should include the whole jquery-ui package (like in the playground).

Keep me posted if that works

**Comment by SteveG3R** [comment]
Got it working with the JS File `jquery-ui.js`

Removed all the mentioned JS Files from https://github.com/jsonform/jsonform/wiki#dealing-with-arrays

- deps/opt/jquery.ui.core.js
- deps/opt/jquery.ui.widget.js
- deps/opt/jquery.ui.mouse.js
- deps/opt/jquery.ui.sortable.js

Probably should update the documentation with that information since you dont need these.

**Comment by tchapi** [comment]
I have updated the documentation — thanks !
