### ISSUE TITLE
Styling the addmore/deletelast buttons

### ISSUE THREAD

**Issue by SteveG3R** [jsonform/jsonform#311]
Hello,

is it possible to style the addmore/deletelast buttons when using arrays? I could not find any information about this in the Documentation.

![image](https://user-images.githubusercontent.com/27893204/103913433-cfa1ae80-5108-11eb-8972-445ee71f8682.png)

<hr>

An additional problem I had with using the sortable function is the following:

![image](https://user-images.githubusercontent.com/27893204/103913555-f233c780-5108-11eb-8a24-df447cf52072.png)

As you can see the sortable function adds another css layer i can not influence?! The result is this funky look.

**Comment by tchapi** [comment]
Hi @SteveG3R 

The markup is pure Bootstrap, so you can easily change it with custom CSS. Jsonform in itself does not add specific CSS over Bootstrap's own, and you are right that in some cases, the default styles are not adapted (_Bootstrap form elements are not meant to be sorted hence the funky look here_)
