### ISSUE TITLE
Number converted to string when the form is submitted

### ISSUE THREAD

**Issue by joelguittet** [jsonform/jsonform#313]
Hello,

I'm playing with the example at the same time developing my own application, and first I would like to say thanks a lot for this library !

I have notice a bug when a form is submitted: numbers are converted to strings.

For example logging the "values" object when submit is performed:

```
 { name: 'joel', age: '34', gender: 'alien' }
```

The quote around the 34 value should not be there :) Age is defined as a "number" in my schema.

Joel

**Comment by tchapi** [comment]
Hello Joel

Numbers are not converted to string, at least not on modern browsers that support the `type="number"` input.

Have a look in the playground: https://jsonform.github.io/jsonform/playground/index.html?example=schema-morecomplex

BR

**Comment by joelguittet** [comment]
Hello @tchapi 

Thanks for the quick reply. Double checked what I was doing in my app and found what was wrong. I was using a form defined with:

```
<form id="myform" action="/url" method="POST"></form>
```

And without using "onSubmit" callback.

Maybe you can indicate in the wiki it's mandatory to use onSubmit to avoid unwanted behavior.

Thanks for the help.
Joel
