### ISSUE TITLE
Some empty field types pass "Required" validation. Specifically date, custom fields, and possibly others

### ISSUE THREAD

**Issue by nextonphotos** [jsonform/jsonform#316]
Hi, I've run into an issue that I can't figure out.

I made a custom field that looks like the built in select field, but adds an Other option.  When the Other option is selected, it displays a text field for the user to specify.  That text field is the actual field used for the data and is just hidden or shown by the select field.  The select field just sets the text box value onChange.

Here is the code for the field (largely copied from jsonform.js): 
```javascript
JSONForm.fieldTypes['selectOther'] = {
        'template':`<select onChange="$('#<%= id %>').val((this.value != 'Other')?this.value:''); $('#<%= id %>').toggle(this.value == 'Other'); $('#<%= id %>').focus();"` +
            'class=\'form-control<%= (fieldHtmlClass ? " " + fieldHtmlClass : "") %>\'' +
            '<%= (node.schemaElement && node.schemaElement.disabled? " disabled" : "")%>' +
            '> ' +
            '<% node.schemaElement.selectOptions.push("Other") %>' +
            '<% _.each(node.schemaElement.selectOptions, function(key, val) { if(key instanceof Object) { if (value === key.value) { %> <option selected value="<%= key.value %>"><%= key.title %></option> <% } else { %> <option value="<%= key.value %>"><%= key.title %></option> <% }} else { if (value === key) { %> <option selected value="<%= key %>"><%= key %></option> <% } else { %><option value="<%= key %>"><%= key %></option> <% }}}); %> ' +
            '</select>' +
            '<input type="text" ' +
            'class=\'form-control<%= (fieldHtmlClass ? " " + fieldHtmlClass : "") %>\'' +
            'name="<%= node.name %>" value="<%= escape(value) %>" id="<%= id %>"' +
            'title="Please Specify"' +
            '<%= (node.disabled? " disabled" : "")%>' +
            '<%= (node.readOnly ? " readonly=\'readonly\'" : "") %>' +
            '<%= (node.schemaElement && (node.schemaElement.step > 0 || node.schemaElement.step == "any") ? " step=\'" + node.schemaElement.step + "\'" : "") %>' +
            '<%= (node.schemaElement && node.schemaElement.maxLength ? " maxlength=\'" + node.schemaElement.maxLength + "\'" : "") %>' +
            '<%= (node.schemaElement && node.schemaElement.required && (node.schemaElement.type !== "boolean") ? " required=\'required\'" : "") %>' +
            '<%= (node.placeholder? " placeholder=" + \'"\' + escape(node.placeholder) + \'"\' : "")%>' +
            ' />',
        'fieldtemplate': true,
        'inputfield': true,
        'onInsert':function (evt, node) {
            let selectNode = $(node.el).find('select');
            let inputNode = $(node.el).find('input');

            //Initialize the textbox to the value of the select box
            if(!inputNode.val()) {
                inputNode.val(selectNode.val());
            }

            //If the text box is set to something that isn't in the select options, set select to Other
            if (selectNode.find(`option[value="${inputNode.val()}"]`).length === 0){
                selectNode.val('Other');
            }

            //Show the text box if the select option is Other and hide otherwise
            $(inputNode).toggle(selectNode.val() == 'Other');
        }
    };
```

And here is how I add it to the schema:
```javascript
"platform": {
    "type": "selectOther",
    "title": "Platform",
    "selectOptions": ["Phone","Email","In-Person","Facebook","Instagram","LinkedIn"],
    "required": true
}
```

My problem is that when the form is submitted, the field doesn't behave as if it is actually required.  What I want to happen is if a user selects Other but doesn't actually fill the textbox, then they will get a validation error stating that the box is required when they try to submit.  Any ideas on what I'm missing to make this work properly?

Thanks!

**Comment by tchapi** [comment]
Hi @nextonphotos 

In the generated DOM, is the `required` attribute correctly set ?

**Comment by nextonphotos** [comment]
It looks like it is correctly set, unless I'm missing something.  Here is the generated html when Other has been selected in the select box:

```javascript
<div class="form-group jsonform-error-platform jsonform-required">
   <label for="jsonform-1-elt-platform">Platform</label>
   <div class="controls">
      <select onchange="$('#jsonform-1-elt-platform').val((this.value != 'Other')?this.value:''); $('#jsonform-1-elt-platform').toggle(this.value == 'Other'); $('#jsonform-1-elt-platform').focus();" class="form-control">
         <option value="Phone">Phone</option>
         <option value="Email">Email</option>
         <option value="In-Person">In-Person</option>
         <option value="Facebook">Facebook</option>
         <option value="Instagram">Instagram</option>
         <option value="LinkedIn">LinkedIn</option>
         <option value="Other">Other</option>
      </select>
      <input type="text" class="form-control" name="platform" value="" id="jsonform-1-elt-platform" title="Please Specify" required="required" style=""><span class="help-block jsonform-errortext" style="display:none;"></span>
   </div>
</div>
```

**Comment by tchapi** [comment]
Maybe you need to add a Bootstrap class too to add the required behavior ?

**Comment by nextonphotos** [comment]
What class would you suggest? The red asterisk currently appears on the field and other normal text fields in the save form work properly with both the asterisk and the validation message if left blank.  There's just something about this custom field that isn't working.

I can roll my own validation for the field to force it to work, but I'd like to figure out why it doesn't work with the built in validation.

**Comment by tchapi** [comment]
The "required" behaviour (having a little popup that says that you must fill this field) is standard HTML validation, triggered only by the `required` attribute on the form, nothing else .. so I'm not sure what is the culprit here to be honest.

**Comment by nextonphotos** [comment]
Ok, I finally had a chance to revisit this. I've figured out what the problem is.

When an item is selected in in the dropdown, my code automatically sets the value of the hidden text field to match unless "Other" is selected.  In that case the textbox value is set to "", or null, and shown. 

The reason validation is passing the field despite the required flag seems to be that the jsonFormValue object that is passed to validation actually contains a "" value for the field, which apparently satisfies the required condition, even though I don't think it should.

I'm not sure where the best spot to fix this would be.  One option is checking the jsonFormValue object for any items set to "" prior to validation and deleting them from the object.  This seems to work, though I don't know if it would break other things. It also feels pretty hacky.

I can also add a pattern, like ".{1,}", to all of the custom fields to enforce validation.  This also works, but also doesn't seem like it should be necessary.

Any ideas about how I should go about fixing this properly?

**Comment by nextonphotos** [comment]
It seems that line 2544 of jsonform.js is where this issue is handled for the built-in string types.  If I add my custom type into this if statement, that also fixes the problem.  I'd rather have a solution that doesn't require me to change the library's code, however.

Thanks for any guidance you can provide!

**Comment by nextonphotos** [comment]
This same issue happens with required type date fields as well.  This is just using the built in HTML5 date field, but it results in an empty string being sent to the validator, which satisfies the required constraint and passes.

This seems to be fixed by changing line 2544's (eltSchema.type === 'string') to (eltSchema.type === 'string' || eltSchema.type === 'date')

I suspect other built in field types may also display this behavior, along with any custom fields like the one discussed above.

**Comment by sdetweil** [comment]
@nextonphotos  "If I add my custom type i"

in your tyes view do you provide the onSumbit()  handler 
```
from my custom type with a hidden field too )

```
onSubmit: function(evt, elt){
    let left_value = 0
    // get the value of the left field
    left_value=$(elt.el).find('#'+LeftID).val()
   // console.log( "value="+y)
   // it can't be empty
    if(left_value==emptyString){
      alert("definition for "+elt.el.firstChild.innerText+" cannot be empty")
    }
    return left_value!==emptyString
  },
```

mine is two fields; sidebyside
the left one (key on an object) MUST not be null 
my types onchange handler copies left and right together into the hidden field
```
$(node.el).change(function (element) {
}
```

**Comment by tchapi** [comment]
Hi @nextonphotos 

Sorry for the delay. I've tested and to me, the field has the correct behaviour (I used your code from this issue):

![Screenshot 2021-05-07 at 14 05 07](https://user-images.githubusercontent.com/1944007/117447117-5e9ac800-af3d-11eb-8b95-4f5ec8080054.png)

If I select "Other" and don't fill in something, the form does not validate and the browser shows the little error popup.

Am I missing something ?
