### ISSUE TITLE
Custom attributes in html inputs

### ISSUE THREAD

**Issue by Hiweus** [jsonform/jsonform#317]
**Hi**, i have run into an issue that i can't figure out.

I wold like to put some custom attributes in the html inputs how can i do that ?

like below.

```html
<input name="name" custom-field="my-value" />
```

I already tried some things.

```json
{
  "schema": {
    "name": {
      "title": "Name",
      "description": "Nickname allowed",
      "type": "string",
      "custom-field": "my-value",
      "properties": {
        "custom-field": "my-value"
      },
      "htmlMetaData": {
        "custom-field": "my-value"
      },
      "fieldHtmlCustomField": "my-value"
    }
  }
}
```

And none of these properties had appended to my html input.

![image](https://user-images.githubusercontent.com/45133420/107637944-ac10dd00-6c4d-11eb-802c-e13d1808a9da.png)

Any ideas about what is missing for work properly ?

Thanks!

**Comment by tchapi** [comment]
See https://jsonform.github.io/jsonform/playground/index.html?example=fields-common — You need to put this on the form, not the schema
