### ISSUE TITLE
selectfieldset & checkboxes

### ISSUE THREAD

**Issue by mrszmoline** [jsonform/jsonform#318]
Hello!

I am wanting to implement the same functionality that selectfieldset provides, but with multiple select checkboxes instead of a dropdown. 

Is there any way to do this?

Thanks

**Comment by tchapi** [comment]
Hi @mrszmoline 

No, `selectfieldset` is the only "alternative" form input that we have right now.

But you can totally use an array of checkboxes, and show/hide parts of the form based on the value of the array, for instance.
