### ISSUE TITLE
Can you build hierachy?

### ISSUE THREAD

**Issue by Norberg95** [jsonform/jsonform#319]
Let's say we have a `Person `object with three fields `name `, `age `and `children ` The `children` contains an array of `Person `objects. So you can have childs and child's childs and so on. So the user could build an entire family tree and with as many levels as he wants.
Is it possible with jsonform?

**Comment by tchapi** [comment]
Hi

jsonform is about having a specific schema turned into a functional form, so infinite recursion is not really meant to work per se, but I guess you can make it work if you really want to. Not sure that's the best tool for it though, TBH.

**Comment by Norberg95** [comment]
Thank you for the response. I thought about it a bit more and I am planning to integrate `jsTree` and `jsonform` to get the desired functionality.
