### ISSUE TITLE
Please add a CDN and Playground link

### ISSUE THREAD

**Issue by PythonLinks** [jsonform/jsonform#322]
Hello.  I have been trying and rejecting various JSON Schema Form libraries.  Hopefully my journey ends here.  it looks like you do nested, Ace and RTF editors, and validation errors bubble up to the tabs.  You even let me change the layout and add in html snippets. Perfect.  
You may want to mention the cdn I found here:
https://www.jsdelivr.com/package/npm/jsonform
And the live playground I found here:
https://ulion.github.io/jsonform/playground/

If any newbie is curious why I rejected the other competitors, here are my experiences with other tools. 
https://forestwiki.com/json-schema-form-generators
You are welcome to a copy of that page.  I always think that it is useful for open source projects to compare themselves with the other platforms.   People could start with that page and update it.

In particular, I think one needs a good base class, and maybe your base class is better than all of the others. 

I am hoping that this is the last JSON Schema Form library which I have to evaluate. 
Wish me luck.

**Comment by tchapi** [comment]
Hello @PythonLinks 

The playground link is on the home page of this repo, in the "About" section: https://jsonform.github.io/jsonform/playground/index.html

And the npm link is indicated in the badges on the README file. Various CDN pull the content of the NPM public repository, so you may want to use jsdelivr if you wish

Good luck !
