### ISSUE TITLE
WYSIHTML5 Demo Please

### ISSUE THREAD

**Issue by PythonLinks** [jsonform/jsonform#323]
First thanks for a great library.  This is the only one I have seen with documentation on the underlying model.  

I am not able to get WYSIHTML5 working. 
I am not able to find a demo in your playground. 
The code for it in index has been commented out. 
https://github.com/jsonform/jsonform/blob/08eb83f40ac016c1b6161d49d83a724bf4487908/tests/index.html

Does it still work?  Maybe what I need to do is fire up the tests.  

In other comments, I almost dropped this because I could not find tabs, without arrays.  Finally I spotted them in your playground.  You may want to mentoin them in the documentation. 

If anyone is curious about my misadventures with choosing a JSON Schema library, you can read more here. 
https://forestwiki.com/json-schema-form-generators

**Comment by tchapi** [comment]
Hello

Yes it does work, see https://github.com/jsonform/jsonform/commit/6e0dc3ad560a4d887c2766f3998755fe6561b585
I added the missing example in the playground.

Best !

**Comment by tchapi** [comment]
https://jsonform.github.io/jsonform/playground/index.html?example=fields-wysihtml5

**Comment by PythonLinks** [comment]
Thank you for the fast service.   
I think that this is my favorite library. 
I particularly like your idea of separating the form object from the JSON schema and data objects.  It allows me to decouple my server side data model from my presentation model.  Previously they were too bound together.  

I am still trying to understand all of his.  My instinct is that this is a better approach than the React or Vue solutions.  Your computational model is focused on client server, at the component level.  Vue or React are focussed on the browser at the language level.  In fact Vue applications are recommended to use Nuxt.js with client and server rendering, this approach is much cleaner, and simpler.   Closer to my world view.
