### ISSUE TITLE
Source code related to boostrap examples

### ISSUE THREAD

**Issue by tomitesh** [jsonform/jsonform#325]
Hi,

I am a developer and use the jsonForm library.

I am able to download below examples and source code.
https://github.com/jsonform/jsonform/tree/gh-pages/playground

but , i can not find the following example (which is under boostrap3 folder). could you please suggest where I can download these examples from. 

http://ulion.github.io/jsonform/playground/bootstrap3/?example=fields-checkbox#

The  dependencies code is not working for 1st url but it works for examples mentioned under boostrap3 folder but i can not see these folder on code download. could you please suggest.

"dependencies": {
      "flag": ["adultOnlyInfo"]
    }

**Comment by tchapi** [comment]
You are looking at the fork of @ulion so you need to search in the fork to find the example you're looking for: https://github.com/ulion/jsonform

**Comment by tomitesh** [comment]
Thank you. my bad....
