### ISSUE TITLE
How to layout fields horizontally?

### ISSUE THREAD

**Issue by toddwh50** [jsonform/jsonform#332]
Is there a way to lay out fields horizontally (i.e. put FirstName and LastName on the same row)? I have forms with a lot of fields and doing them all vertically makes for a LOT of scrolling.

I've tried adding bootstrap classes to htmlClass to force narrower grid-sizes (ex. col-4) for for field containers and but they don't seem to affect the layout.

**Comment by tchapi** [comment]
I think you have to create ad hoc classes + your custom CSS if you want to change the form layout. The best way would be to create object types in the schema (that would translate to fieldsets) and then style these fieldsets as you like (with flexbox for instance)

**Comment by toddwh50** [comment]
Thanks - I was able to do as you suggested but had to also apply "display:inline-block" to the field container to allow them to flow side by side (using bootstrap grid layout classes in my case).
