### ISSUE TITLE
valueInLegend array NOT tabArray, producing weird results

### ISSUE THREAD

**Issue by sdetweil** [jsonform/jsonform#343]
I have a field that is an array of objects.(presented as an array, NOT a tabarray)  I want the user to be able to label the entry, and do it live, like tabarray

so I have a string field, valueinlegend=true
schema 
```
    "MyCovid19": {
      "type": "array",
      "items": {
        "type": "object",
        "title": "properties for MyCovid19",
        "properties": {
          "label": {
            "type": "string",
            "title": "label"
          } 
```
form
```
            {
              "type": "fieldset",
              "title": "MyCovid19",
              "expandable": true,
              "items": [
                {
                  "type": "array",
                  "draggable": false,
                  "items": [
                    {
                      "type": "fieldset",
                      "legend": "{{value}}",
                      "expandable": true,
                      "items": [
                        {
                          "key": "MyCovid19[0].label",
                          "valueInLegend": true
                        } 
```
but it gets presented with all this whitespace behind it 
![Screenshot at 2021-05-19 10-44-09](https://user-images.githubusercontent.com/1498142/118842929-355c2f00-b88f-11eb-8b15-6e80cc4f2abf.png)

and the generated html content
![Screenshot at 2021-05-19 10-48-02](https://user-images.githubusercontent.com/1498142/118843551-c9c69180-b88f-11eb-82b6-2d2e65bff4f6.png)

it LOOKS like it generates a li for each character in the legend value

**Comment by sdetweil** [comment]
adding an onKeyUp handler allows me to adjust the legend live..

**Comment by sdetweil** [comment]
after looking at this for a while,  the 'problem' is that the code that does the array offset adjustment ([] to [0], [1]...)
gets returned  a string which is the leaf node (an enum in my case) , and it uses THAT 'string' as the 'array... 
but its only 1 string.. 

```
formNode.prototype.getPreviousNumberOfItems = function (values, arrayPath) {
  var key = null;
  var arrayValue = null;
  var childNumbers = null;
  var idx = 0;

  if (!values) {
    // No previously submitted values, no need to go any further
    return 0;
  }

  if (this.view.inputfield && this.schemaElement) {
    // Case 1: node is a simple input field that links to a key in the schema.
    // The schema key looks typically like:
    //  foo.bar[].baz.toto[].truc[].bidule
    // The goal is to apply the array path and truncate the key to the last
    // array we're interested in, e.g. with an arrayPath [4, 2]:
    //  foo.bar[4].baz.toto[2]
    key = truncateToArrayDepth(this.formElement.key, arrayPath.length);
    key = applyArrayPath(key, arrayPath);
    arrayValue = jsonform.util.getObjKey(values, key);
    if(typeof arrayValue ==='string')   // if this is a string
      return 1;                                     // return the size count as 1
```

i really think truncateToArrayDepth has returned the wrong key parent[].leafmost_child, with arrayPath["1"]
applyArraypath does its job,  and returns
parent[1].leafmost_child
and then getObjKey() does its thing and returns the value of that field.. which is NOT an array..(well it IS, but not in the context being used here)...

before this I could make 100 tabs show up, or none.. depending on the contents of the leafmost_child field.  in this case, whatever was in the enum list

**Comment by tchapi** [comment]
Hi

`valueInLegend` is not supposed to work with the `array` type, so I don't really understand how #351 fixes that TBH.

**Comment by sdetweil** [comment]
here is an example. its not the array type, its a string IN the array type 
[weird_array items.json.txt](https://github.com/jsonform/jsonform/files/6578459/weird_array.items.json.txt)
![Screenshot at 2021-06-01 12-54-01](https://user-images.githubusercontent.com/1498142/120369373-c6dc8f80-c2d8-11eb-944b-e187867df9ab.png)

**Comment by tchapi** [comment]
I still don't really get what you are trying to achieve. The following schema that you provided (I simplified and removed the fieldset) doesn't work since `valueInLegend` is not available for the `array` type, so your `{{value}}` placeholder is not used when "live editing":

```json
{
    "schema": {
        "MyCovid19": {
            "type": "array",
            "items": {
                "type": "object",
                "title": "properties for MyCovid19",
                "properties": {
                    "label": {
                        "type": "string",
                        "title": "label"
                    }
                }
            }
        }
    },
    "form": [{
        "type": "array",
        "items": [
        {
            "type": "fieldset",
            "legend": "value is: {{ value }}",
            "expandable": true,
            "items": [
                {
                    "key": "MyCovid19[0].label",
                    "valueInLegend": true
                } 
            ]
        }
      ]
    }]
}
```
Moreover, you're referencing `MyCovid19[0].label` in your key, which cannot be expanded by JSONForm. What you want is rather something like this:

```json
{
    "schema": {
        "MyCovid19": {
            "type": "array",
            "items": {
                "type": "object",
                "title": "properties for MyCovid19",
                "properties": {
                    "label": {
                        "type": "string",
                        "title": "label"
                    }
                }
            }
        }
    },
    "form": [{
        "type": "tabarray",
        "items": [
        {
            "type": "fieldset",
            "legend": "value is: {{ value }}",
            "items": [
                {
                    "key": "MyCovid19[].label",
                    "valueInLegend": true
                } 
            ]
        }
      ]
    }],
    "value": {
        "MyCovid19": [{
            "label": "testing"
        },{
            "label": "other"
        }]
    }
}
```

Notice that:

  1. We use  `MyCovid19[].label` as the key
  2. The values are separated: we have one object for each value (since it's an array)

The result is :

![Screenshot 2021-06-01 at 21 14 08](https://user-images.githubusercontent.com/1944007/120378152-58babb80-c31e-11eb-95ee-a47a60299daa.png)

... which looks pretty much correct (but it's a `tabarray`, not an `array`).

Does it make more sense ?

PS: Making the "live value editing" work on `array` just as `tabarray` does should be feasible I think, I will have a look

**Comment by sdetweil** [comment]
yes, You'll see that I mentioned the [0] in my original posts,
but mistake shouldnt cause garbage..   
I would have accepted an error 

my fix fixes that

live edit doesn't work.. I had to add an onKeyUp handler
