### ISSUE TITLE
Offset column not working 

### ISSUE THREAD

**Issue by Lakhwinder00** [jsonform/jsonform#345]

**Comment by sdetweil** [comment]
could u explain with more detail.. I don't know what offset column means

**Comment by Lakhwinder00** [comment]
Spouse, I have one row in the container but I want should textbox place on the right side. I have faced some issue with  move columns to the right using .offset-md-* classes

**Comment by tchapi** [comment]
Closing for now as it seems to be bootstrap related (and not properly detailed anyway with a reproducible example, etc)
