### ISSUE TITLE
need to select tabarray label string in CSS

### ISSUE THREAD

**Issue by sdetweil** [jsonform/jsonform#354]
in my form design, I have a list of items, some support multiple of the same type, some not, some have one entry, some more

the tab label of 'Item 1'  doesn't mean anything and is confusing. I would like to hide it. (the tab label)

but CSS doesn't provide a selector for  the contents of an element, only for the value of an attribute
(:has() selector has been approved, but not yet implemented in any browser)
the generated tab label code is 
```
<a class="draggable tab" data-toggle="tab">Item 1</a>
```
IF there was an attribute, then it could be selected, like this
```
<a class="draggable tab" data-toggle="tab" val="Item 1">Item 1</a>
```

would u be interested in this change? 

my tab array 
if one tab and val='Item 1'
no tab shows 
![Screenshot at 2021-05-24 11-42-32](https://user-images.githubusercontent.com/1498142/119379521-332a1400-bc85-11eb-83ee-e6e330ee3fbd.png)

in one item with one tab val NOT default 'Item 1'
![Screenshot at 2021-05-24 11-42-32](https://user-images.githubusercontent.com/1498142/119379580-46d57a80-bc85-11eb-99ba-797e60e8caea.png)

if more than one tab
![Screenshot at 2021-05-24 11-42-40](https://user-images.githubusercontent.com/1498142/119379703-6c628400-bc85-11eb-8094-471fdc4ce948.png)

**Comment by sdetweil** [comment]
then u can target the a item like this 
```
.possibly-hidden-tab div:nth-child(2)  > div > div >div >ul >li:only-child >a[val*="Item 1"] {
  display: none;
}
```

**Comment by tchapi** [comment]
Hi @sdetweil,

Yes, I think that change is meaningful. Let me try to give it a go this week, I'll keep you updated

**Comment by sdetweil** [comment]
I will submit a pr

**Comment by sdetweil** [comment]
thank you
