### ISSUE TITLE
Display one field depending of values from other field

### ISSUE THREAD

**Issue by joelguittet** [jsonform/jsonform#359]
Hello,

I would like to have one field that is hidden depending of the value from another field.

Basically the 2 fields are titleMap enum strings. I would like the second one to be hidden depending of the values selected in the first one.

I have seen this is very similar to this question: https://github.com/jsonform/jsonform/issues/312. But the solution proposed was to use events. Is it suitable in all cases ? I mean, when the form is loaded with default values, what about the events and thus what about the display of the second field if the user doesn't change the value of the first field?

Thanks,

Joel

**Comment by sdetweil** [comment]
use selectfieldset  then based on the enum, u can expose different other fields

**Comment by joelguittet** [comment]
selectfieldset is very similar from what I have seen on https://jsonform.github.io/jsonform/playground/index.html?example=fields-selectfieldset, but two questions:
- is it possible to have the selection field value in the output submitted? On the above example this is just a "make  choice" selection, and it's of part of the output when the submit button is pressed.
- in the above example, the selection display one field or another one (text / category). What about "one field or no field at all" ? i.e. my selection field will be "Disable / Enable" and I need to show one field when the selection field is "Enable".
- 
Thanks
Joel

**Comment by sdetweil** [comment]
i think u have to be tricky... 

show the second field, but have it hidden.

I haven't tried no fields as a choice result

**Comment by sdetweil** [comment]
I was able to setup a selectFieldset to show a structure, a field and nothing 

```
{
  "schema":{
		"somefile":{
			"type":"object",
			"properties":{
				"name":{
					"type":"string"
				},
				"address":{
					"type":"string"
				}
			}
		},
		"location":{
			"type":"string",
			"enum":[
				"first",
				"second",
				"third"
			]
		},
		"freddy":{
			"type":"boolean"
		}
	},
 	"form": [
	    {
	      "type": "selectfieldset",
	      "title": "Make a choice",
	      "key": "location",
	      "titleMap": {
	        "first": "Search by text",
	        "second": "Search by category",
          "third":"fribble"
	      },
        "items": [
	        "somefile",
          "freddy",
          ""                                        <--- show nothing  erase this comment before pasting into playground
	      ]        
	    }
  ]	
}
```

**Comment by joelguittet** [comment]
Hello @sdetweil 

Impressive ! I was trying some config but haven't realized the solution was just to set item "" !!
I have done the "" item at the first position, working as well, and my "freddy" item is itself a titleMap because it's also an enum string, working like a charm !

Thanks for the help!

Joel

**Comment by sdetweil** [comment]
I didn't know either, just trying it to learn..
