### ISSUE TITLE
Way to get form values without onSubmit?

### ISSUE THREAD

**Issue by enikok** [jsonform/jsonform#363]
hi !
I am trying to build JsonForm by sending schema from the server to client. I cannot use templating because I don't know before hand which schema to use. but once user selects some options, I do AJAX calll to the server and retrieve schema, e.g. 
        dataType: 'json',
        success: function (data) {
            const my_schema = JSON.parse(data.schema_str);
            $('#featureAttribs').jsonForm( my_schema );
        }

this works fine, but I also need to save values, so that I can populate form later. Only way I know so far is to extract all values from POST at server side, then form values.  But it would be great if I could call something like getFormValue before POST and then send values inside the post and avoid parsing at server ser.

is getFormValue() official API?  I did not see it the wiki docs.

I could not also use onSubmit callback (which supplies values), because i could not pass function definition in Json format.

I tried also 

        dataType: 'json',
        success: function (data) {
            const my_schema = JSON.parse(data.schema_str);

            my_schema["onSubmit"] = "function (errors, values) { alert(\"Hello\"); return onJsonFormSubmission(errors, values);  }";

            $('#featureAttribs').jsonForm( my_schema );
        }

but callback never gets called. I can guess that JsonForm extracts function part and then parses schema.

**Comment by enikok** [comment]
started reading JsonForm source code....(in lib/jsonform.js) and in the end it has:

/**
 * Retrieves the structured values object generated from the values
 * entered by the user and the data schema that gave birth to the form.
 *
 * Defined as a jQuery function that typically needs to be applied to
 * a <form> element whose content has previously been generated by a
 * call to "jsonForm".
 *
 * Unless explicitly disabled, the values are automatically validated
 * against the constraints expressed in the schema.
 *
 * @function
 * @return {Object} Structured values object that matches the user inputs
 *  and the data schema.
 */
$.fn.jsonFormValue = function() {
  return jsonform.getFormValue(this);
};

I am new to Javascript (I have first learned Javascript literally 2 weeks ago), can someone please show me how I am supposed to call this function?
comments suggest, I call this in the following way:

    var attributes_as_json = $('#featureAttribs').getFormValue();
      //var attributes_as_json = myJsonForm.getFormValue();      <--- here I attempted to save return from JsonForm and use that.
    console.log(attributes_as_json);

this did not work, nothing happens and browser gets wobbly (I have to restart it, because debugging stops working).

so I could use only this
    var attributes_as_json = $('#featureAttribForm :input').serialize();
this works, but I need obtain structured json, which I can send to server, save, and then I can re-use it by passing as "values" back to JsonForm when user needs to edit.

continuing reading source code....

**Comment by enikok** [comment]
ok... I found answer to one of questions I had.   JsonForm accepts Javascript object, not pure Json.  that is why, it is possible to add "function objects" (and thus specify onSubmit function). I still don't understand though, why the following is not working:

          var my_schema = JSON.parse(data.schema_str);   // <-- parse stringified Json from server

            // also add function callback

           my_schema["onSubmit"] = "function (errors, values) { alert(\"Hello\");  }";
           // or my_schema.onSubmit = "onJsonFormSubmission";

I think I lack knowledge of precize JS syntax or smth else in the way json object created.

**Comment by sdetweil** [comment]
because my_schema is a binary object now (after JSON parse), so adding a 'string' object is wrong...

u want
```
 my_schema["onSubmit"] = function (errors, values) { alert("Hello");  };
```

they give u a sample of the onsubmit ..

here is my client side, receiving the  text string of the json form (after stringify) 
I am using socket.io as the transport
```
activesocket.on("json", function (incoming_json) {
    // make it binary  (don't need the leading/trailing {}
    let data = parseData(incoming_json.slice(1, -1));
    // free the memory, my form is 12,000 lines
    incoming_json = null;

    // clear my form output message
    $("#outmessage").text("");
    try {
// add handle for submitValid  (all good, send data base to server 
      data.onSubmitValid = function (values) {
        activesocket.emit("saveConfig", values);
        $("#outmessage").html(
          "<p><strong>Your Configuration has been submitted.</strong></p>"
        );
      };
//  add handle for submit
      data.onSubmit = function (errors, values) {
        if (errors) {
          console.log("Validation errors 1", errors, values);
          let buildInner = "";
          errors.forEach(function (errItem) {
            let errSchemaUri = errItem.schemaUri
              .replace(/.+\/properties\//, "")
              .replace("/", " >> ");
            buildInner +=
              `<p><strong style="font-color:red">Error: ` +
              errItem.message +
              "</strong></br>Location: " +
              errSchemaUri +
              "</p>";
          });
          $("#outMsg").html(buildInner);
          console.log("Validation errors 2", values);
          return false;
        }
        return true;
      };
```

**Comment by sdetweil** [comment]
sorry, intended to add   JUST because there was a submit, does NOT mean u have to send back to the server..JSONFORM does not care.. u received the callback on onSubmit..

**Comment by enikok** [comment]
hi !  thanks a lot for your reply. this has brightened by my day. 

Yesterday, I gave up trying and change my design a bit:  on server side, introduced case-specific classes, which handle both "schema" and "parsing" of POST results, by cherry picking items (I added Json form inside more bigger, complex form, which allows to dynamically select cases and then I do AJAX call to fetch case-specific JsonForm schema from the server and then I insert result of JsonForm() call into <div> inside this outer form) - so I cherry pick and reconstruct "values" manually. Also considered using https://github.com/marioizquierdo/jquery.serializeJSON on client side.

but luckily, I have done all these design on paper only and have started implementation. 
Now I will try what you suggested. Thanks a lot for your help!

(and indeed, parsed Json is binary structure and adding "string" object would not work.  this did not occur to me at all).

**Comment by enikok** [comment]
hi again!

I tried this:

    var my_schema = JSON.parse(data.schema_str);   

  my_schema["onSubmit"] = function (errors, values)
   {
                alert("Hello");
    };


and then checked how content changes (in the debugger).  Indeed, as you said, function object is added:

Local
.....
my_schema:
form: (2) [{…}, {…}]
onSubmit: ƒ (errors, values)
arguments: null
caller: null
length: 2
name: ""
prototype: {constructor: ƒ}
__proto__: ƒ ()
[[FunctionLocation]]: feature_new:309
... . .....

so now for use, my_schema contains correct function signature.  But   this function is not getting called on form submission. 

(I first tried sample to see that in classic examples, onSubmit is called, so I know that my submit button works, etc.)

do you know, is there could be some other reason why JsonForm is not calling functions created this way?

in the example you gave (thanks for that too, btw), you call:

 _let data = parseData(incoming_json.slice(1, -1));_

in this, parseData, do you call JSON.parse() ?  that is, standard Json parse method?  I will try onSubmitValid now. may be it will work.

**Comment by enikok** [comment]
> sorry, intended to add JUST because there was a submit, does NOT mean u have to send back to the server..JSONFORM does not care.. u received the callback on onSubmit..

actually, I do send back to server too. I need to send values to server and persist there. and once it is there, I can later use "values" to display same form for editing purposes (e.g. user wants to edit configuration).

**Comment by sdetweil** [comment]
yes, the parse on the client side is just JSON.parse.   I have a exit that handles function defs in the form contents, so that is part of the parse.  and the reason I send text. as socket.io does stringify under the covers (without such an exit)

I can put a stop on the onsubmit functions in the browser and they stop after the user presses submit in the form. and I can examine the values raw data

data is the after parse binary JavaScript object, so adding another element into the object is easy.

I do have a submit button defined in the form

**Comment by enikok** [comment]
ok. thanks for confirming. 

Update from my side:   I got this callback working!

Reason why it was not working was:   I used <div> where I inserted output of JsonForm:


             var my_schema = JSON.parse(data.schema_str);
             my_schema.onSubmit = function (errors, values)
             {
                alert("Hello");
             };

            $('#featureAttribs').jsonForm( my_schema );  //   <- - - -  HERE featureAttribs is <div> inside HTML form.

When I replace last line with this

            $('#featureAttribForm').jsonForm( my_schema );  //   <- - - -  HERE featureAttribForm is <form> inside HTML form.

then my callback started working.

Conclusions:
1. JsonForm output can go to <div>, inside any form, but then function callbacks do not work
2. if we want onSubmit to work, JsonForm output must go to <form>

My guess is that JsonForm uses something from <form>, may be some jQuery method like this:

        $("#featureAttribForm").submit( function(eventObj)


Using (2) creates some inconvenience for me, because JsonForm messes up my form where I combine also other things, like JS managed inputs and also inputs from Django.  But I can live with this, by specifiying inputs in JsonForm schema (it will then have to repeat for each schema) and I can take out JS managed inputs outside of the form.


My HTML form looks like this:

    <form method="POST" class="post-form" id="featureAttribForm">
        {% csrf_token %}
        {{ form.as_p }}
        <p>&nbsp</p>
        <div id="featureAttribs"></div>

        <button type="submit" class="save btn btn-default" name="first_button" value="just-save">Save</button>
    </form>

**Comment by enikok** [comment]
sorry for typos, I have now corrected in all places.

**Comment by enikok** [comment]
I am about to close this ticket. should a new issue be created to address this?  for example, JsonForm can handle such cases, by looking at the parent of the div element?

**Comment by sdetweil** [comment]
in my html I have a div for the form 
and use jQuery to fill it in the JavaScript
```
$("#result").html('<form id="result-form" class="form-vertical"></form>');
      // insert the new form
      $("#result-form").jsonForm(data);
```
my project is here
https://github.com/sdetweil/MMM-Config

config.html and form-client.js
node_helper.js sends the form text
and processes the response

I am building a configuration form over a user composed set of extensions in a magic mirror application.

**Comment by enikok** [comment]
thanks a lot! I will familiarize myself more deeper with MMM-Config, I am sure it will help me to gain more insights and learn more.    

i see .... you have  a div with id="outmessage" and generate form inside it using JS.  That is, form is inside div.  and then you still call jsonForm(data) on this form:

 $("#result-form").jsonForm(data);  

in my case, it is other way around, there is a div was inside a form.   and then I  called jsonForm() on this div:

 $("#DIV_INSIDE_MY_FORM").jsonForm(data);  

and this did not work.   but this one works:

 $("#MY_FORM").jsonForm(data);  

and I think it works because JsonForm needs to call  $("#MY_FORM").submit( callback_function).

JsonForm library can be improved so that it checks and realizes that DIV_INSIDE_MY_FORM is not a form, and then looks up its parent MY_FORM before calling submit( callback_function).

I just did this now:

$("#featureAttribForm").submit( function(eventObj) {
  return true;
});

and it hits breakpoint. 

should I give a go and try to fix/improve in JsonLib?  do you think it is a good thing and pull request will be accepted ?

**Comment by sdetweil** [comment]
jsonform is going to generate the html that goes inside an html <form>
I construct this form field on the fly
$("#result").html('<form id="result-form" class="form-vertical"></form>');

and then  to use it here
for the jsonform generated output
$("#result-form").jsonForm(data)

yes my form is in a div.   I don't think jsonform should have to locate the right parent

**Comment by enikok** [comment]
yes, having thought second time - if really necessary, things can be put in right places without using div. ok, thanks a lot for all  the help you gave so far. I will close this issue not.
