### ISSUE TITLE
Bootstrap 5?

### ISSUE THREAD

**Issue by onlinesid** [jsonform/jsonform#364]
I'm wondering how hard would it be to make it output Bootstrap-5 html?

**Comment by tchapi** [comment]
Hi
I have no time to make this happen right now unfortunately, but I will gladly review a PR if you want to give it a go :)

**Comment by onlinesid** [comment]
I was considering making a PR and wondering how hard would it be, seems just adding another set of templates when I checked the code.

**Comment by onlinesid** [comment]
Looking at the code looks like we can just set the template variables.
