### ISSUE TITLE
is there a built in way to make a field next to a range slider that shows the value, with live-edit? 

### ISSUE THREAD

**Issue by sdetweil** [jsonform/jsonform#365]
one of my users wants to make a slide view like this 

This results in a ranging slider, like I'd like, but no number to indicate what it means.

![slider-none](https://user-images.githubusercontent.com/1498142/122567581-6d7d9b80-d00e-11eb-81c5-c52a25b28fb1.png)

I'd rather have something like

![slide-box](https://user-images.githubusercontent.com/1498142/122567612-75d5d680-d00e-11eb-858d-29f37641ff1f.png)

short of creating a custom field, is there a mechanism to do this? 

append puts the html before the description and makes a mess (from playground) 
without append
![Screenshot at 2021-06-18 08-26-34](https://user-images.githubusercontent.com/1498142/122568019-ec72d400-d00e-11eb-8e0d-4b523794623b.png)

with append

![Screenshot at 2021-06-18 08-25-28](https://user-images.githubusercontent.com/1498142/122567885-c64d3400-d00e-11eb-9144-85ec40dd14fc.png)

**Comment by BKeyport** [comment]
I'm the user involved - Here's ideally what I want. 

I would like the number to appear on load, showing the current value before any move. 
When moved, it should change instantly. 
the description should *not* be part of the box. 

The code we're using in the json is thus: 

from schema section -
```
"startMonth": {
              "type": "integer",
              "minimum": "-12",
              "maximum": "12"              
            },
```
from form section -

```
{
          "title": "startMonth",
          "key": "MMM-Multimonth.config.startMonth",
          "type": "range",
          "description": "What month do you want to start the calendar, in relation to current month",
          "append":"<div id='someid' class='classname'>",
          "onChange": "(evt,node)=>{let slideval=$(evt.target).val(); $('#someid').text(slideval)}"
        },
```

**Comment by tchapi** [comment]
Hello all,
I have made this feature available in https://github.com/jsonform/jsonform/tree/feature/range-indicator

Can you tell me if this suits your need before I merge ?

**Comment by tchapi** [comment]
The value indicator is not styled — this is left as something that can be done in CSS

**Comment by sdetweil** [comment]
not styled. that's awesome!

**Comment by sdetweil** [comment]
i hadn't tested yet,, just responding to the styled statement

**Comment by tchapi** [comment]
Well let me know if there are adjustments to make and reopen if needed :)

**Comment by BKeyport** [comment]
I'm not sure how to test this outside Sam's project, or I'd test it myself. 

Sam, If you give me instructions on your issue, I'll test when ready.

**Comment by sdetweil** [comment]
@tchapi   u might add in the doc that the css class is range-value

**Comment by tchapi** [comment]
☑️ Done

**Comment by BKeyport** [comment]
tchapi: Works perfectly within my system. Just gotta learn CSS (my weak point) 

In form section: 
```
{
          "title": "startMonth",
          "key": "MMM-Multimonth.config.startMonth",
          "type": "range",
          "description": "What month do you want to start the calendar, in relation to current month",
          "htmlClass":"some_unique_classname",
          "indicator":true
        },
```

THANK YOU very much.

**Comment by tchapi** [comment]
My pleasure. I try to contribute to / improve JSONForm as often as I can but as with every open-source single-contributor project, it is quite an endeavour and my time is limited 🙂
