### ISSUE TITLE
Is there plan to support for Bootstrap 5 and OpenAPI 3?

### ISSUE THREAD

**Issue by KES777** [jsonform/jsonform#366]
thank you.

**Comment by tchapi** [comment]
See https://github.com/jsonform/jsonform/issues/364 for Bootstrap 5

Unfortunately, I don't have much time to implement all this, and rely essentially on PRs from the community to enhance JSONForm for now.

Thanks

**Comment by KES777** [comment]
Could you please provide some clues to start with? Probably I try to move it further. Thank you

**Comment by tchapi** [comment]
Hi @KES777 

For Bootstrap5, it's a matter of changing the utility classes for each field type and check that the form renders correctly
For the Json Schema (not open API), we need to go through https://json-schema.org/draft-07/json-schema-release-notes.html and find the differences, and implement what is missing (more or less)
