### ISSUE TITLE
error after PR 349 

### ISSUE THREAD

**Issue by sdetweil** [jsonform/jsonform#367]
if the schema default is smaller than the minimum for template (5 chars)
in my case it is "" or " "

the new code fails.. 

text.replace is  invalid

need to add back the test I had to see if the value retrieved from the schema contains a templated value 
```
        this.value =this.schemaElement['default']
        if(this.value.toString().includes("{{"))
```

**Comment by tchapi** [comment]
Do you have a full example where it fails ?

**Comment by sdetweil** [comment]
[jsonform_trap.txt](https://github.com/jsonform/jsonform/files/6704210/jsonform_trap.txt)


actually it is not text, it is a number

**Comment by tchapi** [comment]
Ah, but you have a default property that is an integer for an element that expects a string, so it's not related to the templating in _itself_.

I will make a fix for that

**Comment by sdetweil** [comment]
well, the templating code ASSUMES it is working on a string, which its not..
