### ISSUE TITLE
Expandable sections with required fields inside lead to an invalid form control with name='XYZ' is not focusable.

### ISSUE THREAD

**Issue by aeneaswiener** [jsonform/jsonform#373]
When putting a required field inside an expandable section, it triggers an error in the console

```
An invalid form control with name='XYZ' is not focusable.
```

It is expected as per https://github.com/jsonform/jsonform/blob/9e2463c1a8d516e2f8c419a05b02ef61de3d0081/lib/jsonform.js#L404-L406

What would be a good workaround for this? Is there an elegant way to unfold all sections only if there are errors? I tried putting unfolding sections logic into into the onSubmit function however this runs after the here reported error triggers. Any other options?

**Comment by tchapi** [comment]
Hi

Can you share your whole JSONForm so I can test in the playground ?

**Comment by aeneaswiener** [comment]
Great, thanks in advance!

Here is a working example that shows the issue. I've confirmed this works in the playground and shows the issue there 

```JSON
{
    "form": [
        {
            "type": "fieldset",
            "title": "my fieldset 1",
            "expandable": true,
            "items": [
                {
                    "key": "field1",
                    "type": "text"
                },
                {
                    "key": "field2",
                    "type": "text"
                }
            ]
        },
        {
            "type": "fieldset",
            "title": "my fieldset 2",
            "expandable": true,
            "items": [
                {
                    "type": "tabarray",
                    "items": [
                        {
                            "type": "section",
                            "legend": "Item {{idx}}",
                            "items": [
                                {
                                    "key": "myparent1[].field1",
                                    "type": "text"
                                },
                                {
                                    "key": "myparent1[].field2",
                                    "type": "text"
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "type": "submit",
            "title": "My submit"
        }
    ],
    "schema": {
        "field1": {
            "type": "string",
            "title": "my field1",
            "required": true
        },
        "field2": {
            "type": "string",
            "title": "my field2",
            "required": true
        },
        "myparent1": {
            "type": "array",
            "required": true,
            "minItems": 1,
            "items": {
                "type": "object",
                "title": "my yparent1",
                "properties": {
                    "field1": {
                        "type": "string",
                        "title": "my field1",
                        "required": true
                    },
                    "field2": {
                        "type": "string",
                        "title": "my field2",
                        "required": true
                    }
                }
            }
        }
    }
}
```

<img width="1633" alt="Screenshot 2021-07-15 at 17 48 31" src="https://user-images.githubusercontent.com/4281507/125826391-91c13db7-850e-4f38-9a18-9fde85688efa.png">

As mentioned in the original issue, I don't think this can be fixed unless we can find a way to unfold the relevant, or all sections. I'm also not sure what will happen if the missing field is in a currently hidden tab, but will test that once I worked around this first issue

**Comment by tchapi** [comment]
Hi

What I would try is to make the fields not required, and implement a custom validation (in the onSubmit for instance) that would unfold the relevant sections.

_or_

you could leave the fields as required and use the `novalidate` attribute on the form element for a similar effect, but where you get the actual validation errors without much work + the little red * _(see the console when you submit the form in `novalidate` mode)_

What do you think ?
