### ISSUE TITLE
Is JSONForms.io has any relation with jsonform github ?

### ISSUE THREAD

**Issue by ab73863** [jsonform/jsonform#380]
Hello,

We were building an component using JSONforms and would like to give the logo for it. From the git hub repo (https://github.com/jsonform/jsonform) couldn't find any reference to jsonforms.io website and in the repo couldn't find any logo or icon referred. 

Could you please confirm whether the JSONForms.io icon is applicable for jsonform . If not please let me know the ideal publically available icon jsonform framework.

**Comment by tchapi** [comment]
Hi !
https://jsonforms.io/ has nothing to do with this repo, it's another project. We don't really have a logo...
