### ISSUE TITLE
Data List

### ISSUE THREAD

**Issue by Kreijstal** [jsonform/jsonform#381]
For those times where you have a field text, and you want to have suggestions but you are not limited by those suggestions, it's still free text, I have not found a way to create a [datalist](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) with this Library, or did I read the documentation way too swiftly?

**Comment by Kreijstal** [comment]
I came up with a way to force a datalist somehow but JSV doesn't like it when you want to be more flexible, is there a way to get around this?
I made an example here.

https://jsitor.com/uI2c9UtZlZ

Apparently JSV really doesn't like when enum is not a value in the input field, and I don't see any alternatives that allow this, so do people really don't like Free input fields with suggestions? :/

**Comment by tchapi** [comment]
Sorry for not coming back to you sooner — would you mind posting your working solution here so I can maybe add a note in the Wiki for others that wish to do the same ?
Thanks !

**Comment by Kreijstal** [comment]
Hi, sure, I just realized the site 404'd.

I just added this line after calling the library
```
  JSONForm.fieldTypes.datalist={inputfield:true,fieldtemplate:true,template:"<input list=\"<%= id %>-list\" id=\"<%= id %>\" name=\"<%= node.name %>\" class='form-control<%= (fieldHtmlClass ? \" \" + fieldHtmlClass : \"\") %>'<%= (node.schemaElement && node.schemaElement.disabled? \" disabled\" : \"\")%><%= (node.schemaElement && node.schemaElement.required ? \" required='required'\" : \"\") %>/><datalist id=\"<%= id %>-list\"> <% _.each(node.options, function(key, val) { if(key instanceof Object) {  %> <option value=\"<%= key.value %>\"><%= key.title %></option> <% } else { %><option value=\"<%= key %>\"><%= key %></option> <% }}); %> </datalist>"}; 
 ```
 and I put "type":"datalist" on the keys where I want to use them.

**Comment by tchapi** [comment]
Thanks !
