### ISSUE TITLE
Issue  : Description not showing above the text field

### ISSUE THREAD

**Issue by ab73863** [jsonform/jsonform#385]
Hi,

I am adding the description to a text field refering the sample provided in the playground [http://ulion.github.io/jsonform/playground/](http://ulion.github.io/jsonform/playground/) . When my html is rendered the description is showing below the text field instead of above the text field. Could you please help in resolving this issue.

**JSON form used:**
```
{
  "schema": {
    "name": {
      "title": "Name",
      "description": "Your name",
      "type": "string"
    },
    "gender": {
      "title": "Gender",
      "description": "Your gender",
      "type": "string",
      "enum": [
        "male",
        "female",
        "alien"
      ]
    },
    "email": {
      "title": "Email",
      "description": "Personal email address",
      "type": "string"
    }
  },
  "form":[
      { "description": "Your name","key" : "name","placeholder" : "Nickname allowed" },
      { "key" : "gender" }
      ]
}
```
**HTML rendered:**

<img width="699" alt="Screen Shot 2021-10-24 at 9 52 09 AM" src="https://user-images.githubusercontent.com/37161891/138573864-1cb579c3-ebe2-4e50-bbc4-04f1a0ea7107.png">

**Expected html (As shown in playground):**

<img width="697" alt="Screen Shot 2021-10-24 at 9 53 55 AM" src="https://user-images.githubusercontent.com/37161891/138573896-10c04c1c-68a5-4750-a214-a48a8779dcdb.png">

**Comment by domeales-paloit** [comment]
Hi there, I know this is closed, but it looks like this is the current behaviour in 2023 that the description/help-text is below the input field?

This is also how it is shown in the playground.

Is there a way to get the description to display before the input field?

Thanks!

**Comment by sdetweil** [comment]
Use the title attribute in the form declaration..  you can put it where u want..  I do 
```
                        {
                          "type": "section",
                          "title": "config",
                          "items": [
                            {
                              "title": "effect",
                              "key": "alert[].config.effect"
                            },
                            {
                              "title": "alert_effect",
                              "key": "alert[].config.alert_effect"
                            },
```

**Comment by domeales-paloit** [comment]
Ok thanks. I have moved it as I needed with JS.
