### ISSUE TITLE
Support for descriptive enum with "oneOf"

### ISSUE THREAD

**Issue by janesp** [jsonform/jsonform#395]
I just tried with my first schema (derived from a real world case) and realized that "oneOf" is not supported (more descriptive enum, as of https://github.com/json-schema-org/json-schema-spec/issues/57)

Are there any plans to support this functionality anytime soon?

**Comment by tchapi** [comment]
Hello @janesp 

So far, plans are on hold since I don't have much time to add functionnality to the library. But I'm always happy to accept PRs ;)
