### ISSUE TITLE
Enhanced jsonform version

### ISSUE THREAD

**Issue by piorek94** [jsonform/jsonform#401]
Please checkout new fork: https://github.com/piorek94/jsonform

The main goal of this fork:
- update bootstrap to 4.6.1
- merge all features of [original repo](https://github.com/jsonform/jsonform) and [ulion fork](https://github.com/ulion/jsonform)
- update all dependencies (and add new optionals)

Changes:
- move towards new jsonschema drafts versions (draft-04) - not supported keywords: `anyOf`, `oneOf`, `allOf`
- support simple schema's
- support references (including recursive references)
- json schema validators: z-schema, ajv, jsv (deprecated)
- new WYSIWYG editor - summernote
- deleting i'th (tab)array item
- new color pickers - vanilla-picker & spectrum by seballot
- dropped transloadit (temporary)
- use fontawesome icons
- tagsinput partial support (not follow all the constraints)
- autocomplete (by jqueryUI & bootstrap-typeahead)
- arrays do not render first empty item from default

**Comment by joelguittet** [comment]
Hello
Why not proposing some PR(s) to the original repo ?
Regards,
