### ISSUE TITLE
Empty required textarea

### ISSUE THREAD

**Issue by alcabon** [jsonform/jsonform#402]
An empty textarea has always instance.getType() === 'string' in jsv.js in my case (?) and the required option doesn't work because it is not "undefined" like an empty input string.

Did you notice the same thing?

I am building a tool based on jsonform.js and that works well excepted for the empty required textarea and the validator of jsv.js that I used.  

              myitem: {
                  type: "textarea",
                  title: "Item {{idx}}",
                  required: true,
                  default:""
                },

https://github.com/jsonform/jsonform/blob/master/deps/opt/jsv.js

My quick fix for empty required textareas in json forms for the validator of jsv.js:

  "required" : {
			"type" : "boolean",
			"default" : false,

			"parser" : function (instance, self) {
				return !!instance.getValue();
			},

			"validator" : function (instance, schema, self, report, parent, parentSchema, name) {
       
				if ( ( instance.getType() === "undefined" 
				|| instance.getType() === "string" && instance.getValue().trim() === ''
				 )
				&& schema.getAttribute("required")) {
					report.addError(instance, schema, "required", "Property is required", true);
				}
			}
		},

**Comment by tchapi** [comment]
Hi @alcabon
So this is more a bug with jsv ... unfortunately it is not maintained anymore so I guess your fix is the right solution

**Comment by alcabon** [comment]
Hi @tchapi 

https://github.com/garycourt/JSV/blob/master/lib/json-schema-draft-03.js  seems the last version indeed (10 years ago).

You are using your own fork based on this draft version and I have created my own fork too.

Thanks for your help

**Comment by alcabon** [comment]
A bettter fix still limited but sufficient in my case for empty textareas. 

|| instance.getType() === "string" && instance.getValue().trim() === ''    // prevent some pb with getValue() not defined

instance.getType() !== "undefined" is not restrictive enough in my case finally for other required fields. 

"required" : {
				"type" : "boolean",
				"default" : false,

				"parser" : function (instance, self) {
					return !!instance.getValue();
				},

				"validator" : function (instance, schema, self, report, parent, parentSchema, name) {
           
					if ( ( instance.getType() === "undefined" 
					|| instance.getType() === "string" && instance.getValue().trim() === ''
					 )
					&& schema.getAttribute("required")) {
						report.addError(instance, schema, "required", "Property is required", true);
					}
				}
			},
