### ISSUE TITLE
How to manage combination of vertical and horizontal layout? 

### ISSUE THREAD

**Issue by UdayCTO** [jsonform/jsonform#403]
Hello, 

I would like to manage combination of horizontal and vertical layout, how do I do it? 
e.g. I have invoice schema which has invoice header (Invoice nr, invoice date, invoice amount, discount) and invoice details which will have multiple line items (e.g. product code, product name, quantity, unit price, amount, tax% etc)

**Comment by sdetweil** [comment]
JSONForm is vertical. 
so I think u will have to use CSS classnames and then css to arrange the fields in a different visual layout

**Comment by tchapi** [comment]
That's true. You can roll your own CSS or alter the templates if you want to achieve a custom layout

**Comment by sdetweil** [comment]
altering the template seems extreme, but...
