### ISSUE TITLE
Question: how to update data in the form?

### ISSUE THREAD

**Issue by pruchay** [jsonform/jsonform#405]
Hi :) 
I want to create two tabs with two different libraries (one for regular users and one for tech users). In the regular tab will be placed `jsonform` and in the tech tab `jsoneditor`. 

When the user will be switching between tabs, I need to pass data from one tab to another. Currently, it works, but when I switch from the `jsoneditor` tab to the tab with `jsonform` I have a problem - data in the form is not updated - it's just creating a new form.

So, is it possible to update a form that already exists instead of creating a new one?

For updating data in the form, I use this code:
```
      const setFormData = data => {
        $('#jsonForm').jsonForm({
          value: data,
          ...jsonFormSchema,
        })
      }
  ```
Update 1:
Aa a quick solution I used `document.getElementById('jsonForm').innerHTML = ''`, but maybe there is built in solution?

Update 2:
But this lead to a bug - I can't expand grouped fields.

**Comment by tchapi** [comment]
Hi,
I would reckon that you need to instantiate your form _once_, and then update the data as you need when you switch between tabs.

`.jsonForm()` creates a form. You need to use standard JS to update a field
