### ISSUE TITLE
date-time validation issues

### ISSUE THREAD

**Issue by ThomasJejkal** [jsonform/jsonform#407]
Hi, 

I have an issue while dealing with date-time attributes and I hope that someone can give me some advice on how to cope with this. First, I'm using the updated version of jsonform mentioned in #401 but the situation should also apply to the official version.

Furthermore, I have a schema with an attribute defined as follows:

```
"lastCalibration":{
   "type":"string",
   "format":"date-time"
}
```
For this attribute, jsonform creates an input of type "datetime-local", which returns values in the format "2022-06-13T14:53" according to the HTML spec. Unfortunately, according to the jSON Schema spec, values of type "date-time" must include timezone information and therefore, form submission fails with a validation error.  

Does anybody have an idea how to workaround this kind of conflict? The only solution I can think of is using a pattern-based text input, which is not extremely user friendly. Thanks for your help.

**Comment by sdetweil** [comment]
here is a direction for handling
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local#setting_timezones

**Comment by sdetweil** [comment]
@ThomasJejkal
