### ISSUE TITLE
Multiple Fields on A Single Row

### ISSUE THREAD

**Issue by jasondalycan** [jsonform/jsonform#408]
Is there a way to control the layout whereby multiple fields will appear on a single row within the form (instead of each field being laid out line by line)?  I reviewed the documentation but could not find reference to such an opion.

**Comment by tchapi** [comment]
Hi
You can modify the templates if you wish.

See https://github.com/jsonform/jsonform/issues/332 for instance (there are others discussions in various issues about this)

**Comment by sdetweil** [comment]
you could also add a class to a wrapper div  and change the layout to inline-flex, flex-direction horizontal.

**Comment by jasondalycan** [comment]
Ok thanks
