### ISSUE TITLE
Plain Text without input tag

### ISSUE THREAD

**Issue by RealMasterZen** [jsonform/jsonform#409]
Hello,
Is it possible to just add a text item without relative input element?
So just a generic text to write some note / description / header ( single line or multiline )

If so, if i'm using a text editor, will it works on the generated field?

Thanks !

**Comment by sdetweil** [comment]
you could mark the input field as read only 

[Mark a field as read-only: the readonly property](https://github.com/jsonform/jsonform/wiki#fields-common-readonly)
(as well as description, title...) 

don't understand the second question 
```
