### ISSUE TITLE
[meta] Maintenance going forward

### ISSUE THREAD

**Issue by tchapi** [jsonform/jsonform#412]
:wave: Hi all contributors,

Unfortunately lately I haven't had the bandwidth to look at issues / pull requests and my day-to-day job is taking too much time. Also, I have little interest to put hours into this library as I'm not using it anymore.

@sdetweil, would you be interested in taking ownership of the maintenance of this library ? I've created an [organization](https://github.com/jsonform?type=source) so it's easy to add you to it with the correct merge rights.

Thanks 🙏🏼

**Comment by sdetweil** [comment]
@tchapi yes, I would be willing

is the doc in the same repo?

who manges/pays for/supports the jsonform playground website, and how do updates/examples get added/removed there

**Comment by tchapi** [comment]
> is the doc in the same repo?

Everything is in this repo on Github, there's nothing else.

> who manages/pays for/supports the jsonform playground website

This is Github Pages, directly from the `master` branch of this repo. It's free. There is no maintenance or hosting involved.

> how do updates/examples get added/removed there

It's in the [playground](https://github.com/jsonform/jsonform/tree/master/playground) folder

**Comment by sdetweil** [comment]
ok, thanks

**Comment by sdetweil** [comment]
i see I cannot set labels on issues..

**Comment by tchapi** [comment]
Should be good now

**Comment by sdetweil** [comment]
I have a wiki update for #411 , and I made a separate branch.. how can I expose it for any review? 

seems it master or nothing..  I will post that to the issue I suppose

**Comment by tchapi** [comment]
Yes, the wiki is not versionned (as in `git`) but it's revisioned ([here](https://github.com/jsonform/jsonform/wiki/Home/_history)) so you're safe

**Comment by sdetweil** [comment]
thx.. posted in original  issue.. will wait a little

**Comment by tchapi** [comment]
I merged #422.

For #414, I think it would be better to update the whole optional dependency ...

**Comment by sdetweil** [comment]
sorry don't understand the dependency thing

**Comment by sdetweil** [comment]
jsv.js from github project (also 10 yrs old) isn't as big as the one here.. (by half)

**Comment by tchapi** [comment]
I'm all in favour of putting it in `package.json`, but jsonform doesn't use any package dependency manager yet (like yarn or npm). This would be a good thing to add but it's not straightforward I think

**Comment by sdetweil** [comment]
can u guide me where the components come from/should come from. I see the jQuery stuff

jsv seems soooo different and has dependencies

**Comment by tchapi** [comment]
jsv is here: https://github.com/garycourt/JSV/commits/master
The version we use is [0aa11852537069b0830569ef1eab11a36b65b3ab](https://github.com/garycourt/JSV/commit/0aa11852537069b0830569ef1eab11a36b65b3ab) - you can pin the dependency to this specific commit if ever it's not possible to update (I doubt so)

**Comment by sdetweil** [comment]
thx.  I also have trouble w the jQuery plugins. every time I select download I get taken to jQuery download, which doesn't  provide these separated out in the downloaded zip

**Comment by sdetweil** [comment]
didn't look there!

**Comment by sdetweil** [comment]
how does test work?

**Comment by sdetweil** [comment]
can u write me two or three paragraphs on what u think the work is, and I can start. not asking u to do it.  

my email is my userid at gmail

**Comment by sdetweil** [comment]
ah, i see.. I Have never produced a production web site before so haven't investigated using any kind of framework, classes, styles, etc.. 

so in some cases we can replace the classes with the new, and test for impacts
and in some cases classes went away.. (dropdown) from the bootstrap core (v5)

**Comment by tchapi** [comment]
> and in some cases classes/plugins went away.. (dropdown) from the bootstrap core (v5)

It's included, you just have to include popper.js with it: see https://getbootstrap.com/docs/5.0/components/dropdowns/

**Comment by Rndwiga** [comment]
Was the update to V5 ever done?

**Comment by sdetweil** [comment]
no.

**Comment by Rndwiga** [comment]
That's sad. Before I waste time hacking my way with the upgrades, and do a PR, is there a fork that has the upgrades?

**Comment by sdetweil** [comment]
not that I am aware of.. I was working on it, but never got done..  now swamped with other stuff

**Comment by Rndwiga** [comment]
Oh okay. Did you have an opportunity to look at what was suggested on the fork on issue #401 ? I could start by upgrading using those suggestions

**Comment by sdetweil** [comment]
I saw them, but did not evaluate them at the time I was starting to update .. 

some look awesome, some I'm not sure what they mean.. 

 so net, no

**Comment by Rndwiga** [comment]
I am going to jump Bs4 and go straight to Bs5. Since that's where I need to use the project on. Can we do that on a branch that I can be pushing PRs to?

**Comment by sdetweil** [comment]
yes, use the upgrades branch, just created

**Comment by Rndwiga** [comment]
Thanks!

**Comment by Rndwiga** [comment]
Well, it seems nothing is broken yet apart from the UI looking ugly but functional. What do you feel about the following:

- Switching Gyphicons with Bootstrap 5 icons?
- Switching bootstrap-wysihtml5 with Summernote. The bootstrap-wysihtml5 is no longer actively updated.
- Updating the playground example to use Bootstrap 5

**Comment by sdetweil** [comment]
seems reasonable..
