### ISSUE TITLE
Bug in selectedfieldset when using enums

### ISSUE THREAD

**Issue by jmalcaraz** [jsonform/jsonform#413]
Hi, i have discovered a bug that would like to report. It is related to the "readonly" and "disabled" properties that are not being enforced when there is a "selectedfieldset" and it applies for those selected fields  that contains an enum.  The properties work well with they are not enums. 

The way to reproduce the error is very simple as it there is a JSON Playground almost ready for that "Fields - Alternative - the selectedfieldset type", just try to disable/readonly the "category" availble in such playground and you will realise. 

P.S. Thanks a lot for the library, it is really useful.

**Comment by sdetweil** [comment]
don't think it's a bug, so much as a limitation of the core behavior

some choices
https://stackoverflow.com/questions/14019670/how-to-prevent-a-select-from-being-changed
