### ISSUE TITLE
Array Field's Icons(add/remove) are misaligned

### ISSUE THREAD

**Issue by drveresh** [jsonform/jsonform#417]
The add/remove icons for fields are redundant and misplaced.

Ref links:
https://jsonform.github.io/jsonform/playground/index.html?example=fields-tabarray
https://jsonform.github.io/jsonform/playground/index.html?example=templating-idx

Screenshots:
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/3812468/190625449-3e1ae090-40d8-47d0-9152-c7c2a4f31609.png">

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/3812468/190627370-c5f68b99-518c-4cae-b6e1-cf3b970db402.png">

If there is a section containing >1 field, then there should be one single remove icon and the entire section should have some border to indicate the area where the action takes place on.

**Comment by sdetweil** [comment]
the individual delete button is due to this pr, cause some wanted the ability to delete a specific list entry, instead of just the last
https://github.com/jsonform/jsonform/pull/400/files

 the drag element is an element above the element title, so positioning it might be more difficult. 
(I'm the one that submitted the draggable:false function )

**Comment by drveresh** [comment]
@sdetweil Thanks for the quick response.  

**1: Remove Icon:** Even if somebody wants to delete any random records, keeping its own _remove_ icon towards right most side is appropriate.

**2: Drag Icon**: Keeping it in a separate(top) line is efficient because the rest of the entire line will be useless, so positioning it in front of the input box is better.

**3: Drag Icon Symbol**: The current one looks bulky. I would suggest using a simple and clean one like this "**⁝**" by "&##8285;", it looks much better, please see the below screenshot.

**4: Drag Field Title Place**: Based on the latest trend, it doesn't make sense to give a separate line for it, rather we can directly put it as a "placeholder" attribute, see the screenshot.

Some of these changes would give a simple yet clean look and feel.  Please let me know your thoughts.

<img width="698" alt="image" src="https://user-images.githubusercontent.com/3812468/190650257-32f152a0-b103-4794-b9e8-f56300794125.png">

**Comment by sdetweil** [comment]
I hear you,  but, every UI change breaks someone's doc somewhere.  

you are, of course, welcome to clone the repo and make those changes.  maybe submitting back a PR for consideration

I personally like the delete at the end idea  worried about view clipping without trying it. 

oh,  and border, you can add an html class and customize the structure colors, fonts, borders..  

I do this in one of my uses

**Comment by sdetweil** [comment]
in #419  I added a form setting to allow removing the delete current item  button.. 

deleteCurrent: false.

**Comment by sdetweil** [comment]
looking at what might be doable.. I see a structure like this 
![Screenshot at 2022-09-19 11-38-06](https://user-images.githubusercontent.com/1498142/191068628-7493790f-8123-419c-adb3-f7e5f03114cb.png)

which is an array of objects.. the drag affects the entire object.. 
where would we put the drag icon in this case?
