### ISSUE TITLE
Error in Navigation Tabs when the title has more than one blank space

### ISSUE THREAD

**Issue by Juanmenacho** [jsonform/jsonform#420]
If a tab is added, with a title that has more than one blank space, the display of the navigation tabs fails.

Example, tab:
```
{
	"title": "Movies and TV",
	"type": "tab",
	"items": [
		{
			"key": "favorite_movie",
			"type": "radiobuttons",
			"activeClass": "btn-success"
		}
	]
}
```

It will generate the following HTML:
`<div class="tab-pane" id="navtabs-Movies_and TV">`

Will cause the jQuery selector to fail when trying to retrieve the element by its ID

Example tested on https://jsonform.github.io/jsonform/playground/index.html?example=navigation-tabs
![Error1](https://user-images.githubusercontent.com/27310423/191938515-2d634370-7633-4704-9512-50ddf3b87389.PNG)

One possible solution is to replace the replace function with replaceAll when constructing the element id in the template, screenshots are attached.
![Possible_solution](https://user-images.githubusercontent.com/27310423/191938989-c78f1e70-05a0-495e-a5e2-b4aac42dbcf0.PNG)

**Comment by sdetweil** [comment]
I wonder if there are any other characters in labels that cause similar problem

**Comment by sdetweil** [comment]
![Screenshot_20220923-072609_Chrome](https://user-images.githubusercontent.com/1498142/191959799-317cf204-a00f-4f59-a379-ff02ebc6d54e.jpg)

no spaces allowed in IDs.  but can be escaped
