### ISSUE TITLE
How to add class on label tag

### ISSUE THREAD

**Issue by ajayexpert** [jsonform/jsonform#424]
How to add class on label tag

**Comment by sdetweil** [comment]
which jsonform element are you mentioning?  as we don't have a 'label' thing..

**Comment by ajayexpert** [comment]
I meant for class on title since i am not using bootstrap using tailwind css so need to give css for title as well. 

![image](https://user-images.githubusercontent.com/20170050/201276919-1ca4de76-3aae-4f47-a5d8-3ef0c2f160a4.jpeg)

**Comment by sdetweil** [comment]
ok, what I did on my app was use a little jquery on the result of the jsonform output to set styles 

https://stackoverflow.com/questions/4844594/jquery-select-the-associated-label-element-of-a-input-field

the .closest() method will locate  the nearest parent
// find the element with htmlclassname
find its closest parent label element, and apply these styles
```jquery
$(.htmlclassname).closest('label').css(...)
```

**Comment by sdetweil** [comment]
closing answer given, reopen if needed
