### ISSUE TITLE
Ace Type as Array

### ISSUE THREAD

**Issue by jasondalycan** [jsonform/jsonform#426]
I have not found a way to create an array of Ace fields.  When doing the following the Ace editors show-up within each field, but they drag in a very odd way and appear buggy:

``
schema: 
{  myArray: 
        {   type: "array",
            title: "Form Values",
            items:
            {   type: "object",
                properties:
                {   value:
                    {   type: "object",
                        title: "Form Value",
                        properties:
                        {   key:
                            {   type: "ace",
                                title: "Key"                                                
                            },
                            value:
                            {   type: "ace",
                                title: "Value"                                                
                            }
                        }
                    }                    
                }
            }            
        }
}
``

Is it possible to create an array of Ace types and if so can you please provide an example?

**Comment by sdetweil** [comment]
set draggable:false in the array form definition

**Comment by jasondalycan** [comment]
Thanks that resolves the dragging issue.  The height parameter for the Ace editor doesn't seem to take effect in this case though.  For example, using the following the height is ignored and falls back to the default:

`myAceField:
{   title: "My Ace Field",
    type: "ace",
    aceMode: "javascript",
    height: "80px"                                    
} `

**Comment by sdetweil** [comment]
well, 80px for a custom font text editor .....

maybe Ace has a minimum size
did u try using css to style it?

**Comment by jasondalycan** [comment]
The height: "80px" parameter works fine if added within the `form` section of the definition, it's just not recognized if added within the `schema` portion of the definition.  Is this only supported within the `form` section?

**Comment by sdetweil** [comment]
yes  config of the elements is done in the form section

**Comment by jasondalycan** [comment]
Ok thanks.  In that case is there a way to set ace as the type for an object's property within the `form` section?  I haven't noticed a way to do this within the documentation and was wondering if this is supported.

**Comment by sdetweil** [comment]
i add 
```
  type: "ace",
  aceMode: "json",
  aceTheme: "twilight",
  width: "100%",
  height: "100px"
```
its right there in playground
https://jsonform.github.io/jsonform/playground/index.html?example=fields-ace
and in the doc
https://github.com/jsonform/jsonform/wiki#fields-ace

remember 'key':  connects the form element to the schema element

**Comment by jasondalycan** [comment]
Ok thanks.  And sorry if I've missed this somewhere, but what I'm trying to understand though is how to set the property a field of type `"object"` to the ace type.  Please see the following example, I'm not clear on how to set the `object` field property **setStatus.statusExpression** to the ace field type within the form section:

`schema: 
{   setStatus:
	{   type: "object",
		properties:
		{   menuTitle:
			{   title: "Menu Title",
				type: "string"
			},
			statusExpression:
			{   title: "Status Expression",
	                    type: "string"
			}                            
		}
	}
},
form: 
[   {   title: "Actions",
		type: "array",
		items:
		[   {   type: "selectfieldset",
				title: "Action Type",
				items:
				[   {   key: "setStatus",
						legend: "Set Status"
					}
				]
			}                                
		]
	},
	{   type: "submit",
		title: "Save"
	}
]`

**Comment by sdetweil** [comment]
given your example, (as json, needs to be json) 

```
{ "schema": {
    
  "setStatus":
  {   
    "type": "object",
  	"properties":
		{   "menuTitle":
			{   
        "title": "Menu Title",
				"type": "string"
			},
			"statusExpression":
			{  
        "title": "Status Expression",
	      "type": "string"
			} 
		}
	}
},
"form": 
[   
  {   "title": "Actions",
		"type": "array",
		"items":
		[  
      {   
        "type": "selectfieldset",
				"title": "Action Type",
				"items":
				[  
          {   
            "key": "setStatus.statusExpression",
						"title": "Set Status1",
            "type":"ace"
					}        
				]
			}                                
		]
	},
	{   
    "type": "submit",
		"title": "Save"
	}
]
}
```
using playground to test the form definition, copy/paste to the playground window

![Screenshot_2022-12-24_12-56-38](https://user-images.githubusercontent.com/1498142/209448291-0e7441ec-dbbb-42c1-8d97-741f356c3724.png)

**Comment by jasondalycan** [comment]
That works: thanks!  cheers
