### ISSUE TITLE
[Question] How to get the markup of the form programatically in JS without attaching it to a DOM element

### ISSUE THREAD

**Issue by naveenvalecha** [jsonform/jsonform#429]

**Comment by sdetweil** [comment]
I don't think you can  BUT the DOM  doesn't have to be IN  the DOM

I think u can create a div element and use that as the target. and then use element.innerHtml to get the html text

**Comment by sdetweil** [comment]
because jsonform is a Dom generator  it needs to be done in a runtime supporting Dom operations, not just node.
