### ISSUE TITLE
activeClass isn't applied correctly for schemas with defaults

### ISSUE THREAD

**Issue by radiomime** [jsonform/jsonform#432]
## intent

I'd like to apply a bootstrap activeClass to a radiobutton with a default set.

## bug

```json
{
  "schema": {
    "language": {
      "type": "string",
      "title": "Best language",
      "enum": ["JavaScript", "Python", "PHP", "Java", "C++", "other"],
      "default": "Python"
    }
  },
  "form": [
    {
      "key": "language",
      "type": "radiobuttons",
      "activeClass": "btn-primary"
    }
  ]
}
```

On load, yields:

![Screen Shot 2023-04-12 at 1 52 22 PM](https://user-images.githubusercontent.com/11998202/231569572-c93a4a87-9fc8-4780-b21f-83a7086fc946.png)

And when a different selection (C++) is chosen, yields:

![Screen Shot 2023-04-12 at 1 52 29 PM](https://user-images.githubusercontent.com/11998202/231569682-6d65f350-cc75-4283-a795-68b20c2d7427.png)

## observations

This isn't an issue when there isn't a default value set. Removing `"default": "Python"` in the `schema` section above will allow the `btn-primary` class to apply. But when a default is provided (with the `default` keyword or in a `value` section), the `btn-success` class is applied.

**Comment by tchapi** [comment]
Hi and thanks for the report

It should be fixed in https://github.com/jsonform/jsonform/commit/961c590237b48c13bacd533206222e043ff39c49, can you confirm?

**Comment by radiomime** [comment]
Thanks for the quick turn around! Confirmed, it is working for the example in the issue and in my project.
