### ISSUE TITLE
Rendering fails if property name contains dots

### ISSUE THREAD

**Issue by chaehni** [jsonform/jsonform#439]
I'm trying to render a JSON schema which contains properties that contain a dot.
Rendering fails with the following error message:

> Entered content is not yet a valid JSON Form object.

>The JSON Form library returned:
>Error: The JSONForm object references the schema key "name.with.dot" but that key does not exist in the JSON schema

According to JSON schema specification, my schema is valid and should be rendered correctly.

A minimal example is this schema:

`{
  "schema": {
    "name.with.dot": {
      "title": "Name",
      "description": "Nickname allowed",
      "type": "string"
    }
  }
}`

**Comment by sdetweil** [comment]
we do not support the use of '.' in the keyname field , as we use this value to differentiate nesting levels.
