### ISSUE TITLE
Boolean options are always true

### ISSUE THREAD

**Issue by radiomime** [jsonform/jsonform#442]
# What I want to happen

I want two radio buttons to from, and I'd like the text in the box to be different than the value being sent. I'd also like the box to be preselected if it was presubmitted (by using the value key).

# Issue

No matter which button I select before submitting, the value sent is `true` in this example:

```json
{
  "schema": {
    "general": {
      "type": "object",
      "properties": {
        "is_cool": {
          "title": "Are you cool?",
          "type": "boolean"
        }
      }
    }
  },
  "form": [
    {
      "type": "fieldset",
      "title": "<b>General</b>",
      "items": [
        {
          "key": "general.is_cool",
          "type": "radiobuttons",
          "activeClass": "btn-success",
          "options": [
            {
              "title": "I'm not cool",
              "value": false
            },
            {
              "title": "I am, indeed, cool",
              "value": true
            }
          ]
        }
      ]
    },
    {
      "type": "submit",
      "title": "Submit"
    }
  ],
  "value": {
    "general": {
      "is_cool": true
      }
  }
}
```

The value sent should be `false` when selecting `"I'm not cool"` and hitting submit

# What I'd expect

This exact example works as I'd expect using strings instead of booleans:

```json
{
  "schema": {
    "general": {
      "type": "object",
      "properties": {
        "is_cool": {
          "title": "Are you cool?",
          "type": "string"
        }
      }
    }
  },
  "form": [
    {
      "type": "fieldset",
      "title": "<b>General</b>",
      "items": [
        {
          "key": "general.is_cool",
          "type": "radiobuttons",
          "activeClass": "btn-success",
          "options": [
            {
              "title": "I'm not cool",
              "value": "false"
            },
            {
              "title": "I am, indeed, cool",
              "value": "true"
            }
          ]
        }
      ]
    },
    {
      "type": "submit",
      "title": "Submit"
    }
  ],
  "value": {
    "general": {
      "is_cool": "true"
      }
  }
}
```

**Comment by sdetweil** [comment]
change the "true" and "false" to without quotes.  those are string and are always thrue

**Comment by sdetweil** [comment]
you might try "submit" instead of "value"

the doc says options are for strong values  not boolean

**Comment by sdetweil** [comment]
![Screenshot_20231219_081615_Chrome](https://github.com/jsonform/jsonform/assets/1498142/60e9bead-2e72-4c02-8d50-7cd25d993fe2)

**Comment by radiomime** [comment]
Thanks for the reply @sdetweil.

I templated the above schema (with the `value` key) from this [part of the projects wiki](https://github.com/jsonform/jsonform/wiki#constructing-a-dialog--the-questionsquestion-type) which gives a similar example, but with strings instead of boolean values.

If I don't include `"value": true`, both submitted values false. This is also the case if I use `"submit": true` instead.

**Comment by sdetweil** [comment]
ok, I'll look at it. the doc says "strings"

**Comment by sdetweil** [comment]
at this time, this is currently a restriction, only works with string entities..
