### ISSUE TITLE
How to show error after a control value is changed,

### ISSUE THREAD

**Issue by mamta91** [jsonform/jsonform#445]
I have a form with some controls which has  validations like min, max and pattern. I am looking for a solution in which I can show error related to a fields as I changed its content.

I have not found any such solution. I tried calling submit button of form on change of controls but it is also displaying error for non-visited fields as well but I want to show errors related to current field only.

Is there any workaround for this?

**Comment by sdetweil** [comment]
you can add your own onChange handler to each of the fields

**Comment by sdetweil** [comment]
you can also use css to display the notification and use the change handler to set the style
see 
the styles shown on the Common schema properties
https://github.com/jsonform/jsonform/wiki#common-schema-properties
