### ISSUE TITLE
Fieldset along with the Select all checkbox.

### ISSUE THREAD

**Issue by tlshinde** [jsonform/jsonform#450]
I would like to implement the functionality shown in the screenshot below, which includes a fieldset along with a 'Select All' checkbox. Is this possible? If so, could you provide me with the schema for it?

![Capturejasbhasc sa chsd vjhds vh sdjv sjd v](https://github.com/jsonform/jsonform/assets/168520710/fe78c079-b7bc-44e1-a7d3-7861a9ecc232)

**Comment by sdetweil** [comment]
well, its not in the schema.. its in the form. 
```
{
  "schema": {
    "menu": {
      "type": "array",
      "title": "Options",
      "items": {
        "type": "string",
        "title": "Option",
        "enum": [
          "starter",
          "maincourse",
          "cheese",
          "dessert"
        ]
      }
    }
  },
  "form": [
    {
     "title":"<input type=\"checkbox\" onchange=\"handlechange()\"> Options ( check all)",
      "type": "fieldset",      
      "expandable": false,
      "order": 0,
      "items": [
    {
      "key": "menu",
      "notitle":true,
      "type": "checkboxes",
      "htmlClass":"foo",
      "titleMap": {
        "starter": "Starter would be great",
        "maincourse": "No way I'll skip the main course",
        "cheese": "Cheddar rules!",
        "dessert": "Thumbs up for a dessert"
      }
    }
  ]
    }
    ]
}
```
then the handleChange function might look like this  (untested) 
function handlechange(evt, node){
     var all_checked=$(evt.target).checked  // get 'all' checkbox state.. should be true/false
     // use jquery to get all the checkboxes under the 'foo' class
     // loop thru them 
     $('.foo .checkbox').forEach((box)=>{ 
         box.checked = all_checked
     })
}
![Screenshot at 2024-04-30 11-33-41](https://github.com/jsonform/jsonform/assets/1498142/913463a1-947f-47dd-9951-db1b944fb5fb)

**Comment by tlshinde** [comment]
Hey @sdetweil , Using your code and the generated form appears as shown in the screenshot below. However, I would like the 'select all' checkbox to be positioned in front of the options to select all fields. By the way, I am using ajsf  in my project. 

![Screenshot Todays](https://github.com/jsonform/jsonform/assets/168520710/50d0a7d8-5097-43aa-ac8c-08c3b17b4fd6)

**Comment by sdetweil** [comment]
I don't know what you mean asjf. 
this is the jsonform library

I see there is a different library for asjf  angular

I do not know on the positioning. my literal coding places the checkbook in front 

there IS a problem.  we defined this as a string with a single choice.  so checking all has no place to store it.

**Comment by sdetweil** [comment]
I see you posted to the asjf github repo too 
https://github.com/hamzahamidi/ajsf

**Comment by sdetweil** [comment]
closing, wrong project reference
