### ISSUE TITLE
Array binding issue 

### ISSUE THREAD

**Issue by prafullbhalekar** [jsonform/jsonform#451]
Hello I am trying to bind dynamic array values to field inside ajsf but somehow I was not able to. could anyone please help me here ? attaching SS for the ref
![Screenshot (51)](https://github.com/jsonform/jsonform/assets/37729729/c7f3051e-016e-4bda-8151-ca33035a3a92)
any help would be apricated

**Comment by sdetweil** [comment]
I do not know what you mean  
```
 bind dynamic array values to field
```

the schema defines the array
the value section defines the values that are used when generating the form 
the form section defines the visual and interaction rules for the presentation

**Comment by sdetweil** [comment]
what do you mean by 'dynamic'

there are two approaches
1. the static value section define the data on form START 
2. the FORM can add or subtract from the array , before submit

you cannot change the data(value section)  live and THEN ask for form to change.. 
you must re-render the form

**Comment by prafullbhalekar** [comment]
Hi @sdetweil Thank you so much for you reply....If I want to add static values then how should I write my json schema file ? Currently what happing is if I add static array data in data object inside schema file on UI it's showing those values inside input fields but I don't want that input fields I just want to show direct values as shown in SS

**Comment by sdetweil** [comment]
I dont understand what you mean

**Comment by sdetweil** [comment]
also, asjf is a different project
https://github.com/hamzahamidi/ajsf

**Comment by sdetweil** [comment]
static data sounds like labels
lables are created from the fields title property
you could create read only fields with no data, and use css to mark the field display:none;  to hide it. leaving onty the title showing

**Comment by sdetweil** [comment]
closing, wrong project reference
