### ISSUE TITLE
Swapping the images 

### ISSUE THREAD

**Issue by bhalekarP** [jsonform/jsonform#452]
Hello , I am using the ajsf in my project , wherein I have requirement where once click on svg icon it should change to another svg icon basically wanted change the icons once click , How can I achieve this inside json schema file  ?

**Comment by sdetweil** [comment]
you would use the onChange or onClick properties to attach a function to handle the operation in javascript. 
see
https://github.com/jsonform/jsonform/wiki#using-event-handlers-to-react-on-fields-updates-in-real-time

**Comment by sdetweil** [comment]
also, asjf is not this project. that is something else.

**Comment by sdetweil** [comment]
closing, wrong project reference
