### ISSUE TITLE
"Instance is not one of the possible values" error on submit when changing the option list of a select field based on other field value

### ISSUE THREAD

**Issue by lethuy123** [jsonform/jsonform#459]
Hi Development team,

I want to create a select field (called A) that have option list changing based on other field's value (called B).
For example:

1. If field B value = 1, field A option list is list_1
2. If field B value = 2, field A option list is list_2
3. list_1 != list_2

I can do that by adding one event handler for field A as below
```javascript
function onBChanged() {
    var B_value = $(".input_form_B").find("select").val();
    var A_options = allOptionChoices[B_value]);
    var A_select = $(".input_form_A").find("select");
    A_select.empty();
    A_options .forEach((new_option) => {
        A_select .append($("<option></option>").attr("value", new_option).text(new_option));
    });
}
``` 
However, the problem is that at the JSONForm object initialization, I set the schema for field A like this:
```javascript
"schema": {
  "A":  {
        "required": true,
        "type": "string",
        "title": "A",
        "enum": allOptionChoices[1])
    }
}
``` 
It seems that the validator gets the initial enum value to check but I changed the option list of field A to a different list. So that why I got the "Instance is not one of the possible values" error when I click on Submit button. How can I create a select field that have option list changed but skip the "Instance is not one of the possible values" error? 

Any ideas would be appreciated. Thank you so much!

**Comment by sdetweil** [comment]
what you would need to do is setup a selectfieldset in the form section 
see doc here https://github.com/jsonform/jsonform/wiki#alternative-sections

this lets you control the visibility/access of a set of fields based on a selection 

then you don't need an event handler at all

the playground example uses a simple field change, but you can use a section to group fields per the doc
https://jsonform.github.io/jsonform/playground/index.html?example=fields-selectfieldset

**Comment by sdetweil** [comment]
in your case it looks like you may need nested selectfieldsets.. 
note you can have fields in the schema just to hold the enums and never show them directly except as select choices
the key: value in the form would reference those enum lists

**Comment by lethuy123** [comment]
Thank you so much for your help, @sdetweil !

**Comment by sdetweil** [comment]
have you been able to get it working? can we close this?

**Comment by lethuy123** [comment]
It works now. Please help me to close this issue.
