### ISSUE TITLE
How to get password field real value on the page

### ISSUE THREAD

**Issue by njuptlzf** [jsonform/jsonform#460]
i use https://github.com/eclipsesource/jsonforms-react-seed, 
![image](https://github.com/user-attachments/assets/f686ad95-49f2-4940-a6ff-f557f56df092)

uischema
```json
        {
          "type": "Control",
          "scope": "#/properties/postgres/properties/password",
          "options": {
            "type": "password",
            "format": "password"
          }
        }
```
jsonschema
```json
        "password": {
          "type": "string",
          "format": "password",
          "description": "postgres password",
          "minLength": 5
        }
```

**Comment by sdetweil** [comment]
i don't understand. what are you trying to say?

**Comment by sdetweil** [comment]
https://github.com/eclipsesource/jsonforms-react-seed,

thats not ths library.
but to SHOW the text of a '*** password field., you would have to move it to a text field (not ***) 
so you could hide/show  a text field over the pw field  by clicking hide/show button (with an onClick hander)
