### ISSUE TITLE
Submission fails when a key's required property uses "true" instead of true

### ISSUE THREAD

**Issue by tidoust** [jsonform/jsonform#53]
A key such as:

``` json
{
 "type": "string",
 "title": "Required key",
 "required": "true"
}
```

... will make the submission crash. The problem seems to come from the fact that `"true"` is not `true`. At a minimum, JSONForm should report the fact that the `required` property has an invalid value.

**Comment by tchapi** [comment]
This is already fixed, in fact, in the current version; closing.
