### ISSUE TITLE
Support relative $ref references

### ISSUE THREAD

**Issue by tidoust** [jsonform/jsonform#54]
As raised in #43, JSONForm does not yet support schemas that use the `$ref` JSON Schema keyword.

At a minimum, JSONForm should support internal references. Support for external references may be harder to achieve due to the async nature of such references.

See [JSON Reference](http://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03) and JSON Schema [URI resolution scope alteration with the "id" keyword](http://json-schema.org/latest/json-schema-core.html#anchor27) for details.

**Comment by englercj** [comment]
Bump! Looking to use this in a new project, but we have a complex json schema accross many files using many $refs.

It would be great to add each schema object to jsonform then generate a form.

**Comment by Bluesoniq** [comment]
resolveRefs(data.schema, data.schema.definitions);
$('form').jsonForm(data);
-----------------------------------------------------------------------
Uncaught RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at escapeSelector (jsonform.js:101)
    at formTree.buildFromLayout (jsonform.js:3108)
    at formTree.<anonymous> (jsonform.js:3196)
    at underscore.js:73

**Comment by sciurius** [comment]
Please reopen.

**Comment by sdetweil** [comment]
is there a definition of what the ref link should look like?  I have some time

**Comment by sciurius** [comment]
https://json-schema.org/understanding-json-schema/structuring.html

**Comment by sdetweil** [comment]
@sciurius  thx.. is there a place to talk about this outside of this issue?

**Comment by sdetweil** [comment]
i know its been 7 years, 
so this is a specific subset of the jsonform.org spec which allows all kinds of target refs (not just 'definitions')

I think this needs a hash of already resolved links, to prevent recursion, and probably have to make a resolved copy of the target
so you don't trapse into it every time. oops. resolved.. 

it is ok to stomp on the source definition? 
```
function resolveRefs(obj, defs)
{
  Object.keys(obj).forEach(function(prop, index, array){
    var def = obj[prop];

    if (def.$ref) {
      var ref = def.$ref.replace(/^#\/definitions\//, '');
      obj[prop] = defs[ref];
    } else if (typeof def === 'object') {
      resolveRefs(def, defs);
    }
  })
}
```
and the uri resolution decoder.. , ~0, ~1 and %nn

external would never work for my use (unless it was a full URI), as the lib doesn't know where THIS doc came from as its loaded directly via javascript.

**Comment by tchapi** [comment]
External refs (/schemas) should not be in the scope of this feature, you're right.

For internal refs (/definitions), we should process the `definitions` property first, and then replace them where needed. I would implement this as a pre-processor, I think, and directly modify the JSON object that is fed to JSONForm

**Comment by sdetweil** [comment]
in general I agree. the example is recursive, as it uses the definition IN the definition. not sure how to update the object with this.

**Comment by tchapi** [comment]
In the spec, the loop is ok for the validation process, but in our case where we need to construct the form, it's slightly more complicated. I think we might need to stop at the first level. Maybe put a parameter for this, like `levels: <integer>` for instance ? Or a "global" parameter in the JSONForm object that could be overriden ? I'm not sure...

**Comment by sdetweil** [comment]
I was thinking stop at the 1st level.
the question is what do you put in the schema for any secondary?, or is that an error? then the example would fail. 

thus rule : no refs in /definitions

**Comment by tchapi** [comment]
And no `{ "$ref": "#" }` too.

I think that we should be able to display an error stating the probleme

**Comment by sdetweil** [comment]
just fyi, I got jammed on another project suddenly..   so my 'free' time evaporated

**Comment by tchapi** [comment]
That's alright, don't worry :)

**Comment by jwlodek** [comment]
Ran into this today. Any chance support for this could be added?

**Comment by sdetweil** [comment]
Sadly it takes more effort than of us have had. Welcome a PR
