### ISSUE TITLE
Multidimensional array support

### ISSUE THREAD

**Issue by butters16** [jsonform/jsonform#62]
Need support for the following:

``` json
"blah": {
  "type": "array",
  "items": {
    "type": "array",
    "items": {
      "type": "number"
    }
  }
}
```

I tried to make a fix that allowed loading the form (https://github.com/joshfire/jsonform/pull/61), but there is more to change to make it actually function. For now, I will just make an array of objects containing arrays, which seems to be supported. Like this:

``` json
"blah": {
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "blah_inner": {
        "type": "array",
        "items": {
          "type": "number"
        }
      }
    }
  }
```

**Comment by tchapi** [comment]
Seems to be fixed - the other bug remains open
