### ISSUE TITLE
tabarray - Drag and drop Vs. default values

### ISSUE THREAD

**Issue by yonromai** [jsonform/jsonform#64]
Hi!

First of all, thanks a ton for this great lib.

I found the drag and drop feature of arrays super useful to reorder the elements of an array. This feature works fine in playground but whenever some inital values are provided (via the `value` field), the re-ordering does not propagate to the original array.

After a quick diagnosis, it looks like the templating I used (like `"title": "{{values.my_list[]}}"`) caused this problem.

Any plan to fix this?

Merci,
Romain

**Comment by thanhngch** [comment]
Can change default value {{values.xx}} with
```js
// #dynamic-form is id of dynamic form
$("#dynamic-form" ).on("sortstop", '.ui-sortable', function( event, ui ) {
     // do something update value on sort stop        
});
```
