### ISSUE TITLE
knockout js

### ISSUE THREAD

**Issue by srkamineni** [jsonform/jsonform#92]
This is a newbie question.  I am trying to integrate jsonform with knockout to observe changes in the form.  I have a huge json file that needs to be edited in pieces.  I need the datasource/mvvm kind of model to track all the changes in the form to persist at the server later.

I need to add data-bind attributes to the existing input elements in json form.  I went thru all the examples it doesn't help

Thanks for any ideas.

**Comment by tchapi** [comment]
_I'm closing this issue since it is probably outdated — Please reopen if you still need help on this. Thanks_
