### ISSUE TITLE
Reset and load

### ISSUE THREAD

**Issue by pedroalmeidabp** [jsonform/jsonform#96]
Is it possible to reset all fields to their initial values?

Another feature i would need is after creating the form, a way to load the "values" in runtime. Is there a way at the moment to do that?

**Comment by DRVTiny** [comment]
The same question.
My submit action is controlled by JS, but i have to do location.reload() in submit handler to reset form fields to its initial states. I can use jQuery reset() on generated form id, but maybe there is more sophisticated/clever method to reset jsonform state? I want to keep my websockets properly working after sumbit, but AFAIK after location.reload websocket connections will be losted.

**Comment by tchapi** [comment]
If I understand correctly, You could reset the whole form by emptying and reiniting it as in https://github.com/jsonform/jsonform/issues/126.

Is that what you're looking for ?

**Comment by Asef00** [comment]
I've got the same issue. I'm using jQuery `reset()` to reset the whole form. But then, I lost default values that passed in form init.
