### ISSUE TITLE
onClick: submit()

### ISSUE THREAD

**Issue by davidrubin** [jsonform/jsonform#97]
I have been digging at the code for a while, but haven't figured out how to call the submit function when the user clicks on a radio button.

This is what I'd like to accomplish. Could someone please tell me how. Thanks! 

```
  {
  "schema": {
    "language": {
      "type": "string",
      "title": "Best language",
      "enum": [ "JavaScript", "Python", "PHP", "Java", "C++", "other" ]
    }
  },
  "form": [
    {
      "key": "language",
      "type": "radiobuttons",
      "activeClass": "btn-success",
      "onClick": function () {
       submit();     
      }
    }
  ]
} 

```

**Comment by tchapi** [comment]
You could trigger a click on the submit button of the form, or call `$('form').submit()` if you don't have one. This should work
